// Code generated by Scalar SDK Generator. DO NOT EDIT.

package sdk

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"github.com/scalar/scalar-go/internal/apijson"
	"github.com/scalar/scalar-go/internal/param"
	"github.com/scalar/scalar-go/internal/requestconfig"
	"github.com/scalar/scalar-go/option"
)

// AccessGroupDomainService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewAccessGroupDomainService] method instead.
type AccessGroupDomainService struct {
	Options []option.RequestOption
}

// NewAccessGroupDomainService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewAccessGroupDomainService(opts ...option.RequestOption) (r *AccessGroupDomainService) {
	r = &AccessGroupDomainService{}
	r.Options = opts
	return
}

// Allow an exact email domain in a group. Requires docs edit permission. A group supports up to 1000 domains.
//
// Parameters:
//
//	ctx: Context for the request.
//	slug: Path parameter.
//	body: AccessGroupDomainNewParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*map[string]interface{}: Default Response
//
// Example:
//
//	domain, err := client.AccessGroups.Domains.New(context.Background(), "slug", sdk.AccessGroupDomainNewParams{
//		Domain: sdk.F[string](""),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(domain)
func (r *AccessGroupDomainService) New(ctx context.Context, slug string, body AccessGroupDomainNewParams, opts ...option.RequestOption) (res *map[string]interface{}, err error) {
	opts = slices.Concat(r.Options, opts)
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/access-groups/%s/domains", url.PathEscape(slug))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Remove an exact email domain from a group. Requires docs edit permission. Other allowed domains and emails are preserved.
//
// Parameters:
//
//	ctx: Context for the request.
//	slug: Path parameter.
//	body: AccessGroupDomainDeleteParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*map[string]interface{}: Default Response
//
// Example:
//
//	domain, err := client.AccessGroups.Domains.Delete(context.Background(), "slug", sdk.AccessGroupDomainDeleteParams{
//		Domain: sdk.F[string](""),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(domain)
func (r *AccessGroupDomainService) Delete(ctx context.Context, slug string, body AccessGroupDomainDeleteParams, opts ...option.RequestOption) (res *map[string]interface{}, err error) {
	opts = slices.Concat(r.Options, opts)
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/access-groups/%s/domains", url.PathEscape(slug))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, body, &res, opts...)
	return res, err
}

type AccessGroupDomainNewParams struct {
	Domain param.Field[string] `json:"domain" api:"required"`
}

func (r AccessGroupDomainNewParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type AccessGroupDomainDeleteParams struct {
	Domain param.Field[string] `json:"domain" api:"required"`
}

func (r AccessGroupDomainDeleteParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}
