// Code generated by Scalar SDK Generator. DO NOT EDIT.

package sdk

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"github.com/scalar/scalar-go/internal/apijson"
	"github.com/scalar/scalar-go/internal/param"
	"github.com/scalar/scalar-go/internal/requestconfig"
	"github.com/scalar/scalar-go/option"
)

// AccessGroupService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewAccessGroupService] method instead.
type AccessGroupService struct {
	Options []option.RequestOption
	Domains *AccessGroupDomainService
}

// NewAccessGroupService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewAccessGroupService(opts ...option.RequestOption) (r *AccessGroupService) {
	r = &AccessGroupService{}
	r.Options = opts
	r.Domains = NewAccessGroupDomainService(opts...)
	return
}

// Create a group for the current team. Requires docs edit permission and the access groups billing feature. Domains are exact email domains, without wildcards or implicit subdomain matching.
//
// Parameters:
//
//	ctx: Context for the request.
//	body: AccessGroupNewParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*AccessGroupNewResponse: Default Response
//
// Example:
//
//	accessGroup, err := client.AccessGroups.New(context.Background(), sdk.AccessGroupNewParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(accessGroup)
func (r *AccessGroupService) New(ctx context.Context, body AccessGroupNewParams, opts ...option.RequestOption) (res *AccessGroupNewResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/access-groups"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Get a group and its email and domain allowlists by slug.
//
// Parameters:
//
//	ctx: Context for the request.
//	slug: Path parameter.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*AccessGroupGetResponse: Default Response
//
// Example:
//
//	accessGroup, err := client.AccessGroups.Get(context.Background(), "slug")
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(accessGroup)
func (r *AccessGroupService) Get(ctx context.Context, slug string, opts ...option.RequestOption) (res *AccessGroupGetResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/access-groups/%s", url.PathEscape(slug))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Update group metadata. Requires docs edit permission. After changing the slug, use the new slug in subsequent requests.
//
// Parameters:
//
//	ctx: Context for the request.
//	slug: Path parameter.
//	body: AccessGroupUpdateParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*map[string]interface{}: Default Response
//
// Example:
//
//	accessGroup, err := client.AccessGroups.Update(context.Background(), "slug", sdk.AccessGroupUpdateParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(accessGroup)
func (r *AccessGroupService) Update(ctx context.Context, slug string, body AccessGroupUpdateParams, opts ...option.RequestOption) (res *map[string]interface{}, err error) {
	opts = slices.Concat(r.Options, opts)
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/access-groups/%s", url.PathEscape(slug))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPatch, path, body, &res, opts...)
	return res, err
}

// Delete a group and remove its project assignments. Requires docs edit permission.
//
// Parameters:
//
//	ctx: Context for the request.
//	slug: Path parameter.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*map[string]interface{}: Default Response
//
// Example:
//
//	accessGroup, err := client.AccessGroups.Delete(context.Background(), "slug")
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(accessGroup)
func (r *AccessGroupService) Delete(ctx context.Context, slug string, opts ...option.RequestOption) (res *map[string]interface{}, err error) {
	opts = slices.Concat(r.Options, opts)
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/access-groups/%s", url.PathEscape(slug))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, nil, &res, opts...)
	return res, err
}

type AccessGroupNewParams struct {
	AllowedDomains param.Field[interface{}] `json:"allowedDomains"`
	Name           param.Field[string]      `json:"name"`
	Slug           param.Field[string]      `json:"slug"`
}

func (r AccessGroupNewParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type AccessGroupUpdateParams struct {
	Name param.Field[string] `json:"name"`
	Slug param.Field[string] `json:"slug"`
}

func (r AccessGroupUpdateParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type AccessGroupNewResponse struct {
	AllowedDomains interface{}                `json:"allowedDomains" api:"required"`
	AllowedEmails  interface{}                `json:"allowedEmails" api:"required"`
	Name           string                     `json:"name" api:"required"`
	Slug           string                     `json:"slug" api:"required"`
	UID            string                     `json:"uid" api:"required"`
	JSON           accessGroupNewResponseJSON `json:"-"`
}

// accessGroupNewResponseJSON contains the JSON metadata for the struct [AccessGroupNewResponse]
type accessGroupNewResponseJSON struct {
	AllowedDomains apijson.Field
	AllowedEmails  apijson.Field
	Name           apijson.Field
	Slug           apijson.Field
	UID            apijson.Field
	raw            string
	ExtraFields    map[string]apijson.Field
}

func (r *AccessGroupNewResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r accessGroupNewResponseJSON) RawJSON() string {
	return r.raw
}

type AccessGroupGetResponse struct {
	AllowedDomains interface{}                `json:"allowedDomains" api:"required"`
	AllowedEmails  interface{}                `json:"allowedEmails" api:"required"`
	Name           string                     `json:"name" api:"required"`
	Slug           string                     `json:"slug" api:"required"`
	UID            string                     `json:"uid" api:"required"`
	JSON           accessGroupGetResponseJSON `json:"-"`
}

// accessGroupGetResponseJSON contains the JSON metadata for the struct [AccessGroupGetResponse]
type accessGroupGetResponseJSON struct {
	AllowedDomains apijson.Field
	AllowedEmails  apijson.Field
	Name           apijson.Field
	Slug           apijson.Field
	UID            apijson.Field
	raw            string
	ExtraFields    map[string]apijson.Field
}

func (r *AccessGroupGetResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r accessGroupGetResponseJSON) RawJSON() string {
	return r.raw
}
