// Code generated by Scalar SDK Generator. DO NOT EDIT.

package sdk

import (
	"github.com/scalar/scalar-go/internal/apierror"
	"github.com/scalar/scalar-go/shared"
)

type Error = apierror.Error

type Value400 = shared.Value400

type Value401 = shared.Value401

type Value403 = shared.Value403

type Value404 = shared.Value404

type Value422 = shared.Value422

type Value500 = shared.Value500

type Nanoid = shared.Nanoid

type Namespace = shared.Namespace

type ManagedDocVersion = shared.ManagedDocVersion

type ManagedDocVersionTool = shared.ManagedDocVersionTool

type ManagedDocVersionToolsEnabledTool = shared.ManagedDocVersionToolsEnabledTool

const (
	ManagedDocVersionToolsEnabledToolExecuteRequest     = shared.ManagedDocVersionToolsEnabledToolExecuteRequest
	ManagedDocVersionToolsEnabledToolGetMiniOpenapiSpec = shared.ManagedDocVersionToolsEnabledToolGetMiniOpenapiSpec
)

type ManagedDocVersionEmbedStatus = shared.ManagedDocVersionEmbedStatus

const (
	ManagedDocVersionEmbedStatusComplete = shared.ManagedDocVersionEmbedStatusComplete
	ManagedDocVersionEmbedStatusFailed   = shared.ManagedDocVersionEmbedStatusFailed
)

type Timestamp = shared.Timestamp

type UID = shared.UID
