// Code generated by Scalar SDK Generator. DO NOT EDIT.

package scalarapi

import (
	"github.com/scalar/scalar-go/internal/apierror"
	"github.com/scalar/scalar-go/packages/param"
)

// aliased to make [param.APIUnion] private when embedding
type paramUnion = param.APIUnion

// aliased to make [param.APIObject] private when embedding
type paramObj = param.APIObject

type Error = apierror.Error
