// Code generated by Scalar SDK Generator. DO NOT EDIT.

package scalarapi

import (
	"context"
	"net/http"
	"slices"

	"scalar-api/internal/apijson"
	"scalar-api/internal/requestconfig"
	"scalar-api/option"
	"scalar-api/packages/param"
	"scalar-api/packages/respjson"
)

// AuthenticationService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewAuthenticationService] method instead.
type AuthenticationService struct {
	options []option.RequestOption
}

// NewAuthenticationService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewAuthenticationService(opts ...option.RequestOption) AuthenticationService {
	s := AuthenticationService{}
	s.options = opts
	return s
}

// Exchange an API key for an access token.
func (r *AuthenticationService) ExchangePersonalToken(ctx context.Context, body AuthenticationExchangePersonalTokenParams, opts ...option.RequestOption) (res *AuthenticationExchangePersonalTokenResponse, err error) {
	opts = slices.Concat(r.options, opts)
	requestPath := "v1/auth/exchange"
	res = new(AuthenticationExchangePersonalTokenResponse)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, requestPath, body, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type AuthenticationExchangePersonalTokenParams struct {
	PersonalToken string `json:"personalToken" api:"required"`
	paramObj
}

func (r AuthenticationExchangePersonalTokenParams) MarshalJSON() (data []byte, err error) {
	type shadow AuthenticationExchangePersonalTokenParams
	return param.MarshalObject(r, (*shadow)(&r))
}
func (r *AuthenticationExchangePersonalTokenParams) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Get the authenticated user, including their available teams and theme.
func (r *AuthenticationService) ListCurrentUser(ctx context.Context, opts ...option.RequestOption) (res *User, err error) {
	opts = slices.Concat(r.options, opts)
	requestPath := "v1/auth/me"
	res = new(User)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, requestPath, nil, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type AuthenticationExchangePersonalTokenResponse struct {
	AccessToken string `json:"accessToken" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		AccessToken respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// RawJSON returns the unmodified JSON received from the API.
func (r AuthenticationExchangePersonalTokenResponse) RawJSON() string { return r.JSON.raw }
func (r *AuthenticationExchangePersonalTokenResponse) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}
