// Code generated by Scalar SDK Generator. DO NOT EDIT.

package sdk

import (
	"context"
	"net/http"
	"slices"

	"github.com/scalar/scalar-go/internal/apijson"
	"github.com/scalar/scalar-go/internal/param"
	"github.com/scalar/scalar-go/internal/requestconfig"
	"github.com/scalar/scalar-go/option"
)

// AuthenticationService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewAuthenticationService] method instead.
type AuthenticationService struct {
	Options []option.RequestOption
}

// NewAuthenticationService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewAuthenticationService(opts ...option.RequestOption) (r *AuthenticationService) {
	r = &AuthenticationService{}
	r.Options = opts
	return
}

// Exchange an API key for an access token.
//
// Parameters:
//
//	ctx: Context for the request.
//	body: AuthenticationExchangePersonalTokenParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*AuthenticationExchangePersonalTokenResponse: Default Response
//
// Example:
//
//	authentication, err := client.Authentication.ExchangePersonalToken(context.Background(), sdk.AuthenticationExchangePersonalTokenParams{
//		PersonalToken: sdk.F[string](""),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(authentication)
func (r *AuthenticationService) ExchangePersonalToken(ctx context.Context, body AuthenticationExchangePersonalTokenParams, opts ...option.RequestOption) (res *AuthenticationExchangePersonalTokenResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/auth/exchange"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Get the authenticated user, including their available teams and theme.
//
// Parameters:
//
//	ctx: Context for the request.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*AuthenticationListCurrentUserResponse: Default Response
//
// Example:
//
//	authentication, err := client.Authentication.ListCurrentUser(context.Background())
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(authentication)
func (r *AuthenticationService) ListCurrentUser(ctx context.Context, opts ...option.RequestOption) (res *AuthenticationListCurrentUserResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/auth/me"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

type AuthenticationListCurrentUserResponse struct {
	UID          string                                      `json:"uid" api:"required"`
	CreatedAt    int64                                       `json:"createdAt" api:"required"`
	UpdatedAt    int64                                       `json:"updatedAt" api:"required"`
	Email        string                                      `json:"email" api:"required" format:"email"`
	ActiveTeamID string                                      `json:"activeTeamId" api:"required,nullable"`
	HasGithub    bool                                        `json:"hasGithub" api:"required"`
	Teams        []AuthenticationListCurrentUserResponseTeam `json:"teams" api:"required"`
	Theme        string                                      `json:"theme"`
	JSON         authenticationListCurrentUserResponseJSON   `json:"-"`
}

// authenticationListCurrentUserResponseJSON contains the JSON metadata for the struct [AuthenticationListCurrentUserResponse]
type authenticationListCurrentUserResponseJSON struct {
	UID          apijson.Field
	CreatedAt    apijson.Field
	UpdatedAt    apijson.Field
	Email        apijson.Field
	ActiveTeamID apijson.Field
	HasGithub    apijson.Field
	Teams        apijson.Field
	Theme        apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *AuthenticationListCurrentUserResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r authenticationListCurrentUserResponseJSON) RawJSON() string {
	return r.raw
}

type AuthenticationExchangePersonalTokenParams struct {
	PersonalToken param.Field[string] `json:"personalToken" api:"required"`
}

func (r AuthenticationExchangePersonalTokenParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type AuthenticationExchangePersonalTokenResponse struct {
	AccessToken string                                          `json:"accessToken" api:"required"`
	JSON        authenticationExchangePersonalTokenResponseJSON `json:"-"`
}

// authenticationExchangePersonalTokenResponseJSON contains the JSON metadata for the struct [AuthenticationExchangePersonalTokenResponse]
type authenticationExchangePersonalTokenResponseJSON struct {
	AccessToken apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *AuthenticationExchangePersonalTokenResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r authenticationExchangePersonalTokenResponseJSON) RawJSON() string {
	return r.raw
}

type AuthenticationListCurrentUserResponseTeam struct {
	UID      string                                        `json:"uid" api:"required"`
	Name     string                                        `json:"name" api:"required"`
	ImageURI string                                        `json:"imageUri"`
	JSON     authenticationListCurrentUserResponseTeamJSON `json:"-"`
}

// authenticationListCurrentUserResponseTeamJSON contains the JSON metadata for the struct [AuthenticationListCurrentUserResponseTeam]
type authenticationListCurrentUserResponseTeamJSON struct {
	UID         apijson.Field
	Name        apijson.Field
	ImageURI    apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *AuthenticationListCurrentUserResponseTeam) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r authenticationListCurrentUserResponseTeamJSON) RawJSON() string {
	return r.raw
}
