// Code generated by Scalar SDK Generator. DO NOT EDIT.

package scalarapi

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"scalar-api/internal/apijson"
	"scalar-api/internal/requestconfig"
	"scalar-api/option"
	"scalar-api/packages/param"
	"scalar-api/packages/respjson"
)

// LoginPortalService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewLoginPortalService] method instead.
type LoginPortalService struct {
	options []option.RequestOption
}

// NewLoginPortalService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewLoginPortalService(opts ...option.RequestOption) LoginPortalService {
	s := LoginPortalService{}
	s.options = opts
	return s
}

// Get a login portal by slug.
func (r *LoginPortalService) Get(ctx context.Context, slug string, opts ...option.RequestOption) (res *LoginPortalGetResponse, err error) {
	opts = slices.Concat(r.options, opts)
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	requestPath := fmt.Sprintf("v1/login-portals/%s", url.PathEscape(slug))
	res = new(LoginPortalGetResponse)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, requestPath, nil, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

// Update metadata for a login portal.
func (r *LoginPortalService) Update(ctx context.Context, slug string, body LoginPortalUpdateParams, opts ...option.RequestOption) (res *map[string]any, err error) {
	opts = slices.Concat(r.options, opts)
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	requestPath := fmt.Sprintf("v1/login-portals/%s", url.PathEscape(slug))
	res = new(map[string]any)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPatch, requestPath, body, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type LoginPortalUpdateParams struct {
	Title param.Opt[string] `json:"title,omitzero"`
	paramObj
}

func (r LoginPortalUpdateParams) MarshalJSON() (data []byte, err error) {
	type shadow LoginPortalUpdateParams
	return param.MarshalObject(r, (*shadow)(&r))
}
func (r *LoginPortalUpdateParams) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Delete a login portal.
func (r *LoginPortalService) Delete(ctx context.Context, slug string, opts ...option.RequestOption) (res *map[string]any, err error) {
	opts = slices.Concat(r.options, opts)
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	requestPath := fmt.Sprintf("v1/login-portals/%s", url.PathEscape(slug))
	res = new(map[string]any)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, requestPath, nil, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

// Create a login portal for the current team.
func (r *LoginPortalService) New(ctx context.Context, body LoginPortalNewParams, opts ...option.RequestOption) (res *UID, err error) {
	opts = slices.Concat(r.options, opts)
	requestPath := "v1/login-portals"
	res = new(UID)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, requestPath, body, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type LoginPortalNewParams struct {
	Email LoginPortalEmail `json:"email,omitzero" api:"required"`
	Page LoginPortalPage `json:"page,omitzero" api:"required"`
	Slug string `json:"slug" api:"required"`
	Title string `json:"title" api:"required"`
	paramObj
}

func (r LoginPortalNewParams) MarshalJSON() (data []byte, err error) {
	type shadow LoginPortalNewParams
	return param.MarshalObject(r, (*shadow)(&r))
}
func (r *LoginPortalNewParams) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// List all login portals for the current team.
func (r *LoginPortalService) List(ctx context.Context, opts ...option.RequestOption) (res *[]LoginPortal, err error) {
	opts = slices.Concat(r.options, opts)
	requestPath := "v1/login-portals"
	res = new([]LoginPortal)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, requestPath, nil, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type LoginPortalGetResponse struct {
	Email LoginPortalEmail `json:"email" api:"required"`
	Page LoginPortalPage `json:"page" api:"required"`
	Slug string `json:"slug" api:"required"`
	Title string `json:"title" api:"required"`
	UID string `json:"uid" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Email respjson.Field
		Page respjson.Field
		Slug respjson.Field
		Title respjson.Field
		UID respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// RawJSON returns the unmodified JSON received from the API.
func (r LoginPortalGetResponse) RawJSON() string { return r.JSON.raw }
func (r *LoginPortalGetResponse) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type LoginPortalEmail struct {
	ButtonBackground string `json:"buttonBackground" api:"required"`
	ButtonColor string `json:"buttonColor" api:"required"`
	ButtonText string `json:"buttonText" api:"required"`
	CardBackground string `json:"cardBackground" api:"required"`
	CardColor string `json:"cardColor" api:"required"`
	Logo string `json:"logo" api:"required"`
	LogoSize string `json:"logoSize" api:"required"`
	MainBackground string `json:"mainBackground" api:"required"`
	MainColor string `json:"mainColor" api:"required"`
	Message string `json:"message" api:"required"`
	Title string `json:"title" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		ButtonBackground respjson.Field
		ButtonColor respjson.Field
		ButtonText respjson.Field
		CardBackground respjson.Field
		CardColor respjson.Field
		Logo respjson.Field
		LogoSize respjson.Field
		MainBackground respjson.Field
		MainColor respjson.Field
		Message respjson.Field
		Title respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// RawJSON returns the unmodified JSON received from the API.
func (r LoginPortalEmail) RawJSON() string { return r.JSON.raw }
func (r *LoginPortalEmail) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type LoginPortalPage struct {
	CompanyName string `json:"companyName" api:"required"`
	Description string `json:"description" api:"required"`
	Favicon string `json:"favicon" api:"required"`
	FormDescription string `json:"formDescription" api:"required"`
	FormImage string `json:"formImage" api:"required"`
	FormTitle string `json:"formTitle" api:"required"`
	Head string `json:"head" api:"required"`
	Logo string `json:"logo" api:"required"`
	LogoURL string `json:"logoURL" api:"required"`
	PrivacyLink string `json:"privacyLink" api:"required"`
	Script string `json:"script" api:"required"`
	TermsLink string `json:"termsLink" api:"required"`
	Theme string `json:"theme" api:"required"`
	Title string `json:"title" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		CompanyName respjson.Field
		Description respjson.Field
		Favicon respjson.Field
		FormDescription respjson.Field
		FormImage respjson.Field
		FormTitle respjson.Field
		Head respjson.Field
		Logo respjson.Field
		LogoURL respjson.Field
		PrivacyLink respjson.Field
		Script respjson.Field
		TermsLink respjson.Field
		Theme respjson.Field
		Title respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// RawJSON returns the unmodified JSON received from the API.
func (r LoginPortalPage) RawJSON() string { return r.JSON.raw }
func (r *LoginPortalPage) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}
