// Code generated by Scalar SDK Generator. DO NOT EDIT.

package scalargo

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"github.com/scalar/scalar-go/internal/apijson"
	"github.com/scalar/scalar-go/internal/param"
	"github.com/scalar/scalar-go/internal/requestconfig"
	"github.com/scalar/scalar-go/option"
)

// LoginPortalService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewLoginPortalService] method instead.
type LoginPortalService struct {
	Options []option.RequestOption
}

// NewLoginPortalService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewLoginPortalService(opts ...option.RequestOption) (r *LoginPortalService) {
	r = &LoginPortalService{}
	r.Options = opts
	return
}

// Get a login portal by slug.
//
// Parameters:
//
//	ctx: Context for the request.
//	slug: Path parameter.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*LoginPortalGetResponse: Default Response
//
// Example:
//
//	loginPortal, err := client.LoginPortals.Get(context.Background(), "slug")
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(loginPortal)
func (r *LoginPortalService) Get(ctx context.Context, slug string, opts ...option.RequestOption) (res *LoginPortalGetResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/login-portals/%s", url.PathEscape(slug))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Update metadata for a login portal.
//
// Parameters:
//
//	ctx: Context for the request.
//	slug: Path parameter.
//	body: LoginPortalUpdateParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*map[string]interface{}: Default Response
//
// Example:
//
//	loginPortal, err := client.LoginPortals.Update(context.Background(), "slug", sdk.LoginPortalUpdateParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(loginPortal)
func (r *LoginPortalService) Update(ctx context.Context, slug string, body LoginPortalUpdateParams, opts ...option.RequestOption) (res *map[string]interface{}, err error) {
	opts = slices.Concat(r.Options, opts)
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/login-portals/%s", url.PathEscape(slug))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPatch, path, body, &res, opts...)
	return res, err
}

// Delete a login portal.
//
// Parameters:
//
//	ctx: Context for the request.
//	slug: Path parameter.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*map[string]interface{}: Default Response
//
// Example:
//
//	loginPortal, err := client.LoginPortals.Delete(context.Background(), "slug")
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(loginPortal)
func (r *LoginPortalService) Delete(ctx context.Context, slug string, opts ...option.RequestOption) (res *map[string]interface{}, err error) {
	opts = slices.Concat(r.Options, opts)
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/login-portals/%s", url.PathEscape(slug))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, nil, &res, opts...)
	return res, err
}

// Create a login portal for the current team.
//
// Parameters:
//
//	ctx: Context for the request.
//	body: LoginPortalNewParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*LoginPortalNewResponse: Default Response
//
// Example:
//
//	loginPortal, err := client.LoginPortals.New(context.Background(), sdk.LoginPortalNewParams{
//		Email: sdk.F[sdk.LoginPortalEmailParam](sdk.LoginPortalEmailParam{
//			Logo:             sdk.F[string](""),
//			LogoSize:         sdk.F[string]("100"),
//			ButtonText:       sdk.F[string]("Login"),
//			Message:          sdk.F[string]("Click to access private documentation hosted by scalar.com"),
//			Title:            sdk.F[string]("Private Docs"),
//			MainColor:        sdk.F[string]("#2a2f45"),
//			MainBackground:   sdk.F[string]("#f6f6f6"),
//			CardColor:        sdk.F[string]("2a2f45"),
//			CardBackground:   sdk.F[string]("#fff"),
//			ButtonColor:      sdk.F[string]("#fff"),
//			ButtonBackground: sdk.F[string]("#0f0f0f"),
//		}),
//		Page: sdk.F[sdk.LoginPortalPageParam](sdk.LoginPortalPageParam{
//			Title:           sdk.F[string]("Scalar Private Docs"),
//			Description:     sdk.F[string]("Login to access your documentation"),
//			Head:            sdk.F[string](""),
//			Script:          sdk.F[string](""),
//			Theme:           sdk.F[string](""),
//			CompanyName:     sdk.F[string](""),
//			Logo:            sdk.F[string](""),
//			LogoURL:         sdk.F[string](""),
//			Favicon:         sdk.F[string](""),
//			TermsLink:       sdk.F[string](""),
//			PrivacyLink:     sdk.F[string](""),
//			FormTitle:       sdk.F[string]("Scalar Private Docs"),
//			FormDescription: sdk.F[string]("Login to access your documentation"),
//			FormImage:       sdk.F[string](""),
//		}),
//		Slug:  sdk.F[string](""),
//		Title: sdk.F[string](""),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(loginPortal)
func (r *LoginPortalService) New(ctx context.Context, body LoginPortalNewParams, opts ...option.RequestOption) (res *LoginPortalNewResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/login-portals"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// List all login portals for the current team.
//
// Parameters:
//
//	ctx: Context for the request.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*[]LoginPortal: Default Response
//
// Example:
//
//	loginPortal, err := client.LoginPortals.List(context.Background())
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(loginPortal)
func (r *LoginPortalService) List(ctx context.Context, opts ...option.RequestOption) (res *[]LoginPortal, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/login-portals"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

type LoginPortalEmail struct {
	Logo             string               `json:"logo" api:"required"`
	LogoSize         string               `json:"logoSize" api:"required"`
	ButtonText       string               `json:"buttonText" api:"required"`
	Message          string               `json:"message" api:"required"`
	Title            string               `json:"title" api:"required"`
	MainColor        string               `json:"mainColor" api:"required"`
	MainBackground   string               `json:"mainBackground" api:"required"`
	CardColor        string               `json:"cardColor" api:"required"`
	CardBackground   string               `json:"cardBackground" api:"required"`
	ButtonColor      string               `json:"buttonColor" api:"required"`
	ButtonBackground string               `json:"buttonBackground" api:"required"`
	JSON             loginPortalEmailJSON `json:"-"`
}

// loginPortalEmailJSON contains the JSON metadata for the struct [LoginPortalEmail]
type loginPortalEmailJSON struct {
	Logo             apijson.Field
	LogoSize         apijson.Field
	ButtonText       apijson.Field
	Message          apijson.Field
	Title            apijson.Field
	MainColor        apijson.Field
	MainBackground   apijson.Field
	CardColor        apijson.Field
	CardBackground   apijson.Field
	ButtonColor      apijson.Field
	ButtonBackground apijson.Field
	raw              string
	ExtraFields      map[string]apijson.Field
}

func (r *LoginPortalEmail) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r loginPortalEmailJSON) RawJSON() string {
	return r.raw
}

type LoginPortalEmailParam struct {
	ButtonBackground param.Field[string] `json:"buttonBackground" api:"required"`
	ButtonColor      param.Field[string] `json:"buttonColor" api:"required"`
	ButtonText       param.Field[string] `json:"buttonText" api:"required"`
	CardBackground   param.Field[string] `json:"cardBackground" api:"required"`
	CardColor        param.Field[string] `json:"cardColor" api:"required"`
	Logo             param.Field[string] `json:"logo" api:"required"`
	LogoSize         param.Field[string] `json:"logoSize" api:"required"`
	MainBackground   param.Field[string] `json:"mainBackground" api:"required"`
	MainColor        param.Field[string] `json:"mainColor" api:"required"`
	Message          param.Field[string] `json:"message" api:"required"`
	Title            param.Field[string] `json:"title" api:"required"`
}

func (r LoginPortalEmailParam) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type LoginPortalPage struct {
	Title           string              `json:"title" api:"required"`
	Description     string              `json:"description" api:"required"`
	Head            string              `json:"head" api:"required"`
	Script          string              `json:"script" api:"required"`
	Theme           string              `json:"theme" api:"required"`
	CompanyName     string              `json:"companyName" api:"required"`
	Logo            string              `json:"logo" api:"required"`
	LogoURL         string              `json:"logoURL" api:"required"`
	Favicon         string              `json:"favicon" api:"required"`
	TermsLink       string              `json:"termsLink" api:"required"`
	PrivacyLink     string              `json:"privacyLink" api:"required"`
	FormTitle       string              `json:"formTitle" api:"required"`
	FormDescription string              `json:"formDescription" api:"required"`
	FormImage       string              `json:"formImage" api:"required"`
	JSON            loginPortalPageJSON `json:"-"`
}

// loginPortalPageJSON contains the JSON metadata for the struct [LoginPortalPage]
type loginPortalPageJSON struct {
	Title           apijson.Field
	Description     apijson.Field
	Head            apijson.Field
	Script          apijson.Field
	Theme           apijson.Field
	CompanyName     apijson.Field
	Logo            apijson.Field
	LogoURL         apijson.Field
	Favicon         apijson.Field
	TermsLink       apijson.Field
	PrivacyLink     apijson.Field
	FormTitle       apijson.Field
	FormDescription apijson.Field
	FormImage       apijson.Field
	raw             string
	ExtraFields     map[string]apijson.Field
}

func (r *LoginPortalPage) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r loginPortalPageJSON) RawJSON() string {
	return r.raw
}

type LoginPortalPageParam struct {
	CompanyName     param.Field[string] `json:"companyName" api:"required"`
	Description     param.Field[string] `json:"description" api:"required"`
	Favicon         param.Field[string] `json:"favicon" api:"required"`
	FormDescription param.Field[string] `json:"formDescription" api:"required"`
	FormImage       param.Field[string] `json:"formImage" api:"required"`
	FormTitle       param.Field[string] `json:"formTitle" api:"required"`
	Head            param.Field[string] `json:"head" api:"required"`
	Logo            param.Field[string] `json:"logo" api:"required"`
	LogoURL         param.Field[string] `json:"logoURL" api:"required"`
	PrivacyLink     param.Field[string] `json:"privacyLink" api:"required"`
	Script          param.Field[string] `json:"script" api:"required"`
	TermsLink       param.Field[string] `json:"termsLink" api:"required"`
	Theme           param.Field[string] `json:"theme" api:"required"`
	Title           param.Field[string] `json:"title" api:"required"`
}

func (r LoginPortalPageParam) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type LoginPortal struct {
	UID   string          `json:"uid" api:"required"`
	Title string          `json:"title" api:"required"`
	Slug  string          `json:"slug" api:"required"`
	JSON  loginPortalJSON `json:"-"`
}

// loginPortalJSON contains the JSON metadata for the struct [LoginPortal]
type loginPortalJSON struct {
	UID         apijson.Field
	Title       apijson.Field
	Slug        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *LoginPortal) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r loginPortalJSON) RawJSON() string {
	return r.raw
}

type LoginPortalNewResponse struct {
	UID  string                     `json:"uid" api:"required"`
	JSON loginPortalNewResponseJSON `json:"-"`
}

// loginPortalNewResponseJSON contains the JSON metadata for the struct [LoginPortalNewResponse]
type loginPortalNewResponseJSON struct {
	UID         apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *LoginPortalNewResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r loginPortalNewResponseJSON) RawJSON() string {
	return r.raw
}

type LoginPortalUpdateParams struct {
	Title param.Field[string] `json:"title"`
}

func (r LoginPortalUpdateParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type LoginPortalNewParams struct {
	Email param.Field[LoginPortalEmailParam] `json:"email" api:"required"`
	Page  param.Field[LoginPortalPageParam]  `json:"page" api:"required"`
	Slug  param.Field[string]                `json:"slug" api:"required"`
	Title param.Field[string]                `json:"title" api:"required"`
}

func (r LoginPortalNewParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type LoginPortalGetResponse struct {
	UID   string                     `json:"uid" api:"required"`
	Title string                     `json:"title" api:"required"`
	Slug  string                     `json:"slug" api:"required"`
	Email LoginPortalEmail           `json:"email" api:"required"`
	Page  LoginPortalPage            `json:"page" api:"required"`
	JSON  loginPortalGetResponseJSON `json:"-"`
}

// loginPortalGetResponseJSON contains the JSON metadata for the struct [LoginPortalGetResponse]
type loginPortalGetResponseJSON struct {
	UID         apijson.Field
	Title       apijson.Field
	Slug        apijson.Field
	Email       apijson.Field
	Page        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *LoginPortalGetResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r loginPortalGetResponseJSON) RawJSON() string {
	return r.raw
}
