// Code generated by Scalar SDK Generator. DO NOT EDIT.

package sdk

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"github.com/scalar/scalar-go/internal/apijson"
	"github.com/scalar/scalar-go/internal/param"
	"github.com/scalar/scalar-go/internal/requestconfig"
	"github.com/scalar/scalar-go/option"
)

// McpServerService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewMcpServerService] method instead.
type McpServerService struct {
	Options       []option.RequestOption
	Installations *McpServerInstallationService
}

// NewMcpServerService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewMcpServerService(opts ...option.RequestOption) (r *McpServerService) {
	r = &McpServerService{}
	r.Options = opts
	r.Installations = NewMcpServerInstallationService(opts...)
	return
}

// List every MCP server on the team.
//
// Parameters:
//
//	ctx: Context for the request.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*[]McpServer: Default Response
//
// Example:
//
//	server, err := client.Mcp.Servers.List(context.Background())
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(server)
func (r *McpServerService) List(ctx context.Context, opts ...option.RequestOption) (res *[]McpServer, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/mcp/servers"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Create an MCP server over one or more API document versions. The response carries the server and its first installation.
//
// Parameters:
//
//	ctx: Context for the request.
//	body: McpServerNewParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*McpServerNewResponse: Default Response
//
// Example:
//
//	server, err := client.Mcp.Servers.New(context.Background(), sdk.McpServerNewParams{
//		Name: sdk.F[string]("Acme MCP"),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(server)
func (r *McpServerService) New(ctx context.Context, body McpServerNewParams, opts ...option.RequestOption) (res *McpServerNewResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/mcp/servers"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Get a single MCP server by its id.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Path parameter.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*McpServer: Default Response
//
// Example:
//
//	server, err := client.Mcp.Servers.Get(context.Background(), "42")
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(server)
func (r *McpServerService) Get(ctx context.Context, id string, opts ...option.RequestOption) (res *McpServer, err error) {
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/mcp/servers/%s", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Update MCP server metadata and which tools it exposes.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Path parameter.
//	body: McpServerUpdateParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*McpServer: Default Response
//
// Example:
//
//	server, err := client.Mcp.Servers.Update(context.Background(), "42", sdk.McpServerUpdateParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(server)
func (r *McpServerService) Update(ctx context.Context, id string, body McpServerUpdateParams, opts ...option.RequestOption) (res *McpServer, err error) {
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/mcp/servers/%s", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPatch, path, body, &res, opts...)
	return res, err
}

// Delete an MCP server and every installation it serves.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Path parameter.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*map[string]interface{}: Default Response
//
// Example:
//
//	server, err := client.Mcp.Servers.Delete(context.Background(), "42")
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(server)
func (r *McpServerService) Delete(ctx context.Context, id string, opts ...option.RequestOption) (res *map[string]interface{}, err error) {
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/mcp/servers/%s", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, nil, &res, opts...)
	return res, err
}

type McpServer struct {
	ID                string        `json:"id" api:"required"`
	AutoAddOperations bool          `json:"autoAddOperations" api:"required"`
	CreatedAt         string        `json:"createdAt" api:"required"`
	Name              string        `json:"name" api:"required"`
	Slug              string        `json:"slug" api:"required"`
	UpdatedAt         string        `json:"updatedAt" api:"required"`
	JSON              mcpServerJSON `json:"-"`
}

// mcpServerJSON contains the JSON metadata for the struct [McpServer]
type mcpServerJSON struct {
	ID                apijson.Field
	AutoAddOperations apijson.Field
	CreatedAt         apijson.Field
	Name              apijson.Field
	Slug              apijson.Field
	UpdatedAt         apijson.Field
	raw               string
	ExtraFields       map[string]apijson.Field
}

func (r *McpServer) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r mcpServerJSON) RawJSON() string {
	return r.raw
}

type McpInstallation struct {
	ID                         string              `json:"id" api:"required"`
	AccessGroups               []string            `json:"accessGroups" api:"required"`
	CredentialRedactionEnabled bool                `json:"credentialRedactionEnabled" api:"required"`
	IsPrivate                  bool                `json:"isPrivate" api:"required"`
	LoginPortalUID             string              `json:"loginPortalUid" api:"required,nullable"`
	McpServerID                string              `json:"mcpServerId" api:"required"`
	McpVersion                 string              `json:"mcpVersion" api:"required,nullable"`
	Name                       string              `json:"name" api:"required"`
	PiiRedactionEnabled        bool                `json:"piiRedactionEnabled" api:"required"`
	Slug                       string              `json:"slug" api:"required"`
	JSON                       mcpInstallationJSON `json:"-"`
}

// mcpInstallationJSON contains the JSON metadata for the struct [McpInstallation]
type mcpInstallationJSON struct {
	ID                         apijson.Field
	AccessGroups               apijson.Field
	CredentialRedactionEnabled apijson.Field
	IsPrivate                  apijson.Field
	LoginPortalUID             apijson.Field
	McpServerID                apijson.Field
	McpVersion                 apijson.Field
	Name                       apijson.Field
	PiiRedactionEnabled        apijson.Field
	Slug                       apijson.Field
	raw                        string
	ExtraFields                map[string]apijson.Field
}

func (r *McpInstallation) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r mcpInstallationJSON) RawJSON() string {
	return r.raw
}

type McpServerNewParams struct {
	Name        param.Field[string]   `json:"name" api:"required"`
	ProjectUIDs param.Field[[]string] `json:"projectUids"`
	Slug        param.Field[string]   `json:"slug"`
	VersionUIDs param.Field[[]string] `json:"versionUids"`
}

func (r McpServerNewParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type McpServerUpdateParams struct {
	AutoAddOperations param.Field[bool]     `json:"autoAddOperations"`
	DocsPages         param.Field[[]string] `json:"docsPages"`
	Name              param.Field[string]   `json:"name"`
	Operations        param.Field[[]string] `json:"operations"`
	Slug              param.Field[string]   `json:"slug"`
}

func (r McpServerUpdateParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type McpServerNewResponse struct {
	Installation McpInstallation          `json:"installation" api:"required"`
	Server       McpServer                `json:"server" api:"required"`
	JSON         mcpServerNewResponseJSON `json:"-"`
}

// mcpServerNewResponseJSON contains the JSON metadata for the struct [McpServerNewResponse]
type mcpServerNewResponseJSON struct {
	Installation apijson.Field
	Server       apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *McpServerNewResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r mcpServerNewResponseJSON) RawJSON() string {
	return r.raw
}
