// Code generated by Scalar SDK Generator. DO NOT EDIT.

package scalarapi

import (
	"context"
	"net/http"
	"slices"

	"github.com/scalar/scalar-go/internal/requestconfig"
	"github.com/scalar/scalar-go/option"
)

// NamespaceService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewNamespaceService] method instead.
type NamespaceService struct {
	options []option.RequestOption
}

// NewNamespaceService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewNamespaceService(opts ...option.RequestOption) NamespaceService {
	s := NamespaceService{}
	s.options = opts
	return s
}

// Get all namespaces for the current team
func (r *NamespaceService) List(ctx context.Context, opts ...option.RequestOption) (res *[]string, err error) {
	opts = slices.Concat(r.options, opts)
	requestPath := "v1/namespaces"
	res = new([]string)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, requestPath, nil, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}
