// Code generated by Scalar SDK Generator. DO NOT EDIT.

package scalargo

import (
	"context"
	"net/http"
	"slices"

	"scalar-go/internal/requestconfig"
	"scalar-go/option"
)

// NamespaceService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewNamespaceService] method instead.
type NamespaceService struct {
	Options []option.RequestOption
}

// NewNamespaceService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewNamespaceService(opts ...option.RequestOption) (r *NamespaceService) {
	r = &NamespaceService{}
	r.Options = opts
	return
}

// Get all namespaces for the current team
//
// Parameters:
//     ctx: Context for the request.
//     opts: Options to apply to this request.
//
// Returns:
//     *[]string: Default Response
//
// Example:
//
//     namespace, err := client.Namespaces.List(context.Background())
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(namespace)
func (r *NamespaceService) List(ctx context.Context, opts ...option.RequestOption) (res *[]string, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/namespaces"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}
