// Code generated by Scalar SDK Generator. DO NOT EDIT.

package sdk

import (
	"context"
	"net/http"
	"reflect"
	"slices"

	"github.com/tidwall/gjson"

	"github.com/scalar/scalar-go/internal/apijson"
	"github.com/scalar/scalar-go/internal/param"
	"github.com/scalar/scalar-go/internal/requestconfig"
	"github.com/scalar/scalar-go/option"
)

// OAuthService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewOAuthService] method instead.
type OAuthService struct {
	Options []option.RequestOption
}

// NewOAuthService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewOAuthService(opts ...option.RequestOption) (r *OAuthService) {
	r = &OAuthService{}
	r.Options = opts
	return
}

// Authorization endpoint (RFC 6749 §4.1.1 with PKCE, RFC 7636). Validates the request and sends the user to the Scalar dashboard to approve it; the user returns to `redirect_uri` with a `code` to exchange at the token endpoint. Only `response_type=code` with `code_challenge_method=S256` is supported.
//
// Parameters:
//
//	ctx: Context for the request.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*map[string]interface{}: Default Response
//
// Example:
//
//	oAuth, err := client.OAuth.OauthAuthorize(context.Background())
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(oAuth)
func (r *OAuthService) OauthAuthorize(ctx context.Context, opts ...option.RequestOption) (res *map[string]interface{}, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/oauth/authorize"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Token endpoint (RFC 6749 §4.1.3 and §6). Accepts `application/x-www-form-urlencoded`. Confidential clients authenticate with HTTP Basic or `client_secret` in the body; public clients send `client_id` alone. The `authorization_code` grant needs `code`, `redirect_uri` and `code_verifier`; the `refresh_token` grant needs `refresh_token` and may narrow `scope`.
//
// Parameters:
//
//	ctx: Context for the request.
//	body: OAuthOauthTokenParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*OAuthOauthTokenResponse: Default Response
//
// Example:
//
//	oAuth, err := client.OAuth.OauthToken(context.Background(), sdk.OAuthOauthTokenParams{
//		GrantType: sdk.F[string](""),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(oAuth)
func (r *OAuthService) OauthToken(ctx context.Context, body OAuthOauthTokenParams, opts ...option.RequestOption) (res *OAuthOauthTokenResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/oauth/token"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Revocation endpoint (RFC 7009). Revokes the refresh token and every token issued alongside it. The client authenticates as it does at the token endpoint. Responds 200 whether or not the token was live, as the RFC requires.
//
// Parameters:
//
//	ctx: Context for the request.
//	body: OAuthOauthRevokeParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*OauthError: Default Response
//
// Example:
//
//	oAuth, err := client.OAuth.OauthRevoke(context.Background(), sdk.OAuthOauthRevokeParams{
//		Token: sdk.F[string](""),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(oAuth)
func (r *OAuthService) OauthRevoke(ctx context.Context, body OAuthOauthRevokeParams, opts ...option.RequestOption) (res *OauthError, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/oauth/revoke"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Discovery document for OAuth clients (RFC 8414): where the endpoints are and what they support.
//
// Parameters:
//
//	ctx: Context for the request.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*OauthAuthorizationServerMetadata: Default Response
//
// Example:
//
//	oAuth, err := client.OAuth.OauthAuthorizationServerMetadata(context.Background())
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(oAuth)
func (r *OAuthService) OauthAuthorizationServerMetadata(ctx context.Context, opts ...option.RequestOption) (res *OauthAuthorizationServerMetadata, err error) {
	opts = slices.Concat(r.Options, opts)
	path := ".well-known/oauth-authorization-server"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

type OauthToken struct {
	AccessToken  string              `json:"access_token" api:"required"`
	ExpiresIn    int64               `json:"expires_in" api:"required"`
	RefreshToken string              `json:"refresh_token" api:"required"`
	Scope        OauthScope          `json:"scope" api:"required"`
	TokenType    OauthTokenTokenType `json:"token_type" api:"required"`
	JSON         oauthTokenJSON      `json:"-"`
}

// oauthTokenJSON contains the JSON metadata for the struct [OauthToken]
type oauthTokenJSON struct {
	AccessToken  apijson.Field
	ExpiresIn    apijson.Field
	RefreshToken apijson.Field
	Scope        apijson.Field
	TokenType    apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *OauthToken) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r oauthTokenJSON) RawJSON() string {
	return r.raw
}

type OauthTokenTokenType string

const (
	OauthTokenTokenTypeBearer OauthTokenTokenType = "Bearer"
)

func (r OauthTokenTokenType) IsKnown() bool {
	switch r {
	case OauthTokenTokenTypeBearer:
		return true
	}
	return false
}

type OauthError struct {
	Error            string         `json:"error" api:"required"`
	ErrorDescription string         `json:"error_description"`
	JSON             oauthErrorJSON `json:"-"`
}

// oauthErrorJSON contains the JSON metadata for the struct [OauthError]
type oauthErrorJSON struct {
	Error            apijson.Field
	ErrorDescription apijson.Field
	raw              string
	ExtraFields      map[string]apijson.Field
}

func (r *OauthError) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r oauthErrorJSON) RawJSON() string {
	return r.raw
}

type OauthAuthorizationServerMetadata struct {
	AuthorizationEndpoint                  string                               `json:"authorization_endpoint" api:"required"`
	CodeChallengeMethodsSupported          []string                             `json:"code_challenge_methods_supported" api:"required"`
	GrantTypesSupported                    []string                             `json:"grant_types_supported" api:"required"`
	Issuer                                 string                               `json:"issuer" api:"required"`
	ResponseTypesSupported                 []string                             `json:"response_types_supported" api:"required"`
	RevocationEndpoint                     string                               `json:"revocation_endpoint" api:"required"`
	RevocationEndpointAuthMethodsSupported []string                             `json:"revocation_endpoint_auth_methods_supported" api:"required"`
	ScopesSupported                        []string                             `json:"scopes_supported" api:"required"`
	TokenEndpoint                          string                               `json:"token_endpoint" api:"required"`
	TokenEndpointAuthMethodsSupported      []string                             `json:"token_endpoint_auth_methods_supported" api:"required"`
	JSON                                   oauthAuthorizationServerMetadataJSON `json:"-"`
}

// oauthAuthorizationServerMetadataJSON contains the JSON metadata for the struct [OauthAuthorizationServerMetadata]
type oauthAuthorizationServerMetadataJSON struct {
	AuthorizationEndpoint                  apijson.Field
	CodeChallengeMethodsSupported          apijson.Field
	GrantTypesSupported                    apijson.Field
	Issuer                                 apijson.Field
	ResponseTypesSupported                 apijson.Field
	RevocationEndpoint                     apijson.Field
	RevocationEndpointAuthMethodsSupported apijson.Field
	ScopesSupported                        apijson.Field
	TokenEndpoint                          apijson.Field
	TokenEndpointAuthMethodsSupported      apijson.Field
	raw                                    string
	ExtraFields                            map[string]apijson.Field
}

func (r *OauthAuthorizationServerMetadata) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r oauthAuthorizationServerMetadataJSON) RawJSON() string {
	return r.raw
}

type OauthScope string

const (
	OauthScopeRead  OauthScope = "read"
	OauthScopeWrite OauthScope = "write"
	OauthScopeAdmin OauthScope = "admin"
)

func (r OauthScope) IsKnown() bool {
	switch r {
	case OauthScopeRead, OauthScopeWrite, OauthScopeAdmin:
		return true
	}
	return false
}

type OAuthOauthTokenParams struct {
	GrantType    param.Field[string] `json:"grant_type" api:"required"`
	ClientID     param.Field[string] `json:"client_id"`
	ClientSecret param.Field[string] `json:"client_secret"`
	Code         param.Field[string] `json:"code"`
	CodeVerifier param.Field[string] `json:"code_verifier"`
	RedirectURI  param.Field[string] `json:"redirect_uri"`
	RefreshToken param.Field[string] `json:"refresh_token"`
	Scope        param.Field[string] `json:"scope"`
}

func (r OAuthOauthTokenParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type OAuthOauthRevokeParams struct {
	Token         param.Field[string] `json:"token" api:"required"`
	ClientID      param.Field[string] `json:"client_id"`
	ClientSecret  param.Field[string] `json:"client_secret"`
	TokenTypeHint param.Field[string] `json:"token_type_hint"`
}

func (r OAuthOauthRevokeParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type OAuthOauthTokenResponse struct {
	AccessToken      string                           `json:"access_token"`
	Error            string                           `json:"error"`
	ErrorDescription string                           `json:"error_description"`
	ExpiresIn        int64                            `json:"expires_in"`
	RefreshToken     string                           `json:"refresh_token"`
	Scope            OauthScope                       `json:"scope"`
	TokenType        OAuthOauthTokenResponseTokenType `json:"token_type"`
	JSON             oAuthOauthTokenResponseJSON      `json:"-"`
	union            OAuthOauthTokenResponseUnion
}

// oAuthOauthTokenResponseJSON contains the JSON metadata for the struct [OAuthOauthTokenResponse]
type oAuthOauthTokenResponseJSON struct {
	AccessToken      apijson.Field
	Error            apijson.Field
	ErrorDescription apijson.Field
	ExpiresIn        apijson.Field
	RefreshToken     apijson.Field
	Scope            apijson.Field
	TokenType        apijson.Field
	raw              string
	ExtraFields      map[string]apijson.Field
}

func (r oAuthOauthTokenResponseJSON) RawJSON() string {
	return r.raw
}

func (r *OAuthOauthTokenResponse) UnmarshalJSON(data []byte) (err error) {
	*r = OAuthOauthTokenResponse{}
	err = apijson.UnmarshalRoot(data, &r.union)
	if err != nil {
		return err
	}
	return apijson.Port(r.union, &r)
}

func (r OAuthOauthTokenResponse) AsUnion() OAuthOauthTokenResponseUnion {
	return r.union
}

type OAuthOauthTokenResponseUnion interface {
	implementsOAuthOauthTokenResponse()
}

func init() {
	apijson.RegisterUnion(
		reflect.TypeOf((*OAuthOauthTokenResponseUnion)(nil)).Elem(),
		"type",
		apijson.UnionVariant{
			TypeFilter:         gjson.JSON,
			Type:               reflect.TypeOf(OauthToken{}),
			DiscriminatorValue: "",
		},
		apijson.UnionVariant{
			TypeFilter:         gjson.JSON,
			Type:               reflect.TypeOf(OauthError{}),
			DiscriminatorValue: "",
		},
	)
}

type OAuthOauthTokenResponseTokenType string

const (
	OAuthOauthTokenResponseTokenTypeBearer OAuthOauthTokenResponseTokenType = "Bearer"
)

func (r OAuthOauthTokenResponseTokenType) IsKnown() bool {
	switch r {
	case OAuthOauthTokenResponseTokenTypeBearer:
		return true
	}
	return false
}

func (r OauthToken) implementsOAuthOauthTokenResponse() {}

func (r OauthError) implementsOAuthOauthTokenResponse() {}
