// Code generated by Scalar SDK Generator. DO NOT EDIT.

package scalarapi

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"github.com/scalar/scalar-go/internal/apijson"
	shimjson "github.com/scalar/scalar-go/internal/encoding/json"
	"github.com/scalar/scalar-go/internal/requestconfig"
	"github.com/scalar/scalar-go/option"
	"github.com/scalar/scalar-go/packages/param"
	"github.com/scalar/scalar-go/packages/respjson"
)

// RegistryService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewRegistryService] method instead.
type RegistryService struct {
	options []option.RequestOption
}

// NewRegistryService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewRegistryService(opts ...option.RequestOption) RegistryService {
	s := RegistryService{}
	s.options = opts
	return s
}

// List all API documents across every namespace the caller can access.
func (r *RegistryService) ListAllAPIDocuments(ctx context.Context, opts ...option.RequestOption) (res *[]APIDocument, err error) {
	opts = slices.Concat(r.options, opts)
	requestPath := "v1/apis"
	res = new([]APIDocument)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, requestPath, nil, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

// List API documents in a namespace.
func (r *RegistryService) ListAPIDocuments(ctx context.Context, namespace string, opts ...option.RequestOption) (res *[]APIDocument, err error) {
	opts = slices.Concat(r.options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	requestPath := fmt.Sprintf("v1/apis/%s", url.PathEscape(namespace))
	res = new([]APIDocument)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, requestPath, nil, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

// Create an API document.
func (r *RegistryService) NewAPIDocument(ctx context.Context, namespace string, body RegistryNewAPIDocumentParams, opts ...option.RequestOption) (res *RegistryNewAPIDocumentResponse, err error) {
	opts = slices.Concat(r.options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	requestPath := fmt.Sprintf("v1/apis/%s", url.PathEscape(namespace))
	res = new(RegistryNewAPIDocumentResponse)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, requestPath, body, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type RegistryNewAPIDocumentParams struct {
	Document string `json:"document" api:"required"`
	Slug string `json:"slug" api:"required"`
	Title string `json:"title" api:"required"`
	Version string `json:"version" api:"required"`
	Description param.Opt[string] `json:"description,omitzero"`
	IsPrivate param.Opt[bool] `json:"isPrivate,omitzero"`
	Ruleset param.Opt[string] `json:"ruleset,omitzero"`
	paramObj
}

func (r RegistryNewAPIDocumentParams) MarshalJSON() (data []byte, err error) {
	type shadow RegistryNewAPIDocumentParams
	return param.MarshalObject(r, (*shadow)(&r))
}
func (r *RegistryNewAPIDocumentParams) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Update metadata for an API document.
func (r *RegistryService) UpdateAPIDocument(ctx context.Context, namespace string, slug string, body RegistryUpdateAPIDocumentParams, opts ...option.RequestOption) (res *map[string]any, err error) {
	opts = slices.Concat(r.options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	requestPath := fmt.Sprintf("v1/apis/%s/%s", url.PathEscape(namespace), url.PathEscape(slug))
	res = new(map[string]any)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPatch, requestPath, body, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type RegistryUpdateAPIDocumentParams struct {
	Description param.Opt[string] `json:"description,omitzero"`
	IsPrivate param.Opt[bool] `json:"isPrivate,omitzero"`
	Ruleset param.Opt[string] `json:"ruleset,omitzero"`
	Title param.Opt[string] `json:"title,omitzero"`
	paramObj
}

func (r RegistryUpdateAPIDocumentParams) MarshalJSON() (data []byte, err error) {
	type shadow RegistryUpdateAPIDocumentParams
	return param.MarshalObject(r, (*shadow)(&r))
}
func (r *RegistryUpdateAPIDocumentParams) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Delete an API document and all versions.
func (r *RegistryService) DeleteAPIDocument(ctx context.Context, namespace string, slug string, opts ...option.RequestOption) (res *map[string]any, err error) {
	opts = slices.Concat(r.options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	requestPath := fmt.Sprintf("v1/apis/%s/%s", url.PathEscape(namespace), url.PathEscape(slug))
	res = new(map[string]any)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, requestPath, nil, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

// Get a specific API document version.
func (r *RegistryService) GetAPIDocumentVersion(ctx context.Context, namespace string, slug string, semver string, opts ...option.RequestOption) (res *string, err error) {
	opts = slices.Concat(r.options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	if semver == "" {
		err = errors.New("missing required semver parameter")
		return nil, err
	}
	requestPath := fmt.Sprintf("v1/apis/%s/%s/version/%s", url.PathEscape(namespace), url.PathEscape(slug), url.PathEscape(semver))
	res = new(string)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, requestPath, nil, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

// Update the registry file content for an API document version.
func (r *RegistryService) UpdateAPIDocumentVersion(ctx context.Context, namespace string, slug string, semver string, body RegistryUpdateAPIDocumentVersionParams, opts ...option.RequestOption) (res *RegistryUpdateAPIDocumentVersionResponse, err error) {
	opts = slices.Concat(r.options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	if semver == "" {
		err = errors.New("missing required semver parameter")
		return nil, err
	}
	requestPath := fmt.Sprintf("v1/apis/%s/%s/version/%s", url.PathEscape(namespace), url.PathEscape(slug), url.PathEscape(semver))
	res = new(RegistryUpdateAPIDocumentVersionResponse)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPatch, requestPath, body, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type RegistryUpdateAPIDocumentVersionParams struct {
	Document string `json:"document" api:"required"`
	LastKnownVersionSha param.Opt[string] `json:"lastKnownVersionSha,omitzero"`
	paramObj
}

func (r RegistryUpdateAPIDocumentVersionParams) MarshalJSON() (data []byte, err error) {
	type shadow RegistryUpdateAPIDocumentVersionParams
	return param.MarshalObject(r, (*shadow)(&r))
}
func (r *RegistryUpdateAPIDocumentVersionParams) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Delete a specific API document version.
func (r *RegistryService) DeleteAPIDocumentVersion(ctx context.Context, namespace string, slug string, semver string, opts ...option.RequestOption) (res *map[string]any, err error) {
	opts = slices.Concat(r.options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	if semver == "" {
		err = errors.New("missing required semver parameter")
		return nil, err
	}
	requestPath := fmt.Sprintf("v1/apis/%s/%s/version/%s", url.PathEscape(namespace), url.PathEscape(slug), url.PathEscape(semver))
	res = new(map[string]any)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, requestPath, nil, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

// Get metadata (uid, content shas, version sha, tags) for a specific API document version.
func (r *RegistryService) ListAPIDocumentVersionMetadata(ctx context.Context, namespace string, slug string, semver string, opts ...option.RequestOption) (res *ManagedDocVersion, err error) {
	opts = slices.Concat(r.options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	if semver == "" {
		err = errors.New("missing required semver parameter")
		return nil, err
	}
	requestPath := fmt.Sprintf("v1/apis/%s/%s/version/%s/metadata", url.PathEscape(namespace), url.PathEscape(slug), url.PathEscape(semver))
	res = new(ManagedDocVersion)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, requestPath, nil, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

// Create a new API document version.
func (r *RegistryService) NewAPIDocumentVersion(ctx context.Context, namespace string, slug string, body RegistryNewAPIDocumentVersionParams, opts ...option.RequestOption) (res *ManagedDocVersion, err error) {
	opts = slices.Concat(r.options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	requestPath := fmt.Sprintf("v1/apis/%s/%s/version", url.PathEscape(namespace), url.PathEscape(slug))
	res = new(ManagedDocVersion)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, requestPath, body, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type RegistryNewAPIDocumentVersionParams struct {
	Document string `json:"document" api:"required"`
	Version string `json:"version" api:"required"`
	Force param.Opt[bool] `json:"force,omitzero"`
	LastKnownVersionSha param.Opt[string] `json:"lastKnownVersionSha,omitzero"`
	paramObj
}

func (r RegistryNewAPIDocumentVersionParams) MarshalJSON() (data []byte, err error) {
	type shadow RegistryNewAPIDocumentVersionParams
	return param.MarshalObject(r, (*shadow)(&r))
}
func (r *RegistryNewAPIDocumentVersionParams) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Add an access group to an API document.
func (r *RegistryService) NewAPIDocumentAccessGroup(ctx context.Context, namespace string, slug string, body RegistryNewAPIDocumentAccessGroupParams, opts ...option.RequestOption) (res *map[string]any, err error) {
	opts = slices.Concat(r.options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	requestPath := fmt.Sprintf("v1/apis/%s/%s/access-group", url.PathEscape(namespace), url.PathEscape(slug))
	res = new(map[string]any)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, requestPath, body, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type RegistryNewAPIDocumentAccessGroupParams struct {
	AccessGroup AccessGroup
	paramObj
}

func (r RegistryNewAPIDocumentAccessGroupParams) MarshalJSON() (data []byte, err error) {
	return shimjson.Marshal(r.AccessGroup)
}
func (r *RegistryNewAPIDocumentAccessGroupParams) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Remove an access group from an API document.
func (r *RegistryService) DeleteAPIDocumentAccessGroup(ctx context.Context, namespace string, slug string, body RegistryDeleteAPIDocumentAccessGroupParams, opts ...option.RequestOption) (res *map[string]any, err error) {
	opts = slices.Concat(r.options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	requestPath := fmt.Sprintf("v1/apis/%s/%s/access-group", url.PathEscape(namespace), url.PathEscape(slug))
	res = new(map[string]any)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, requestPath, body, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type RegistryDeleteAPIDocumentAccessGroupParams struct {
	AccessGroup AccessGroup
	paramObj
}

func (r RegistryDeleteAPIDocumentAccessGroupParams) MarshalJSON() (data []byte, err error) {
	return shimjson.Marshal(r.AccessGroup)
}
func (r *RegistryDeleteAPIDocumentAccessGroupParams) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type RegistryNewAPIDocumentResponse struct {
	JSONSha string `json:"jsonSha" api:"required"`
	Title string `json:"title" api:"required"`
	UID string `json:"uid" api:"required"`
	VersionSha string `json:"versionSha" api:"required"`
	VersionUID string `json:"versionUid" api:"required"`
	YamlSha string `json:"yamlSha" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		JSONSha respjson.Field
		Title respjson.Field
		UID respjson.Field
		VersionSha respjson.Field
		VersionUID respjson.Field
		YamlSha respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// RawJSON returns the unmodified JSON received from the API.
func (r RegistryNewAPIDocumentResponse) RawJSON() string { return r.JSON.raw }
func (r *RegistryNewAPIDocumentResponse) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type RegistryUpdateAPIDocumentVersionResponse struct {
	JSONSha string `json:"jsonSha" api:"required"`
	VersionSha string `json:"versionSha" api:"required"`
	YamlSha string `json:"yamlSha" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		JSONSha respjson.Field
		VersionSha respjson.Field
		YamlSha respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// RawJSON returns the unmodified JSON received from the API.
func (r RegistryUpdateAPIDocumentVersionResponse) RawJSON() string { return r.JSON.raw }
func (r *RegistryUpdateAPIDocumentVersionResponse) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type AccessGroup struct {
	AccessGroupSlug string `json:"accessGroupSlug" api:"required"`
	paramObj
}

func (r AccessGroup) MarshalJSON() (data []byte, err error) {
	type shadow AccessGroup
	return param.MarshalObject(r, (*shadow)(&r))
}
func (r *AccessGroup) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}
