// Code generated by Scalar SDK Generator. DO NOT EDIT.

package scalarapi

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"slices"

	"scalar-api/internal/apijson"
	"scalar-api/internal/param"
	"scalar-api/internal/requestconfig"
	"scalar-api/option"
)

// RegistryService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewRegistryService] method instead.
type RegistryService struct {
	Options []option.RequestOption
}

// NewRegistryService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewRegistryService(opts ...option.RequestOption) (r *RegistryService) {
	r = &RegistryService{}
	r.Options = opts
	return
}

// List all API documents across every namespace the caller can access.
//
// Parameters:
//     ctx: Context for the request.
//     opts: Options to apply to this request.
//
// Returns:
//     *[]APIDocument: Default Response
//
// Example:
//
//     registry, err := client.Registry.ListAllAPIDocuments(context.Background())
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(registry)
func (r *RegistryService) ListAllAPIDocuments(ctx context.Context, opts ...option.RequestOption) (res *[]APIDocument, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/apis"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// List API documents in a namespace.
//
// Parameters:
//     ctx: Context for the request.
//     namespace: Path parameter.
//     opts: Options to apply to this request.
//
// Returns:
//     *[]APIDocument: Default Response
//
// Example:
//
//     registry, err := client.Registry.ListAPIDocuments(context.Background(), "namespace")
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(registry)
func (r *RegistryService) ListAPIDocuments(ctx context.Context, namespace string, opts ...option.RequestOption) (res *[]APIDocument, err error) {
	opts = slices.Concat(r.Options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/apis/%s", namespace)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Create an API document.
//
// Parameters:
//     ctx: Context for the request.
//     namespace: Path parameter.
//     body: RegistryNewAPIDocumentParams request parameters.
//     opts: Options to apply to this request.
//
// Returns:
//     *RegistryNewAPIDocumentResponse: Default Response
//
// Example:
//
//     registry, err := client.Registry.NewAPIDocument(context.Background(), "namespace", sdk.RegistryNewAPIDocumentParams{
//     	Document: sdk.F[string](""),
//     	Slug: sdk.F[string](""),
//     	Title: sdk.F[string](""),
//     	Version: sdk.F[string]("x"),
//     })
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(registry)
func (r *RegistryService) NewAPIDocument(ctx context.Context, namespace string, body RegistryNewAPIDocumentParams, opts ...option.RequestOption) (res *RegistryNewAPIDocumentResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/apis/%s", namespace)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Update metadata for an API document.
//
// Parameters:
//     ctx: Context for the request.
//     namespace: Path parameter.
//     slug: Path parameter.
//     body: RegistryUpdateAPIDocumentParams request parameters.
//     opts: Options to apply to this request.
//
// Returns:
//     *map[string]any: Default Response
//
// Example:
//
//     registry, err := client.Registry.UpdateAPIDocument(context.Background(), "namespace", "slug", sdk.RegistryUpdateAPIDocumentParams{})
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(registry)
func (r *RegistryService) UpdateAPIDocument(ctx context.Context, namespace string, slug string, body RegistryUpdateAPIDocumentParams, opts ...option.RequestOption) (res *map[string]any, err error) {
	opts = slices.Concat(r.Options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/apis/%s/%s", namespace, slug)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPatch, path, body, &res, opts...)
	return res, err
}

// Delete an API document and all versions.
//
// Parameters:
//     ctx: Context for the request.
//     namespace: Path parameter.
//     slug: Path parameter.
//     opts: Options to apply to this request.
//
// Returns:
//     *map[string]any: Default Response
//
// Example:
//
//     registry, err := client.Registry.DeleteAPIDocument(context.Background(), "namespace", "slug")
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(registry)
func (r *RegistryService) DeleteAPIDocument(ctx context.Context, namespace string, slug string, opts ...option.RequestOption) (res *map[string]any, err error) {
	opts = slices.Concat(r.Options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/apis/%s/%s", namespace, slug)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, nil, &res, opts...)
	return res, err
}

// Get a specific API document version.
//
// Parameters:
//     ctx: Context for the request.
//     namespace: Path parameter.
//     slug: Path parameter.
//     semver: Path parameter.
//     opts: Options to apply to this request.
//
// Returns:
//     *string: Default Response
//
// Example:
//
//     registry, err := client.Registry.GetAPIDocumentVersion(context.Background(), "namespace", "slug", "semver")
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(registry)
func (r *RegistryService) GetAPIDocumentVersion(ctx context.Context, namespace string, slug string, semver string, opts ...option.RequestOption) (res *string, err error) {
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "text/plain")}, opts...)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	if semver == "" {
		err = errors.New("missing required semver parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/apis/%s/%s/version/%s", namespace, slug, semver)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Update the registry file content for an API document version.
//
// Parameters:
//     ctx: Context for the request.
//     namespace: Path parameter.
//     slug: Path parameter.
//     semver: Path parameter.
//     body: RegistryUpdateAPIDocumentVersionParams request parameters.
//     opts: Options to apply to this request.
//
// Returns:
//     *RegistryUpdateAPIDocumentVersionResponse: Default Response
//
// Example:
//
//     registry, err := client.Registry.UpdateAPIDocumentVersion(context.Background(), "namespace", "slug", "semver", sdk.RegistryUpdateAPIDocumentVersionParams{
//     	Document: sdk.F[string](""),
//     })
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(registry)
func (r *RegistryService) UpdateAPIDocumentVersion(ctx context.Context, namespace string, slug string, semver string, body RegistryUpdateAPIDocumentVersionParams, opts ...option.RequestOption) (res *RegistryUpdateAPIDocumentVersionResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	if semver == "" {
		err = errors.New("missing required semver parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/apis/%s/%s/version/%s", namespace, slug, semver)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPatch, path, body, &res, opts...)
	return res, err
}

// Delete a specific API document version.
//
// Parameters:
//     ctx: Context for the request.
//     namespace: Path parameter.
//     slug: Path parameter.
//     semver: Path parameter.
//     opts: Options to apply to this request.
//
// Returns:
//     *map[string]any: Default Response
//
// Example:
//
//     registry, err := client.Registry.DeleteAPIDocumentVersion(context.Background(), "namespace", "slug", "semver")
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(registry)
func (r *RegistryService) DeleteAPIDocumentVersion(ctx context.Context, namespace string, slug string, semver string, opts ...option.RequestOption) (res *map[string]any, err error) {
	opts = slices.Concat(r.Options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	if semver == "" {
		err = errors.New("missing required semver parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/apis/%s/%s/version/%s", namespace, slug, semver)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, nil, &res, opts...)
	return res, err
}

// Get metadata (uid, content shas, version sha, tags) for a specific API document version.
//
// Parameters:
//     ctx: Context for the request.
//     namespace: Path parameter.
//     slug: Path parameter.
//     semver: Path parameter.
//     opts: Options to apply to this request.
//
// Returns:
//     *RegistryListAPIDocumentVersionMetadataResponse: Default Response
//
// Example:
//
//     registry, err := client.Registry.ListAPIDocumentVersionMetadata(context.Background(), "namespace", "slug", "semver")
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(registry)
func (r *RegistryService) ListAPIDocumentVersionMetadata(ctx context.Context, namespace string, slug string, semver string, opts ...option.RequestOption) (res *RegistryListAPIDocumentVersionMetadataResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	if semver == "" {
		err = errors.New("missing required semver parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/apis/%s/%s/version/%s/metadata", namespace, slug, semver)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Create a new API document version.
//
// Parameters:
//     ctx: Context for the request.
//     namespace: Path parameter.
//     slug: Path parameter.
//     body: RegistryNewAPIDocumentVersionParams request parameters.
//     opts: Options to apply to this request.
//
// Returns:
//     *RegistryNewAPIDocumentVersionResponse: Default Response
//
// Example:
//
//     registry, err := client.Registry.NewAPIDocumentVersion(context.Background(), "namespace", "slug", sdk.RegistryNewAPIDocumentVersionParams{
//     	Document: sdk.F[string](""),
//     	Version: sdk.F[string]("x"),
//     })
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(registry)
func (r *RegistryService) NewAPIDocumentVersion(ctx context.Context, namespace string, slug string, body RegistryNewAPIDocumentVersionParams, opts ...option.RequestOption) (res *RegistryNewAPIDocumentVersionResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/apis/%s/%s/version", namespace, slug)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Add an access group to an API document.
//
// Parameters:
//     ctx: Context for the request.
//     namespace: Path parameter.
//     slug: Path parameter.
//     body: RegistryNewAPIDocumentAccessGroupParams request parameters.
//     opts: Options to apply to this request.
//
// Returns:
//     *map[string]any: Default Response
//
// Example:
//
//     registry, err := client.Registry.NewAPIDocumentAccessGroup(context.Background(), "namespace", "slug", sdk.RegistryNewAPIDocumentAccessGroupParams{
//     	AccessGroup: sdk.AccessGroup{
//     	AccessGroupSlug: sdk.F[string]("xxx"),
//     },
//     })
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(registry)
func (r *RegistryService) NewAPIDocumentAccessGroup(ctx context.Context, namespace string, slug string, body RegistryNewAPIDocumentAccessGroupParams, opts ...option.RequestOption) (res *map[string]any, err error) {
	opts = slices.Concat(r.Options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/apis/%s/%s/access-group", namespace, slug)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Remove an access group from an API document.
//
// Parameters:
//     ctx: Context for the request.
//     namespace: Path parameter.
//     slug: Path parameter.
//     body: RegistryDeleteAPIDocumentAccessGroupParams request parameters.
//     opts: Options to apply to this request.
//
// Returns:
//     *map[string]any: Default Response
//
// Example:
//
//     registry, err := client.Registry.DeleteAPIDocumentAccessGroup(context.Background(), "namespace", "slug", sdk.RegistryDeleteAPIDocumentAccessGroupParams{
//     	AccessGroup: sdk.AccessGroup{
//     	AccessGroupSlug: sdk.F[string]("xxx"),
//     },
//     })
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(registry)
func (r *RegistryService) DeleteAPIDocumentAccessGroup(ctx context.Context, namespace string, slug string, body RegistryDeleteAPIDocumentAccessGroupParams, opts ...option.RequestOption) (res *map[string]any, err error) {
	opts = slices.Concat(r.Options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/apis/%s/%s/access-group", namespace, slug)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, body, &res, opts...)
	return res, err
}

type AccessGroup struct {
	AccessGroupSlug param.Field[string] `json:"accessGroupSlug" api:"required"`
}

func (r AccessGroup) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type AccessGroupParam struct {
	AccessGroupSlug param.Field[string] `json:"accessGroupSlug" api:"required"`
}

func (r AccessGroupParam) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type APIDocument struct {
	UID string `json:"uid" api:"required"`
	Version string `json:"version" api:"required"`
	Title string `json:"title" api:"required"`
	Slug string `json:"slug" api:"required"`
	Description string `json:"description" api:"required"`
	Namespace string `json:"namespace" api:"required"`
	IsPrivate bool `json:"isPrivate" api:"required"`
	Tags any `json:"tags" api:"required"`
	Versions []ManagedDocVersion `json:"versions" api:"required"`
	JSON apiDocumentJSON `json:"-"`
}

// apiDocumentJSON contains the JSON metadata for the struct [APIDocument]
type apiDocumentJSON struct {
	UID apijson.Field
	Version apijson.Field
	Title apijson.Field
	Slug apijson.Field
	Description apijson.Field
	Namespace apijson.Field
	IsPrivate apijson.Field
	Tags apijson.Field
	Versions apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *APIDocument) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r apiDocumentJSON) RawJSON() string {
	return r.raw
}

type ManagedDocVersion struct {
	UID string `json:"uid" api:"required"`
	CreatedAt float64 `json:"createdAt" api:"required"`
	Version string `json:"version" api:"required"`
	Upgraded bool `json:"upgraded" api:"required"`
	// Any of "complete", "failed".
	EmbedStatus ManagedDocVersionEmbedStatus `json:"embedStatus" api:"required,nullable"`
	Tags []string `json:"tags" api:"required"`
	Tools []ManagedDocVersionTool `json:"tools"`
	YamlSha string `json:"yamlSha"`
	JSONSha string `json:"jsonSha"`
	VersionSha string `json:"versionSha"`
	JSON managedDocVersionJSON `json:"-"`
}

// managedDocVersionJSON contains the JSON metadata for the struct [ManagedDocVersion]
type managedDocVersionJSON struct {
	UID apijson.Field
	CreatedAt apijson.Field
	Version apijson.Field
	Upgraded apijson.Field
	EmbedStatus apijson.Field
	Tags apijson.Field
	Tools apijson.Field
	YamlSha apijson.Field
	JSONSha apijson.Field
	VersionSha apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *ManagedDocVersion) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r managedDocVersionJSON) RawJSON() string {
	return r.raw
}

type ManagedDocVersionEmbedStatus string

const (
	ManagedDocVersionEmbedStatusComplete ManagedDocVersionEmbedStatus = "complete"
	ManagedDocVersionEmbedStatusFailed ManagedDocVersionEmbedStatus = "failed"
)

func (r ManagedDocVersionEmbedStatus) IsKnown() bool {
	switch r {
	case ManagedDocVersionEmbedStatusComplete, ManagedDocVersionEmbedStatusFailed:
		return true
	}
	return false
}

type RegistryListAllAPIDocumentsResponse struct {
	Message string `json:"message" api:"required"`
	Code string `json:"code" api:"required"`
	JSON registryListAllAPIDocumentsResponseJSON `json:"-"`
}

// registryListAllAPIDocumentsResponseJSON contains the JSON metadata for the struct [RegistryListAllAPIDocumentsResponse]
type registryListAllAPIDocumentsResponseJSON struct {
	Message apijson.Field
	Code apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *RegistryListAllAPIDocumentsResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r registryListAllAPIDocumentsResponseJSON) RawJSON() string {
	return r.raw
}

type RegistryListAPIDocumentsResponse struct {
	Message string `json:"message" api:"required"`
	Code string `json:"code" api:"required"`
	JSON registryListAPIDocumentsResponseJSON `json:"-"`
}

// registryListAPIDocumentsResponseJSON contains the JSON metadata for the struct [RegistryListAPIDocumentsResponse]
type registryListAPIDocumentsResponseJSON struct {
	Message apijson.Field
	Code apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *RegistryListAPIDocumentsResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r registryListAPIDocumentsResponseJSON) RawJSON() string {
	return r.raw
}

type RegistryNewAPIDocumentResponse struct {
	Message string `json:"message" api:"required"`
	Code string `json:"code" api:"required"`
	JSON registryNewAPIDocumentResponseJSON `json:"-"`
}

// registryNewAPIDocumentResponseJSON contains the JSON metadata for the struct [RegistryNewAPIDocumentResponse]
type registryNewAPIDocumentResponseJSON struct {
	Message apijson.Field
	Code apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *RegistryNewAPIDocumentResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r registryNewAPIDocumentResponseJSON) RawJSON() string {
	return r.raw
}

type RegistryUpdateAPIDocumentResponse struct {
	Message string `json:"message" api:"required"`
	Code string `json:"code" api:"required"`
	JSON registryUpdateAPIDocumentResponseJSON `json:"-"`
}

// registryUpdateAPIDocumentResponseJSON contains the JSON metadata for the struct [RegistryUpdateAPIDocumentResponse]
type registryUpdateAPIDocumentResponseJSON struct {
	Message apijson.Field
	Code apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *RegistryUpdateAPIDocumentResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r registryUpdateAPIDocumentResponseJSON) RawJSON() string {
	return r.raw
}

type RegistryDeleteAPIDocumentResponse struct {
	Message string `json:"message" api:"required"`
	Code string `json:"code" api:"required"`
	JSON registryDeleteAPIDocumentResponseJSON `json:"-"`
}

// registryDeleteAPIDocumentResponseJSON contains the JSON metadata for the struct [RegistryDeleteAPIDocumentResponse]
type registryDeleteAPIDocumentResponseJSON struct {
	Message apijson.Field
	Code apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *RegistryDeleteAPIDocumentResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r registryDeleteAPIDocumentResponseJSON) RawJSON() string {
	return r.raw
}

type RegistryGetAPIDocumentVersionResponse struct {
	Message string `json:"message" api:"required"`
	Code string `json:"code" api:"required"`
	JSON registryGetAPIDocumentVersionResponseJSON `json:"-"`
}

// registryGetAPIDocumentVersionResponseJSON contains the JSON metadata for the struct [RegistryGetAPIDocumentVersionResponse]
type registryGetAPIDocumentVersionResponseJSON struct {
	Message apijson.Field
	Code apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *RegistryGetAPIDocumentVersionResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r registryGetAPIDocumentVersionResponseJSON) RawJSON() string {
	return r.raw
}

type RegistryUpdateAPIDocumentVersionResponse struct {
	Message string `json:"message" api:"required"`
	Code string `json:"code" api:"required"`
	JSON registryUpdateAPIDocumentVersionResponseJSON `json:"-"`
}

// registryUpdateAPIDocumentVersionResponseJSON contains the JSON metadata for the struct [RegistryUpdateAPIDocumentVersionResponse]
type registryUpdateAPIDocumentVersionResponseJSON struct {
	Message apijson.Field
	Code apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *RegistryUpdateAPIDocumentVersionResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r registryUpdateAPIDocumentVersionResponseJSON) RawJSON() string {
	return r.raw
}

type RegistryDeleteAPIDocumentVersionResponse struct {
	Message string `json:"message" api:"required"`
	Code string `json:"code" api:"required"`
	JSON registryDeleteAPIDocumentVersionResponseJSON `json:"-"`
}

// registryDeleteAPIDocumentVersionResponseJSON contains the JSON metadata for the struct [RegistryDeleteAPIDocumentVersionResponse]
type registryDeleteAPIDocumentVersionResponseJSON struct {
	Message apijson.Field
	Code apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *RegistryDeleteAPIDocumentVersionResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r registryDeleteAPIDocumentVersionResponseJSON) RawJSON() string {
	return r.raw
}

type RegistryListAPIDocumentVersionMetadataResponse struct {
	UID string `json:"uid" api:"required"`
	CreatedAt float64 `json:"createdAt" api:"required"`
	Version string `json:"version" api:"required"`
	Upgraded bool `json:"upgraded" api:"required"`
	// Any of "complete", "failed".
	EmbedStatus RegistryListAPIDocumentVersionMetadataResponseEmbedStatus `json:"embedStatus" api:"required,nullable"`
	Tags []string `json:"tags" api:"required"`
	Tools []ManagedDocVersionTool `json:"tools"`
	YamlSha string `json:"yamlSha"`
	JSONSha string `json:"jsonSha"`
	VersionSha string `json:"versionSha"`
	JSON registryListAPIDocumentVersionMetadataResponseJSON `json:"-"`
}

// registryListAPIDocumentVersionMetadataResponseJSON contains the JSON metadata for the struct [RegistryListAPIDocumentVersionMetadataResponse]
type registryListAPIDocumentVersionMetadataResponseJSON struct {
	UID apijson.Field
	CreatedAt apijson.Field
	Version apijson.Field
	Upgraded apijson.Field
	EmbedStatus apijson.Field
	Tags apijson.Field
	Tools apijson.Field
	YamlSha apijson.Field
	JSONSha apijson.Field
	VersionSha apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *RegistryListAPIDocumentVersionMetadataResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r registryListAPIDocumentVersionMetadataResponseJSON) RawJSON() string {
	return r.raw
}

type RegistryListAPIDocumentVersionMetadataResponseEmbedStatus string

const (
	RegistryListAPIDocumentVersionMetadataResponseEmbedStatusComplete RegistryListAPIDocumentVersionMetadataResponseEmbedStatus = "complete"
	RegistryListAPIDocumentVersionMetadataResponseEmbedStatusFailed RegistryListAPIDocumentVersionMetadataResponseEmbedStatus = "failed"
)

func (r RegistryListAPIDocumentVersionMetadataResponseEmbedStatus) IsKnown() bool {
	switch r {
	case RegistryListAPIDocumentVersionMetadataResponseEmbedStatusComplete, RegistryListAPIDocumentVersionMetadataResponseEmbedStatusFailed:
		return true
	}
	return false
}

type RegistryNewAPIDocumentVersionResponse struct {
	UID string `json:"uid" api:"required"`
	CreatedAt float64 `json:"createdAt" api:"required"`
	Version string `json:"version" api:"required"`
	Upgraded bool `json:"upgraded" api:"required"`
	// Any of "complete", "failed".
	EmbedStatus RegistryNewAPIDocumentVersionResponseEmbedStatus `json:"embedStatus" api:"required,nullable"`
	Tags []string `json:"tags" api:"required"`
	Tools []ManagedDocVersionTool `json:"tools"`
	YamlSha string `json:"yamlSha"`
	JSONSha string `json:"jsonSha"`
	VersionSha string `json:"versionSha"`
	JSON registryNewAPIDocumentVersionResponseJSON `json:"-"`
}

// registryNewAPIDocumentVersionResponseJSON contains the JSON metadata for the struct [RegistryNewAPIDocumentVersionResponse]
type registryNewAPIDocumentVersionResponseJSON struct {
	UID apijson.Field
	CreatedAt apijson.Field
	Version apijson.Field
	Upgraded apijson.Field
	EmbedStatus apijson.Field
	Tags apijson.Field
	Tools apijson.Field
	YamlSha apijson.Field
	JSONSha apijson.Field
	VersionSha apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *RegistryNewAPIDocumentVersionResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r registryNewAPIDocumentVersionResponseJSON) RawJSON() string {
	return r.raw
}

type RegistryNewAPIDocumentVersionResponseEmbedStatus string

const (
	RegistryNewAPIDocumentVersionResponseEmbedStatusComplete RegistryNewAPIDocumentVersionResponseEmbedStatus = "complete"
	RegistryNewAPIDocumentVersionResponseEmbedStatusFailed RegistryNewAPIDocumentVersionResponseEmbedStatus = "failed"
)

func (r RegistryNewAPIDocumentVersionResponseEmbedStatus) IsKnown() bool {
	switch r {
	case RegistryNewAPIDocumentVersionResponseEmbedStatusComplete, RegistryNewAPIDocumentVersionResponseEmbedStatusFailed:
		return true
	}
	return false
}

type RegistryNewAPIDocumentAccessGroupResponse struct {
	Message string `json:"message" api:"required"`
	Code string `json:"code" api:"required"`
	JSON registryNewAPIDocumentAccessGroupResponseJSON `json:"-"`
}

// registryNewAPIDocumentAccessGroupResponseJSON contains the JSON metadata for the struct [RegistryNewAPIDocumentAccessGroupResponse]
type registryNewAPIDocumentAccessGroupResponseJSON struct {
	Message apijson.Field
	Code apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *RegistryNewAPIDocumentAccessGroupResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r registryNewAPIDocumentAccessGroupResponseJSON) RawJSON() string {
	return r.raw
}

type RegistryDeleteAPIDocumentAccessGroupResponse struct {
	Message string `json:"message" api:"required"`
	Code string `json:"code" api:"required"`
	JSON registryDeleteAPIDocumentAccessGroupResponseJSON `json:"-"`
}

// registryDeleteAPIDocumentAccessGroupResponseJSON contains the JSON metadata for the struct [RegistryDeleteAPIDocumentAccessGroupResponse]
type registryDeleteAPIDocumentAccessGroupResponseJSON struct {
	Message apijson.Field
	Code apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *RegistryDeleteAPIDocumentAccessGroupResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r registryDeleteAPIDocumentAccessGroupResponseJSON) RawJSON() string {
	return r.raw
}

type RegistryNewAPIDocumentParams struct {
	Document param.Field[string] `json:"document" api:"required"`
	Slug param.Field[string] `json:"slug" api:"required"`
	Title param.Field[string] `json:"title" api:"required"`
	Version param.Field[string] `json:"version" api:"required"`
	Description param.Field[string] `json:"description"`
	IsPrivate param.Field[bool] `json:"isPrivate"`
	Ruleset param.Field[string] `json:"ruleset"`
}

func (r RegistryNewAPIDocumentParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type RegistryUpdateAPIDocumentParams struct {
	Description param.Field[string] `json:"description"`
	IsPrivate param.Field[bool] `json:"isPrivate"`
	Ruleset param.Field[string] `json:"ruleset"`
	Title param.Field[string] `json:"title"`
}

func (r RegistryUpdateAPIDocumentParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type RegistryUpdateAPIDocumentVersionParams struct {
	Document param.Field[string] `json:"document" api:"required"`
	LastKnownVersionSha param.Field[string] `json:"lastKnownVersionSha"`
}

func (r RegistryUpdateAPIDocumentVersionParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type RegistryNewAPIDocumentVersionParams struct {
	Document param.Field[string] `json:"document" api:"required"`
	Version param.Field[string] `json:"version" api:"required"`
	Force param.Field[bool] `json:"force"`
	LastKnownVersionSha param.Field[string] `json:"lastKnownVersionSha"`
}

func (r RegistryNewAPIDocumentVersionParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type RegistryNewAPIDocumentAccessGroupParams struct {
	AccessGroup AccessGroup `json:"accessgroup" api:"required"`
}

func (r RegistryNewAPIDocumentAccessGroupParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r.AccessGroup)
}

type RegistryDeleteAPIDocumentAccessGroupParams struct {
	AccessGroup AccessGroup `json:"accessgroup" api:"required"`
}

func (r RegistryDeleteAPIDocumentAccessGroupParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r.AccessGroup)
}

type ManagedDocVersionTool struct {
	Path string `json:"path" api:"required"`
	// Any of "delete", "get", "head", "options", "patch", "post", "put", "trace".
	Method ManagedDocVersionToolMethod `json:"method" api:"required"`
	// Any of "execute-request", "get-mini-openapi-spec".
	EnabledTools []string `json:"enabledTools" api:"required"`
	JSON managedDocVersionToolJSON `json:"-"`
}

// managedDocVersionToolJSON contains the JSON metadata for the struct [ManagedDocVersionTool]
type managedDocVersionToolJSON struct {
	Path apijson.Field
	Method apijson.Field
	EnabledTools apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *ManagedDocVersionTool) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r managedDocVersionToolJSON) RawJSON() string {
	return r.raw
}

type ManagedDocVersionToolMethod string

const (
	ManagedDocVersionToolMethodDelete ManagedDocVersionToolMethod = "delete"
	ManagedDocVersionToolMethodGet ManagedDocVersionToolMethod = "get"
	ManagedDocVersionToolMethodHead ManagedDocVersionToolMethod = "head"
	ManagedDocVersionToolMethodOptions ManagedDocVersionToolMethod = "options"
	ManagedDocVersionToolMethodPatch ManagedDocVersionToolMethod = "patch"
	ManagedDocVersionToolMethodPost ManagedDocVersionToolMethod = "post"
	ManagedDocVersionToolMethodPut ManagedDocVersionToolMethod = "put"
	ManagedDocVersionToolMethodTrace ManagedDocVersionToolMethod = "trace"
)

func (r ManagedDocVersionToolMethod) IsKnown() bool {
	switch r {
	case ManagedDocVersionToolMethodDelete, ManagedDocVersionToolMethodGet, ManagedDocVersionToolMethodHead, ManagedDocVersionToolMethodOptions, ManagedDocVersionToolMethodPatch, ManagedDocVersionToolMethodPost, ManagedDocVersionToolMethodPut, ManagedDocVersionToolMethodTrace:
		return true
	}
	return false
}
