// Code generated by Scalar SDK Generator. DO NOT EDIT.

package scalargo

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"slices"

	"github.com/scalar/scalar-go/internal/apijson"
	"github.com/scalar/scalar-go/internal/param"
	"github.com/scalar/scalar-go/internal/requestconfig"
	"github.com/scalar/scalar-go/option"
)

// RuleService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewRuleService] method instead.
type RuleService struct {
	Options []option.RequestOption
}

// NewRuleService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewRuleService(opts ...option.RequestOption) (r *RuleService) {
	r = &RuleService{}
	r.Options = opts
	return
}

// List all rulesets in a namespace.
//
// Parameters:
//     ctx: Context for the request.
//     namespace: Path parameter.
//     opts: Options to apply to this request.
//
// Returns:
//     *[]Rule: Default Response
//
// Example:
//
//     rule, err := client.Rules.ListRulesets(context.Background(), "namespace")
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(rule)
func (r *RuleService) ListRulesets(ctx context.Context, namespace string, opts ...option.RequestOption) (res *[]Rule, err error) {
	opts = slices.Concat(r.Options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/rulesets/%s", namespace)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Create a rule in a namespace.
//
// Parameters:
//     ctx: Context for the request.
//     namespace: Path parameter.
//     body: RuleNewRulesetParams request parameters.
//     opts: Options to apply to this request.
//
// Returns:
//     *RuleNewRulesetResponse: Default Response
//
// Example:
//
//     rule, err := client.Rules.NewRuleset(context.Background(), "namespace", sdk.RuleNewRulesetParams{
//     	Document: sdk.F[string](""),
//     	Slug: sdk.F[string](""),
//     	Title: sdk.F[string](""),
//     })
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(rule)
func (r *RuleService) NewRuleset(ctx context.Context, namespace string, body RuleNewRulesetParams, opts ...option.RequestOption) (res *RuleNewRulesetResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/rulesets/%s", namespace)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Update rule metadata by slug.
//
// Parameters:
//     ctx: Context for the request.
//     namespace: Path parameter.
//     slug: Path parameter.
//     body: RuleUpdateRulesetParams request parameters.
//     opts: Options to apply to this request.
//
// Returns:
//     *map[string]interface{}: Default Response
//
// Example:
//
//     rule, err := client.Rules.UpdateRuleset(context.Background(), "namespace", "slug", sdk.RuleUpdateRulesetParams{})
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(rule)
func (r *RuleService) UpdateRuleset(ctx context.Context, namespace string, slug string, body RuleUpdateRulesetParams, opts ...option.RequestOption) (res *map[string]interface{}, err error) {
	opts = slices.Concat(r.Options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/rulesets/%s/%s", namespace, slug)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPatch, path, body, &res, opts...)
	return res, err
}

// Delete a rule by slug.
//
// Parameters:
//     ctx: Context for the request.
//     namespace: Path parameter.
//     slug: Path parameter.
//     opts: Options to apply to this request.
//
// Returns:
//     *map[string]interface{}: Default Response
//
// Example:
//
//     rule, err := client.Rules.DeleteRuleset(context.Background(), "namespace", "slug")
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(rule)
func (r *RuleService) DeleteRuleset(ctx context.Context, namespace string, slug string, opts ...option.RequestOption) (res *map[string]interface{}, err error) {
	opts = slices.Concat(r.Options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/rulesets/%s/%s", namespace, slug)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, nil, &res, opts...)
	return res, err
}

// Get a rule document by slug.
//
// Parameters:
//     ctx: Context for the request.
//     namespace: Path parameter.
//     slug: Path parameter.
//     opts: Options to apply to this request.
//
// Returns:
//     *string: Default Response
//
// Example:
//
//     rule, err := client.Rules.GetRulesetDocument(context.Background(), "namespace", "slug")
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(rule)
func (r *RuleService) GetRulesetDocument(ctx context.Context, namespace string, slug string, opts ...option.RequestOption) (res *string, err error) {
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "text/plain")}, opts...)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/rulesets/%s/%s", namespace, slug)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Grant an access group to a rule.
//
// Parameters:
//     ctx: Context for the request.
//     namespace: Path parameter.
//     slug: Path parameter.
//     body: RuleNewRulesetAccessGroupParams request parameters.
//     opts: Options to apply to this request.
//
// Returns:
//     *map[string]interface{}: Default Response
//
// Example:
//
//     rule, err := client.Rules.NewRulesetAccessGroup(context.Background(), "namespace", "slug", sdk.RuleNewRulesetAccessGroupParams{
//     	AccessGroup: sdk.AccessGroupParam{
//     	AccessGroupSlug: sdk.F[string]("xxx"),
//     },
//     })
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(rule)
func (r *RuleService) NewRulesetAccessGroup(ctx context.Context, namespace string, slug string, body RuleNewRulesetAccessGroupParams, opts ...option.RequestOption) (res *map[string]interface{}, err error) {
	opts = slices.Concat(r.Options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/rulesets/%s/%s/access-group", namespace, slug)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Remove an access group from a rule.
//
// Parameters:
//     ctx: Context for the request.
//     namespace: Path parameter.
//     slug: Path parameter.
//     body: RuleDeleteRulesetAccessGroupParams request parameters.
//     opts: Options to apply to this request.
//
// Returns:
//     *map[string]interface{}: Default Response
//
// Example:
//
//     rule, err := client.Rules.DeleteRulesetAccessGroup(context.Background(), "namespace", "slug", sdk.RuleDeleteRulesetAccessGroupParams{
//     	AccessGroup: sdk.AccessGroupParam{
//     	AccessGroupSlug: sdk.F[string]("xxx"),
//     },
//     })
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(rule)
func (r *RuleService) DeleteRulesetAccessGroup(ctx context.Context, namespace string, slug string, body RuleDeleteRulesetAccessGroupParams, opts ...option.RequestOption) (res *map[string]interface{}, err error) {
	opts = slices.Concat(r.Options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/rulesets/%s/%s/access-group", namespace, slug)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, body, &res, opts...)
	return res, err
}

type Rule struct {
	UID string `json:"uid" api:"required"`
	Title string `json:"title" api:"required"`
	Description string `json:"description" api:"required"`
	Slug string `json:"slug" api:"required"`
	Namespace string `json:"namespace" api:"required"`
	IsPrivate bool `json:"isPrivate" api:"required"`
	JSON ruleJSON `json:"-"`
}

// ruleJSON contains the JSON metadata for the struct [Rule]
type ruleJSON struct {
	UID apijson.Field
	Title apijson.Field
	Description apijson.Field
	Slug apijson.Field
	Namespace apijson.Field
	IsPrivate apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *Rule) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r ruleJSON) RawJSON() string {
	return r.raw
}

type RuleNewRulesetResponse struct {
	UID string `json:"uid" api:"required"`
	JSON ruleNewRulesetResponseJSON `json:"-"`
}

// ruleNewRulesetResponseJSON contains the JSON metadata for the struct [RuleNewRulesetResponse]
type ruleNewRulesetResponseJSON struct {
	UID apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *RuleNewRulesetResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r ruleNewRulesetResponseJSON) RawJSON() string {
	return r.raw
}

type RuleNewRulesetParams struct {
	Document param.Field[string] `json:"document" api:"required"`
	Slug param.Field[string] `json:"slug" api:"required"`
	Title param.Field[string] `json:"title" api:"required"`
	Description param.Field[string] `json:"description"`
	IsPrivate param.Field[bool] `json:"isPrivate"`
}

func (r RuleNewRulesetParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type RuleUpdateRulesetParams struct {
	Description param.Field[string] `json:"description"`
	IsPrivate param.Field[bool] `json:"isPrivate"`
	Namespace param.Field[string] `json:"namespace"`
	Slug param.Field[string] `json:"slug"`
	Title param.Field[string] `json:"title"`
}

func (r RuleUpdateRulesetParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type RuleNewRulesetAccessGroupParams struct {
	AccessGroup AccessGroupParam `json:"access_group" api:"required"`
}

func (r RuleNewRulesetAccessGroupParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r.AccessGroup)
}

type RuleDeleteRulesetAccessGroupParams struct {
	AccessGroup AccessGroupParam `json:"access_group" api:"required"`
}

func (r RuleDeleteRulesetAccessGroupParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r.AccessGroup)
}
