// Code generated by Scalar SDK Generator. DO NOT EDIT.

package scalarapi

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"scalar-api/internal/apijson"
	shimjson "scalar-api/internal/encoding/json"
	"scalar-api/internal/requestconfig"
	"scalar-api/option"
	"scalar-api/packages/param"
)

// RuleService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewRuleService] method instead.
type RuleService struct {
	options []option.RequestOption
}

// NewRuleService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewRuleService(opts ...option.RequestOption) RuleService {
	s := RuleService{}
	s.options = opts
	return s
}

// List all rulesets in a namespace.
func (r *RuleService) ListRulesets(ctx context.Context, namespace string, opts ...option.RequestOption) (res *[]Rule, err error) {
	opts = slices.Concat(r.options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	requestPath := fmt.Sprintf("v1/rulesets/%s", url.PathEscape(namespace))
	res = new([]Rule)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, requestPath, nil, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

// Create a rule in a namespace.
func (r *RuleService) NewRuleset(ctx context.Context, namespace string, body RuleNewRulesetParams, opts ...option.RequestOption) (res *UID, err error) {
	opts = slices.Concat(r.options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	requestPath := fmt.Sprintf("v1/rulesets/%s", url.PathEscape(namespace))
	res = new(UID)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, requestPath, body, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type RuleNewRulesetParams struct {
	Document string `json:"document" api:"required"`
	Slug string `json:"slug" api:"required"`
	Title string `json:"title" api:"required"`
	Description param.Opt[string] `json:"description,omitzero"`
	IsPrivate param.Opt[bool] `json:"isPrivate,omitzero"`
	paramObj
}

func (r RuleNewRulesetParams) MarshalJSON() (data []byte, err error) {
	type shadow RuleNewRulesetParams
	return param.MarshalObject(r, (*shadow)(&r))
}
func (r *RuleNewRulesetParams) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Update rule metadata by slug.
func (r *RuleService) UpdateRuleset(ctx context.Context, namespace string, slug string, body RuleUpdateRulesetParams, opts ...option.RequestOption) (res *map[string]any, err error) {
	opts = slices.Concat(r.options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	requestPath := fmt.Sprintf("v1/rulesets/%s/%s", url.PathEscape(namespace), url.PathEscape(slug))
	res = new(map[string]any)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPatch, requestPath, body, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type RuleUpdateRulesetParams struct {
	Description param.Opt[string] `json:"description,omitzero"`
	IsPrivate param.Opt[bool] `json:"isPrivate,omitzero"`
	Namespace param.Opt[string] `json:"namespace,omitzero"`
	Slug param.Opt[string] `json:"slug,omitzero"`
	Title param.Opt[string] `json:"title,omitzero"`
	paramObj
}

func (r RuleUpdateRulesetParams) MarshalJSON() (data []byte, err error) {
	type shadow RuleUpdateRulesetParams
	return param.MarshalObject(r, (*shadow)(&r))
}
func (r *RuleUpdateRulesetParams) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Delete a rule by slug.
func (r *RuleService) DeleteRuleset(ctx context.Context, namespace string, slug string, opts ...option.RequestOption) (res *map[string]any, err error) {
	opts = slices.Concat(r.options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	requestPath := fmt.Sprintf("v1/rulesets/%s/%s", url.PathEscape(namespace), url.PathEscape(slug))
	res = new(map[string]any)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, requestPath, nil, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

// Get a rule document by slug.
func (r *RuleService) GetRulesetDocument(ctx context.Context, namespace string, slug string, opts ...option.RequestOption) (res *string, err error) {
	opts = slices.Concat(r.options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	requestPath := fmt.Sprintf("v1/rulesets/%s/%s", url.PathEscape(namespace), url.PathEscape(slug))
	res = new(string)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, requestPath, nil, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

// Grant an access group to a rule.
func (r *RuleService) NewRulesetAccessGroup(ctx context.Context, namespace string, slug string, body RuleNewRulesetAccessGroupParams, opts ...option.RequestOption) (res *map[string]any, err error) {
	opts = slices.Concat(r.options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	requestPath := fmt.Sprintf("v1/rulesets/%s/%s/access-group", url.PathEscape(namespace), url.PathEscape(slug))
	res = new(map[string]any)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, requestPath, body, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type RuleNewRulesetAccessGroupParams struct {
	AccessGroup AccessGroup
	paramObj
}

func (r RuleNewRulesetAccessGroupParams) MarshalJSON() (data []byte, err error) {
	return shimjson.Marshal(r.AccessGroup)
}
func (r *RuleNewRulesetAccessGroupParams) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Remove an access group from a rule.
func (r *RuleService) DeleteRulesetAccessGroup(ctx context.Context, namespace string, slug string, body RuleDeleteRulesetAccessGroupParams, opts ...option.RequestOption) (res *map[string]any, err error) {
	opts = slices.Concat(r.options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	requestPath := fmt.Sprintf("v1/rulesets/%s/%s/access-group", url.PathEscape(namespace), url.PathEscape(slug))
	res = new(map[string]any)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, requestPath, body, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type RuleDeleteRulesetAccessGroupParams struct {
	AccessGroup AccessGroup
	paramObj
}

func (r RuleDeleteRulesetAccessGroupParams) MarshalJSON() (data []byte, err error) {
	return shimjson.Marshal(r.AccessGroup)
}
func (r *RuleDeleteRulesetAccessGroupParams) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}
