// Code generated by Scalar SDK Generator. DO NOT EDIT.

package scalarapi

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"github.com/scalar/scalar-go/internal/apijson"
	"github.com/scalar/scalar-go/internal/requestconfig"
	"github.com/scalar/scalar-go/option"
	"github.com/scalar/scalar-go/packages/param"
	"github.com/scalar/scalar-go/packages/respjson"
)

// ScalarDocService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewScalarDocService] method instead.
type ScalarDocService struct {
	options []option.RequestOption
}

// NewScalarDocService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewScalarDocService(opts ...option.RequestOption) ScalarDocService {
	s := ScalarDocService{}
	s.options = opts
	return s
}

// List all guide projects.
func (r *ScalarDocService) ListGuides(ctx context.Context, opts ...option.RequestOption) (res *[]GithubProject, err error) {
	opts = slices.Concat(r.options, opts)
	requestPath := "v1/guides"
	res = new([]GithubProject)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, requestPath, nil, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

// Create a guide project.
func (r *ScalarDocService) NewGuide(ctx context.Context, body ScalarDocNewGuideParams, opts ...option.RequestOption) (res *ScalarDocNewGuideResponse, err error) {
	opts = slices.Concat(r.options, opts)
	requestPath := "v1/guides"
	res = new(ScalarDocNewGuideResponse)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, requestPath, body, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type ScalarDocNewGuideParams struct {
	AllowedDomains []string `json:"allowedDomains,omitzero" api:"required"`
	AllowedUsers []string `json:"allowedUsers,omitzero" api:"required"`
	IsPrivate bool `json:"isPrivate" api:"required"`
	Name string `json:"name" api:"required"`
	Slug param.Opt[string] `json:"slug,omitzero"`
	paramObj
}

func (r ScalarDocNewGuideParams) MarshalJSON() (data []byte, err error) {
	type shadow ScalarDocNewGuideParams
	return param.MarshalObject(r, (*shadow)(&r))
}
func (r *ScalarDocNewGuideParams) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Start a new publish process.
func (r *ScalarDocService) PublishGuide(ctx context.Context, slug string, opts ...option.RequestOption) (res *ScalarDocPublishGuideResponse, err error) {
	opts = slices.Concat(r.options, opts)
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	requestPath := fmt.Sprintf("v1/guides/%s/publish", url.PathEscape(slug))
	res = new(ScalarDocPublishGuideResponse)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, requestPath, nil, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type ScalarDocNewGuideResponse struct {
	Slug string `json:"slug" api:"required"`
	UID string `json:"uid" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Slug respjson.Field
		UID respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// RawJSON returns the unmodified JSON received from the API.
func (r ScalarDocNewGuideResponse) RawJSON() string { return r.JSON.raw }
func (r *ScalarDocNewGuideResponse) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type ScalarDocPublishGuideResponse struct {
	PublishUID string `json:"publishUid" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		PublishUID respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// RawJSON returns the unmodified JSON received from the API.
func (r ScalarDocPublishGuideResponse) RawJSON() string { return r.JSON.raw }
func (r *ScalarDocPublishGuideResponse) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}
