// Code generated by Scalar SDK Generator. DO NOT EDIT.

package scalargo

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"slices"

	"github.com/scalar/scalar-go/internal/apijson"
	"github.com/scalar/scalar-go/internal/param"
	"github.com/scalar/scalar-go/internal/requestconfig"
	"github.com/scalar/scalar-go/option"
)

// ScalarDocService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewScalarDocService] method instead.
type ScalarDocService struct {
	Options []option.RequestOption
}

// NewScalarDocService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewScalarDocService(opts ...option.RequestOption) (r *ScalarDocService) {
	r = &ScalarDocService{}
	r.Options = opts
	return
}

// List all guide projects.
//
// Parameters:
//
//	ctx: Context for the request.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*[]GithubProject: Default Response
//
// Example:
//
//	scalarDoc, err := client.ScalarDocs.ListGuides(context.Background())
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(scalarDoc)
func (r *ScalarDocService) ListGuides(ctx context.Context, opts ...option.RequestOption) (res *[]GithubProject, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/guides"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Create a guide project.
//
// Parameters:
//
//	ctx: Context for the request.
//	body: ScalarDocNewGuideParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*ScalarDocNewGuideResponse: Default Response
//
// Example:
//
//	scalarDoc, err := client.ScalarDocs.NewGuide(context.Background(), sdk.ScalarDocNewGuideParams{
//		AllowedDomains: sdk.F[[]string]([]string{""}),
//		AllowedUsers:   sdk.F[[]string]([]string{""}),
//		IsPrivate:      sdk.F[bool](false),
//		Name:           sdk.F[string](""),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(scalarDoc)
func (r *ScalarDocService) NewGuide(ctx context.Context, body ScalarDocNewGuideParams, opts ...option.RequestOption) (res *ScalarDocNewGuideResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/guides"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Start a new publish process.
//
// Parameters:
//
//	ctx: Context for the request.
//	slug: Path parameter.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*ScalarDocPublishGuideResponse: Default Response
//
// Example:
//
//	scalarDoc, err := client.ScalarDocs.PublishGuide(context.Background(), "slug")
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(scalarDoc)
func (r *ScalarDocService) PublishGuide(ctx context.Context, slug string, opts ...option.RequestOption) (res *ScalarDocPublishGuideResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/guides/%s/publish", slug)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, nil, &res, opts...)
	return res, err
}

type GithubProject struct {
	UID              string                        `json:"uid" api:"required"`
	CreatedAt        int64                         `json:"createdAt" api:"required"`
	UpdatedAt        int64                         `json:"updatedAt" api:"required"`
	Name             string                        `json:"name" api:"required"`
	ActiveDeployment GithubProjectActiveDeployment `json:"activeDeployment" api:"required,nullable"`
	LastPublished    int64                         `json:"lastPublished" api:"required,nullable"`
	LastPublishedUID string                        `json:"lastPublishedUid" api:"required,nullable"`
	LoginPortalUID   string                        `json:"loginPortalUid" api:"required"`
	ActiveThemeID    string                        `json:"activeThemeId" api:"required"`
	IsPrivate        bool                          `json:"isPrivate" api:"required"`
	AgentEnabled     bool                          `json:"agentEnabled" api:"required"`
	AccessGroups     interface{}                   `json:"accessGroups" api:"required"`
	Slug             string                        `json:"slug" api:"required"`
	PublishStatus    string                        `json:"publishStatus" api:"required"`
	PublishMessage   string                        `json:"publishMessage" api:"required"`
	TypesenseID      float64                       `json:"typesenseId"`
	Repository       GithubProjectRepository       `json:"repository" api:"nullable"`
	JSON             githubProjectJSON             `json:"-"`
}

// githubProjectJSON contains the JSON metadata for the struct [GithubProject]
type githubProjectJSON struct {
	UID              apijson.Field
	CreatedAt        apijson.Field
	UpdatedAt        apijson.Field
	Name             apijson.Field
	ActiveDeployment apijson.Field
	LastPublished    apijson.Field
	LastPublishedUID apijson.Field
	LoginPortalUID   apijson.Field
	ActiveThemeID    apijson.Field
	IsPrivate        apijson.Field
	AgentEnabled     apijson.Field
	AccessGroups     apijson.Field
	Slug             apijson.Field
	PublishStatus    apijson.Field
	PublishMessage   apijson.Field
	TypesenseID      apijson.Field
	Repository       apijson.Field
	raw              string
	ExtraFields      map[string]apijson.Field
}

func (r *GithubProject) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r githubProjectJSON) RawJSON() string {
	return r.raw
}

type GithubProjectRepository struct {
	LinkedBy        string                      `json:"linkedBy" api:"required"`
	ID              float64                     `json:"id" api:"required"`
	Name            string                      `json:"name" api:"required"`
	ConfigPath      string                      `json:"configPath" api:"required"`
	Branch          string                      `json:"branch" api:"required"`
	PublishOnMerge  bool                        `json:"publishOnMerge" api:"required"`
	PublishPreviews bool                        `json:"publishPreviews" api:"required"`
	PrComments      bool                        `json:"prComments" api:"required"`
	Expired         bool                        `json:"expired" api:"required"`
	JSON            githubProjectRepositoryJSON `json:"-"`
}

// githubProjectRepositoryJSON contains the JSON metadata for the struct [GithubProjectRepository]
type githubProjectRepositoryJSON struct {
	LinkedBy        apijson.Field
	ID              apijson.Field
	Name            apijson.Field
	ConfigPath      apijson.Field
	Branch          apijson.Field
	PublishOnMerge  apijson.Field
	PublishPreviews apijson.Field
	PrComments      apijson.Field
	Expired         apijson.Field
	raw             string
	ExtraFields     map[string]apijson.Field
}

func (r *GithubProjectRepository) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r githubProjectRepositoryJSON) RawJSON() string {
	return r.raw
}

type GithubProjectActiveDeployment struct {
	UID         string                            `json:"uid" api:"required"`
	Domain      string                            `json:"domain" api:"required"`
	PublishedAt int64                             `json:"publishedAt" api:"required"`
	JSON        githubProjectActiveDeploymentJSON `json:"-"`
}

// githubProjectActiveDeploymentJSON contains the JSON metadata for the struct [GithubProjectActiveDeployment]
type githubProjectActiveDeploymentJSON struct {
	UID         apijson.Field
	Domain      apijson.Field
	PublishedAt apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *GithubProjectActiveDeployment) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r githubProjectActiveDeploymentJSON) RawJSON() string {
	return r.raw
}

type GithubProjectActiveDeploymentParam struct {
	Domain      param.Field[string] `json:"domain" api:"required"`
	PublishedAt param.Field[int64]  `json:"publishedAt" api:"required"`
	UID         param.Field[string] `json:"uid" api:"required"`
}

func (r GithubProjectActiveDeploymentParam) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type ScalarDocNewGuideParams struct {
	AllowedDomains param.Field[[]string] `json:"allowedDomains" api:"required"`
	AllowedUsers   param.Field[[]string] `json:"allowedUsers" api:"required"`
	IsPrivate      param.Field[bool]     `json:"isPrivate" api:"required"`
	Name           param.Field[string]   `json:"name" api:"required"`
	Slug           param.Field[string]   `json:"slug"`
}

func (r ScalarDocNewGuideParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type ScalarDocNewGuideResponse struct {
	UID  string                        `json:"uid" api:"required"`
	Slug string                        `json:"slug" api:"required"`
	JSON scalarDocNewGuideResponseJSON `json:"-"`
}

// scalarDocNewGuideResponseJSON contains the JSON metadata for the struct [ScalarDocNewGuideResponse]
type scalarDocNewGuideResponseJSON struct {
	UID         apijson.Field
	Slug        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *ScalarDocNewGuideResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r scalarDocNewGuideResponseJSON) RawJSON() string {
	return r.raw
}

type ScalarDocPublishGuideResponse struct {
	PublishUID string                            `json:"publishUid" api:"required"`
	JSON       scalarDocPublishGuideResponseJSON `json:"-"`
}

// scalarDocPublishGuideResponseJSON contains the JSON metadata for the struct [ScalarDocPublishGuideResponse]
type scalarDocPublishGuideResponseJSON struct {
	PublishUID  apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *ScalarDocPublishGuideResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r scalarDocPublishGuideResponseJSON) RawJSON() string {
	return r.raw
}
