// Code generated by Scalar SDK Generator. DO NOT EDIT.

package sdk

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"github.com/scalar/scalar-go/internal/apijson"
	"github.com/scalar/scalar-go/internal/param"
	"github.com/scalar/scalar-go/internal/requestconfig"
	"github.com/scalar/scalar-go/option"
)

// SchemaVersionService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewSchemaVersionService] method instead.
type SchemaVersionService struct {
	Options []option.RequestOption
}

// NewSchemaVersionService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewSchemaVersionService(opts ...option.RequestOption) (r *SchemaVersionService) {
	r = &SchemaVersionService{}
	r.Options = opts
	return
}

// Get a specific schema version document.
//
// Parameters:
//
//	ctx: Context for the request.
//	namespace: Path parameter.
//	slug: Path parameter.
//	semver: Path parameter.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*string: Default Response
//
// Example:
//
//	version, err := client.Schemas.Version.Get(context.Background(), "acme", "customer", "1.2.0")
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(version)
func (r *SchemaVersionService) Get(ctx context.Context, namespace string, slug string, semver string, opts ...option.RequestOption) (res *string, err error) {
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "text/plain")}, opts...)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	if semver == "" {
		err = errors.New("missing required semver parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/schemas/%s/%s/version/%s", url.PathEscape(namespace), url.PathEscape(slug), url.PathEscape(semver))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Delete a schema version.
//
// Parameters:
//
//	ctx: Context for the request.
//	namespace: Path parameter.
//	slug: Path parameter.
//	semver: Path parameter.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*map[string]interface{}: Default Response
//
// Example:
//
//	version, err := client.Schemas.Version.Delete(context.Background(), "acme", "customer", "1.2.0")
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(version)
func (r *SchemaVersionService) Delete(ctx context.Context, namespace string, slug string, semver string, opts ...option.RequestOption) (res *map[string]interface{}, err error) {
	opts = slices.Concat(r.Options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	if semver == "" {
		err = errors.New("missing required semver parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/schemas/%s/%s/version/%s", url.PathEscape(namespace), url.PathEscape(slug), url.PathEscape(semver))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, nil, &res, opts...)
	return res, err
}

// Create a schema version.
//
// Parameters:
//
//	ctx: Context for the request.
//	namespace: Path parameter.
//	slug: Path parameter.
//	body: SchemaVersionNewParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*SchemaVersionNewResponse: Default Response
//
// Example:
//
//	version, err := client.Schemas.Version.New(context.Background(), "acme", "customer", sdk.SchemaVersionNewParams{
//		Document: sdk.F[string]("{\"type\":\"object\",\"properties\":{\"name\":{\"type\":\"string\",\"examples\":[\"Acme\"]}}}"),
//		Version:  sdk.F[string]("1.2.0"),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(version)
func (r *SchemaVersionService) New(ctx context.Context, namespace string, slug string, body SchemaVersionNewParams, opts ...option.RequestOption) (res *SchemaVersionNewResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/schemas/%s/%s/version", url.PathEscape(namespace), url.PathEscape(slug))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

type SchemaVersionNewParams struct {
	Document param.Field[string] `json:"document" api:"required"`
	Version  param.Field[string] `json:"version" api:"required"`
	Force    param.Field[bool]   `json:"force"`
}

func (r SchemaVersionNewParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type SchemaVersionNewResponse struct {
	UID  string                       `json:"uid" api:"required"`
	JSON schemaVersionNewResponseJSON `json:"-"`
}

// schemaVersionNewResponseJSON contains the JSON metadata for the struct [SchemaVersionNewResponse]
type schemaVersionNewResponseJSON struct {
	UID         apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *SchemaVersionNewResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r schemaVersionNewResponseJSON) RawJSON() string {
	return r.raw
}
