// Code generated by Scalar SDK Generator. DO NOT EDIT.

package scalargo

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"slices"

	"github.com/scalar/scalar-go/internal/apijson"
	"github.com/scalar/scalar-go/internal/param"
	"github.com/scalar/scalar-go/internal/requestconfig"
	"github.com/scalar/scalar-go/option"
)

// SchemaService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewSchemaService] method instead.
type SchemaService struct {
	Options     []option.RequestOption
	Version     *SchemaVersionService
	AccessGroup *SchemaAccessGroupService
}

// NewSchemaService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewSchemaService(opts ...option.RequestOption) (r *SchemaService) {
	r = &SchemaService{}
	r.Options = opts
	r.Version = NewSchemaVersionService(opts...)
	r.AccessGroup = NewSchemaAccessGroupService(opts...)
	return
}

// List schemas in a namespace.
//
// Parameters:
//
//	ctx: Context for the request.
//	namespace: Path parameter.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*[]Schema: Default Response
//
// Example:
//
//	schema, err := client.Schemas.List(context.Background(), "namespace")
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(schema)
func (r *SchemaService) List(ctx context.Context, namespace string, opts ...option.RequestOption) (res *[]Schema, err error) {
	opts = slices.Concat(r.Options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/schemas/%s", namespace)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Create a schema in a namespace.
//
// Parameters:
//
//	ctx: Context for the request.
//	namespace: Path parameter.
//	body: SchemaNewParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*SchemaNewResponse: Default Response
//
// Example:
//
//	schema, err := client.Schemas.New(context.Background(), "namespace", sdk.SchemaNewParams{
//		Document: sdk.F[string](""),
//		Slug:     sdk.F[string](""),
//		Title:    sdk.F[string](""),
//		Version:  sdk.F[string]("x"),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(schema)
func (r *SchemaService) New(ctx context.Context, namespace string, body SchemaNewParams, opts ...option.RequestOption) (res *SchemaNewResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/schemas/%s", namespace)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Update schema metadata.
//
// Parameters:
//
//	ctx: Context for the request.
//	namespace: Path parameter.
//	slug: Path parameter.
//	body: SchemaUpdateParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*map[string]interface{}: Default Response
//
// Example:
//
//	schema, err := client.Schemas.Update(context.Background(), "namespace", "slug", sdk.SchemaUpdateParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(schema)
func (r *SchemaService) Update(ctx context.Context, namespace string, slug string, body SchemaUpdateParams, opts ...option.RequestOption) (res *map[string]interface{}, err error) {
	opts = slices.Concat(r.Options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/schemas/%s/%s", namespace, slug)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPatch, path, body, &res, opts...)
	return res, err
}

// Delete a schema and all related versions.
//
// Parameters:
//
//	ctx: Context for the request.
//	namespace: Path parameter.
//	slug: Path parameter.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*map[string]interface{}: Default Response
//
// Example:
//
//	schema, err := client.Schemas.Delete(context.Background(), "namespace", "slug")
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(schema)
func (r *SchemaService) Delete(ctx context.Context, namespace string, slug string, opts ...option.RequestOption) (res *map[string]interface{}, err error) {
	opts = slices.Concat(r.Options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/schemas/%s/%s", namespace, slug)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, nil, &res, opts...)
	return res, err
}

type Schema struct {
	UID         string          `json:"uid" api:"required"`
	Title       string          `json:"title" api:"required"`
	Description string          `json:"description" api:"required"`
	Slug        string          `json:"slug" api:"required"`
	Namespace   string          `json:"namespace" api:"required"`
	IsPrivate   bool            `json:"isPrivate" api:"required"`
	Versions    []SchemaVersion `json:"versions" api:"required"`
	JSON        schemaJSON      `json:"-"`
}

// schemaJSON contains the JSON metadata for the struct [Schema]
type schemaJSON struct {
	UID         apijson.Field
	Title       apijson.Field
	Description apijson.Field
	Slug        apijson.Field
	Namespace   apijson.Field
	IsPrivate   apijson.Field
	Versions    apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *Schema) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r schemaJSON) RawJSON() string {
	return r.raw
}

type SchemaNewResponse struct {
	UID  string                `json:"uid" api:"required"`
	JSON schemaNewResponseJSON `json:"-"`
}

// schemaNewResponseJSON contains the JSON metadata for the struct [SchemaNewResponse]
type schemaNewResponseJSON struct {
	UID         apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *SchemaNewResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r schemaNewResponseJSON) RawJSON() string {
	return r.raw
}

type SchemaNewParams struct {
	Document    param.Field[string] `json:"document" api:"required"`
	Slug        param.Field[string] `json:"slug" api:"required"`
	Title       param.Field[string] `json:"title" api:"required"`
	Version     param.Field[string] `json:"version" api:"required"`
	Description param.Field[string] `json:"description"`
	IsPrivate   param.Field[bool]   `json:"isPrivate"`
}

func (r SchemaNewParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type SchemaUpdateParams struct {
	Description param.Field[string] `json:"description"`
	IsPrivate   param.Field[bool]   `json:"isPrivate"`
	Title       param.Field[string] `json:"title"`
}

func (r SchemaUpdateParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type SchemaVersion struct {
	UID       string            `json:"uid" api:"required"`
	CreatedAt int64             `json:"createdAt" api:"required"`
	UpdatedAt int64             `json:"updatedAt" api:"required"`
	Version   string            `json:"version" api:"required"`
	JSON      schemaVersionJSON `json:"-"`
}

// schemaVersionJSON contains the JSON metadata for the struct [SchemaVersion]
type schemaVersionJSON struct {
	UID         apijson.Field
	CreatedAt   apijson.Field
	UpdatedAt   apijson.Field
	Version     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *SchemaVersion) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r schemaVersionJSON) RawJSON() string {
	return r.raw
}
