// Code generated by Scalar SDK Generator. DO NOT EDIT.

package scalarapi

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"github.com/scalar/scalar-go/internal/apijson"
	shimjson "github.com/scalar/scalar-go/internal/encoding/json"
	"github.com/scalar/scalar-go/internal/requestconfig"
	"github.com/scalar/scalar-go/option"
)

// SchemaAccessGroupService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewSchemaAccessGroupService] method instead.
type SchemaAccessGroupService struct {
	options []option.RequestOption
}

// NewSchemaAccessGroupService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewSchemaAccessGroupService(opts ...option.RequestOption) SchemaAccessGroupService {
	s := SchemaAccessGroupService{}
	s.options = opts
	return s
}

// Add an access group to a schema.
func (r *SchemaAccessGroupService) NewSchema(ctx context.Context, namespace string, slug string, body SchemaAccessGroupNewSchemaParams, opts ...option.RequestOption) (res *map[string]any, err error) {
	opts = slices.Concat(r.options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	requestPath := fmt.Sprintf("v1/schemas/%s/%s/access-group", url.PathEscape(namespace), url.PathEscape(slug))
	res = new(map[string]any)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, requestPath, body, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type SchemaAccessGroupNewSchemaParams struct {
	AccessGroup AccessGroup
	paramObj
}

func (r SchemaAccessGroupNewSchemaParams) MarshalJSON() (data []byte, err error) {
	return shimjson.Marshal(r.AccessGroup)
}
func (r *SchemaAccessGroupNewSchemaParams) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Remove an access group from a schema.
func (r *SchemaAccessGroupService) DeleteSchema(ctx context.Context, namespace string, slug string, body SchemaAccessGroupDeleteSchemaParams, opts ...option.RequestOption) (res *map[string]any, err error) {
	opts = slices.Concat(r.options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	requestPath := fmt.Sprintf("v1/schemas/%s/%s/access-group", url.PathEscape(namespace), url.PathEscape(slug))
	res = new(map[string]any)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, requestPath, body, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type SchemaAccessGroupDeleteSchemaParams struct {
	AccessGroup AccessGroup
	paramObj
}

func (r SchemaAccessGroupDeleteSchemaParams) MarshalJSON() (data []byte, err error) {
	return shimjson.Marshal(r.AccessGroup)
}
func (r *SchemaAccessGroupDeleteSchemaParams) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}
