// Code generated by Scalar SDK Generator. DO NOT EDIT.

package scalarapi

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"github.com/scalar/scalar-go/internal/apijson"
	"github.com/scalar/scalar-go/internal/requestconfig"
	"github.com/scalar/scalar-go/option"
	"github.com/scalar/scalar-go/packages/param"
)

// SchemaVersionService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewSchemaVersionService] method instead.
type SchemaVersionService struct {
	options []option.RequestOption
}

// NewSchemaVersionService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewSchemaVersionService(opts ...option.RequestOption) SchemaVersionService {
	s := SchemaVersionService{}
	s.options = opts
	return s
}

// Get a specific schema version document.
func (r *SchemaVersionService) GetSchema(ctx context.Context, namespace string, slug string, semver string, opts ...option.RequestOption) (res *string, err error) {
	opts = slices.Concat(r.options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	if semver == "" {
		err = errors.New("missing required semver parameter")
		return nil, err
	}
	requestPath := fmt.Sprintf("v1/schemas/%s/%s/version/%s", url.PathEscape(namespace), url.PathEscape(slug), url.PathEscape(semver))
	res = new(string)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, requestPath, nil, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

// Delete a schema version.
func (r *SchemaVersionService) DeleteSchema(ctx context.Context, namespace string, slug string, semver string, opts ...option.RequestOption) (res *map[string]any, err error) {
	opts = slices.Concat(r.options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	if semver == "" {
		err = errors.New("missing required semver parameter")
		return nil, err
	}
	requestPath := fmt.Sprintf("v1/schemas/%s/%s/version/%s", url.PathEscape(namespace), url.PathEscape(slug), url.PathEscape(semver))
	res = new(map[string]any)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, requestPath, nil, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

// Create a schema version.
func (r *SchemaVersionService) NewSchema(ctx context.Context, namespace string, slug string, body SchemaVersionNewSchemaParams, opts ...option.RequestOption) (res *UID, err error) {
	opts = slices.Concat(r.options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	requestPath := fmt.Sprintf("v1/schemas/%s/%s/version", url.PathEscape(namespace), url.PathEscape(slug))
	res = new(UID)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, requestPath, body, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type SchemaVersionNewSchemaParams struct {
	Document string `json:"document" api:"required"`
	Version string `json:"version" api:"required"`
	paramObj
}

func (r SchemaVersionNewSchemaParams) MarshalJSON() (data []byte, err error) {
	type shadow SchemaVersionNewSchemaParams
	return param.MarshalObject(r, (*shadow)(&r))
}
func (r *SchemaVersionNewSchemaParams) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}
