// Code generated by Scalar SDK Generator. DO NOT EDIT.

package scalargo

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"slices"

	"github.com/scalar/scalar-go/internal/apijson"
	"github.com/scalar/scalar-go/internal/param"
	"github.com/scalar/scalar-go/internal/requestconfig"
	"github.com/scalar/scalar-go/option"
)

// SchemaVersionService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewSchemaVersionService] method instead.
type SchemaVersionService struct {
	Options []option.RequestOption
}

// NewSchemaVersionService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewSchemaVersionService(opts ...option.RequestOption) (r *SchemaVersionService) {
	r = &SchemaVersionService{}
	r.Options = opts
	return
}

// Get a specific schema version document.
//
// Parameters:
//     ctx: Context for the request.
//     namespace: Path parameter.
//     slug: Path parameter.
//     semver: Path parameter.
//     opts: Options to apply to this request.
//
// Returns:
//     *string: Default Response
//
// Example:
//
//     version, err := client.Schemas.Version.GetSchema(context.Background(), "namespace", "slug", "semver")
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(version)
func (r *SchemaVersionService) GetSchema(ctx context.Context, namespace string, slug string, semver string, opts ...option.RequestOption) (res *string, err error) {
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "text/plain")}, opts...)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	if semver == "" {
		err = errors.New("missing required semver parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/schemas/%s/%s/version/%s", namespace, slug, semver)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Delete a schema version.
//
// Parameters:
//     ctx: Context for the request.
//     namespace: Path parameter.
//     slug: Path parameter.
//     semver: Path parameter.
//     opts: Options to apply to this request.
//
// Returns:
//     *map[string]interface{}: Default Response
//
// Example:
//
//     version, err := client.Schemas.Version.DeleteSchema(context.Background(), "namespace", "slug", "semver")
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(version)
func (r *SchemaVersionService) DeleteSchema(ctx context.Context, namespace string, slug string, semver string, opts ...option.RequestOption) (res *map[string]interface{}, err error) {
	opts = slices.Concat(r.Options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	if semver == "" {
		err = errors.New("missing required semver parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/schemas/%s/%s/version/%s", namespace, slug, semver)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, nil, &res, opts...)
	return res, err
}

// Create a schema version.
//
// Parameters:
//     ctx: Context for the request.
//     namespace: Path parameter.
//     slug: Path parameter.
//     body: SchemaVersionNewSchemaParams request parameters.
//     opts: Options to apply to this request.
//
// Returns:
//     *SchemaVersionNewSchemaResponse: Default Response
//
// Example:
//
//     version, err := client.Schemas.Version.NewSchema(context.Background(), "namespace", "slug", sdk.SchemaVersionNewSchemaParams{
//     	Document: sdk.F[string](""),
//     	Version: sdk.F[string]("x"),
//     })
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(version)
func (r *SchemaVersionService) NewSchema(ctx context.Context, namespace string, slug string, body SchemaVersionNewSchemaParams, opts ...option.RequestOption) (res *SchemaVersionNewSchemaResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/schemas/%s/%s/version", namespace, slug)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

type SchemaVersionNewSchemaResponse struct {
	UID string `json:"uid" api:"required"`
	JSON schemaVersionNewSchemaResponseJSON `json:"-"`
}

// schemaVersionNewSchemaResponseJSON contains the JSON metadata for the struct [SchemaVersionNewSchemaResponse]
type schemaVersionNewSchemaResponseJSON struct {
	UID apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *SchemaVersionNewSchemaResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r schemaVersionNewSchemaResponseJSON) RawJSON() string {
	return r.raw
}

type SchemaVersionNewSchemaParams struct {
	Document param.Field[string] `json:"document" api:"required"`
	Version param.Field[string] `json:"version" api:"required"`
}

func (r SchemaVersionNewSchemaParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}
