// Code generated by Scalar SDK Generator. DO NOT EDIT.

package scalarapi

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"slices"

	"scalar-api/internal/apijson"
	"scalar-api/internal/param"
	"scalar-api/internal/requestconfig"
	"scalar-api/option"
)

// SchemaService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewSchemaService] method instead.
type SchemaService struct {
	Options []option.RequestOption
}

// NewSchemaService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewSchemaService(opts ...option.RequestOption) (r *SchemaService) {
	r = &SchemaService{}
	r.Options = opts
	return
}

// List schemas in a namespace.
//
// Parameters:
//     ctx: Context for the request.
//     namespace: Path parameter.
//     opts: Options to apply to this request.
//
// Returns:
//     *[]Schema: Default Response
//
// Example:
//
//     schema, err := client.Schemas.List(context.Background(), "namespace")
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(schema)
func (r *SchemaService) List(ctx context.Context, namespace string, opts ...option.RequestOption) (res *[]Schema, err error) {
	opts = slices.Concat(r.Options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/schemas/%s", namespace)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Create a schema in a namespace.
//
// Parameters:
//     ctx: Context for the request.
//     namespace: Path parameter.
//     body: SchemaNewParams request parameters.
//     opts: Options to apply to this request.
//
// Returns:
//     *SchemaNewResponse: Default Response
//
// Example:
//
//     schema, err := client.Schemas.New(context.Background(), "namespace", sdk.SchemaNewParams{
//     	Document: sdk.F[string](""),
//     	Slug: sdk.F[string](""),
//     	Title: sdk.F[string](""),
//     	Version: sdk.F[string]("x"),
//     })
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(schema)
func (r *SchemaService) New(ctx context.Context, namespace string, body SchemaNewParams, opts ...option.RequestOption) (res *SchemaNewResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/schemas/%s", namespace)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Update schema metadata.
//
// Parameters:
//     ctx: Context for the request.
//     namespace: Path parameter.
//     slug: Path parameter.
//     body: SchemaUpdateParams request parameters.
//     opts: Options to apply to this request.
//
// Returns:
//     *map[string]any: Default Response
//
// Example:
//
//     schema, err := client.Schemas.Update(context.Background(), "namespace", "slug", sdk.SchemaUpdateParams{})
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(schema)
func (r *SchemaService) Update(ctx context.Context, namespace string, slug string, body SchemaUpdateParams, opts ...option.RequestOption) (res *map[string]any, err error) {
	opts = slices.Concat(r.Options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/schemas/%s/%s", namespace, slug)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPatch, path, body, &res, opts...)
	return res, err
}

// Delete a schema and all related versions.
//
// Parameters:
//     ctx: Context for the request.
//     namespace: Path parameter.
//     slug: Path parameter.
//     opts: Options to apply to this request.
//
// Returns:
//     *map[string]any: Default Response
//
// Example:
//
//     schema, err := client.Schemas.Delete(context.Background(), "namespace", "slug")
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(schema)
func (r *SchemaService) Delete(ctx context.Context, namespace string, slug string, opts ...option.RequestOption) (res *map[string]any, err error) {
	opts = slices.Concat(r.Options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/schemas/%s/%s", namespace, slug)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, nil, &res, opts...)
	return res, err
}

// Get a specific schema version document.
//
// Parameters:
//     ctx: Context for the request.
//     namespace: Path parameter.
//     slug: Path parameter.
//     semver: Path parameter.
//     opts: Options to apply to this request.
//
// Returns:
//     *string: Default Response
//
// Example:
//
//     schema, err := client.Schemas.GetVersion(context.Background(), "namespace", "slug", "semver")
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(schema)
func (r *SchemaService) GetVersion(ctx context.Context, namespace string, slug string, semver string, opts ...option.RequestOption) (res *string, err error) {
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "text/plain")}, opts...)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	if semver == "" {
		err = errors.New("missing required semver parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/schemas/%s/%s/version/%s", namespace, slug, semver)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Delete a schema version.
//
// Parameters:
//     ctx: Context for the request.
//     namespace: Path parameter.
//     slug: Path parameter.
//     semver: Path parameter.
//     opts: Options to apply to this request.
//
// Returns:
//     *map[string]any: Default Response
//
// Example:
//
//     schema, err := client.Schemas.DeleteVersion(context.Background(), "namespace", "slug", "semver")
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(schema)
func (r *SchemaService) DeleteVersion(ctx context.Context, namespace string, slug string, semver string, opts ...option.RequestOption) (res *map[string]any, err error) {
	opts = slices.Concat(r.Options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	if semver == "" {
		err = errors.New("missing required semver parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/schemas/%s/%s/version/%s", namespace, slug, semver)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, nil, &res, opts...)
	return res, err
}

// Create a schema version.
//
// Parameters:
//     ctx: Context for the request.
//     namespace: Path parameter.
//     slug: Path parameter.
//     body: SchemaNewVersionParams request parameters.
//     opts: Options to apply to this request.
//
// Returns:
//     *SchemaNewVersionResponse: Default Response
//
// Example:
//
//     schema, err := client.Schemas.NewVersion(context.Background(), "namespace", "slug", sdk.SchemaNewVersionParams{
//     	Document: sdk.F[string](""),
//     	Version: sdk.F[string]("x"),
//     })
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(schema)
func (r *SchemaService) NewVersion(ctx context.Context, namespace string, slug string, body SchemaNewVersionParams, opts ...option.RequestOption) (res *SchemaNewVersionResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/schemas/%s/%s/version", namespace, slug)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Add an access group to a schema.
//
// Parameters:
//     ctx: Context for the request.
//     namespace: Path parameter.
//     slug: Path parameter.
//     body: SchemaNewAccessGroupParams request parameters.
//     opts: Options to apply to this request.
//
// Returns:
//     *map[string]any: Default Response
//
// Example:
//
//     schema, err := client.Schemas.NewAccessGroup(context.Background(), "namespace", "slug", sdk.SchemaNewAccessGroupParams{
//     	AccessGroupSlug: sdk.F[string]("xxx"),
//     })
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(schema)
func (r *SchemaService) NewAccessGroup(ctx context.Context, namespace string, slug string, body SchemaNewAccessGroupParams, opts ...option.RequestOption) (res *map[string]any, err error) {
	opts = slices.Concat(r.Options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/schemas/%s/%s/access-group", namespace, slug)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Remove an access group from a schema.
//
// Parameters:
//     ctx: Context for the request.
//     namespace: Path parameter.
//     slug: Path parameter.
//     body: SchemaDeleteAccessGroupParams request parameters.
//     opts: Options to apply to this request.
//
// Returns:
//     *map[string]any: Default Response
//
// Example:
//
//     schema, err := client.Schemas.DeleteAccessGroup(context.Background(), "namespace", "slug", sdk.SchemaDeleteAccessGroupParams{
//     	AccessGroupSlug: sdk.F[string]("xxx"),
//     })
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(schema)
func (r *SchemaService) DeleteAccessGroup(ctx context.Context, namespace string, slug string, body SchemaDeleteAccessGroupParams, opts ...option.RequestOption) (res *map[string]any, err error) {
	opts = slices.Concat(r.Options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/schemas/%s/%s/access-group", namespace, slug)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, body, &res, opts...)
	return res, err
}

type Schema struct {
	UID string `json:"uid" api:"required"`
	Title string `json:"title" api:"required"`
	Description string `json:"description" api:"required"`
	Slug string `json:"slug" api:"required"`
	Namespace string `json:"namespace" api:"required"`
	IsPrivate bool `json:"isPrivate" api:"required"`
	Versions []SchemaManagedSchemaVersion `json:"versions" api:"required"`
	JSON schemaJSON `json:"-"`
}

// schemaJSON contains the JSON metadata for the struct [Schema]
type schemaJSON struct {
	UID apijson.Field
	Title apijson.Field
	Description apijson.Field
	Slug apijson.Field
	Namespace apijson.Field
	IsPrivate apijson.Field
	Versions apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *Schema) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r schemaJSON) RawJSON() string {
	return r.raw
}

type SchemaManagedSchemaVersion struct {
	UID string `json:"uid" api:"required"`
	CreatedAt int64 `json:"createdAt" api:"required"`
	UpdatedAt int64 `json:"updatedAt" api:"required"`
	Version string `json:"version" api:"required"`
	JSON schemaManagedSchemaVersionJSON `json:"-"`
}

// schemaManagedSchemaVersionJSON contains the JSON metadata for the struct [SchemaManagedSchemaVersion]
type schemaManagedSchemaVersionJSON struct {
	UID apijson.Field
	CreatedAt apijson.Field
	UpdatedAt apijson.Field
	Version apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *SchemaManagedSchemaVersion) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r schemaManagedSchemaVersionJSON) RawJSON() string {
	return r.raw
}

type SchemaManagedSchemaVersionParam struct {
	CreatedAt param.Field[int64] `json:"createdAt" api:"required"`
	UID param.Field[string] `json:"uid" api:"required"`
	UpdatedAt param.Field[int64] `json:"updatedAt" api:"required"`
	Version param.Field[string] `json:"version" api:"required"`
}

func (r SchemaManagedSchemaVersionParam) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type SchemaListResponse struct {
	Message string `json:"message" api:"required"`
	Code string `json:"code" api:"required"`
	JSON schemaListResponseJSON `json:"-"`
}

// schemaListResponseJSON contains the JSON metadata for the struct [SchemaListResponse]
type schemaListResponseJSON struct {
	Message apijson.Field
	Code apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *SchemaListResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r schemaListResponseJSON) RawJSON() string {
	return r.raw
}

type SchemaNewResponse struct {
	UID string `json:"uid" api:"required"`
	JSON schemaNewResponseJSON `json:"-"`
}

// schemaNewResponseJSON contains the JSON metadata for the struct [SchemaNewResponse]
type schemaNewResponseJSON struct {
	UID apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *SchemaNewResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r schemaNewResponseJSON) RawJSON() string {
	return r.raw
}

type SchemaUpdateResponse struct {
	Message string `json:"message" api:"required"`
	Code string `json:"code" api:"required"`
	JSON schemaUpdateResponseJSON `json:"-"`
}

// schemaUpdateResponseJSON contains the JSON metadata for the struct [SchemaUpdateResponse]
type schemaUpdateResponseJSON struct {
	Message apijson.Field
	Code apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *SchemaUpdateResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r schemaUpdateResponseJSON) RawJSON() string {
	return r.raw
}

type SchemaDeleteResponse struct {
	Message string `json:"message" api:"required"`
	Code string `json:"code" api:"required"`
	JSON schemaDeleteResponseJSON `json:"-"`
}

// schemaDeleteResponseJSON contains the JSON metadata for the struct [SchemaDeleteResponse]
type schemaDeleteResponseJSON struct {
	Message apijson.Field
	Code apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *SchemaDeleteResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r schemaDeleteResponseJSON) RawJSON() string {
	return r.raw
}

type SchemaGetVersionResponse struct {
	Message string `json:"message" api:"required"`
	Code string `json:"code" api:"required"`
	JSON schemaGetVersionResponseJSON `json:"-"`
}

// schemaGetVersionResponseJSON contains the JSON metadata for the struct [SchemaGetVersionResponse]
type schemaGetVersionResponseJSON struct {
	Message apijson.Field
	Code apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *SchemaGetVersionResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r schemaGetVersionResponseJSON) RawJSON() string {
	return r.raw
}

type SchemaDeleteVersionResponse struct {
	Message string `json:"message" api:"required"`
	Code string `json:"code" api:"required"`
	JSON schemaDeleteVersionResponseJSON `json:"-"`
}

// schemaDeleteVersionResponseJSON contains the JSON metadata for the struct [SchemaDeleteVersionResponse]
type schemaDeleteVersionResponseJSON struct {
	Message apijson.Field
	Code apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *SchemaDeleteVersionResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r schemaDeleteVersionResponseJSON) RawJSON() string {
	return r.raw
}

type SchemaNewVersionResponse struct {
	UID string `json:"uid" api:"required"`
	JSON schemaNewVersionResponseJSON `json:"-"`
}

// schemaNewVersionResponseJSON contains the JSON metadata for the struct [SchemaNewVersionResponse]
type schemaNewVersionResponseJSON struct {
	UID apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *SchemaNewVersionResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r schemaNewVersionResponseJSON) RawJSON() string {
	return r.raw
}

type SchemaNewAccessGroupResponse struct {
	Message string `json:"message" api:"required"`
	Code string `json:"code" api:"required"`
	JSON schemaNewAccessGroupResponseJSON `json:"-"`
}

// schemaNewAccessGroupResponseJSON contains the JSON metadata for the struct [SchemaNewAccessGroupResponse]
type schemaNewAccessGroupResponseJSON struct {
	Message apijson.Field
	Code apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *SchemaNewAccessGroupResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r schemaNewAccessGroupResponseJSON) RawJSON() string {
	return r.raw
}

type SchemaDeleteAccessGroupResponse struct {
	Message string `json:"message" api:"required"`
	Code string `json:"code" api:"required"`
	JSON schemaDeleteAccessGroupResponseJSON `json:"-"`
}

// schemaDeleteAccessGroupResponseJSON contains the JSON metadata for the struct [SchemaDeleteAccessGroupResponse]
type schemaDeleteAccessGroupResponseJSON struct {
	Message apijson.Field
	Code apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *SchemaDeleteAccessGroupResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r schemaDeleteAccessGroupResponseJSON) RawJSON() string {
	return r.raw
}

type SchemaNewParams struct {
	Document param.Field[string] `json:"document" api:"required"`
	Slug param.Field[string] `json:"slug" api:"required"`
	Title param.Field[string] `json:"title" api:"required"`
	Version param.Field[string] `json:"version" api:"required"`
	Description param.Field[string] `json:"description"`
	IsPrivate param.Field[bool] `json:"isPrivate"`
}

func (r SchemaNewParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type SchemaUpdateParams struct {
	Description param.Field[string] `json:"description"`
	IsPrivate param.Field[bool] `json:"isPrivate"`
	Title param.Field[string] `json:"title"`
}

func (r SchemaUpdateParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type SchemaNewVersionParams struct {
	Document param.Field[string] `json:"document" api:"required"`
	Version param.Field[string] `json:"version" api:"required"`
}

func (r SchemaNewVersionParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type SchemaNewAccessGroupParams struct {
	AccessGroupSlug param.Field[string] `json:"accessGroupSlug" api:"required"`
}

func (r SchemaNewAccessGroupParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type SchemaDeleteAccessGroupParams struct {
	AccessGroupSlug param.Field[string] `json:"accessGroupSlug" api:"required"`
}

func (r SchemaDeleteAccessGroupParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}
