// Code generated by Scalar SDK Generator. DO NOT EDIT.

package sdk

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"github.com/scalar/scalar-go/internal/apijson"
	"github.com/scalar/scalar-go/internal/requestconfig"
	"github.com/scalar/scalar-go/option"
)

// SchemaAccessGroupService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewSchemaAccessGroupService] method instead.
type SchemaAccessGroupService struct {
	Options []option.RequestOption
}

// NewSchemaAccessGroupService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewSchemaAccessGroupService(opts ...option.RequestOption) (r *SchemaAccessGroupService) {
	r = &SchemaAccessGroupService{}
	r.Options = opts
	return
}

// Add an access group to a schema.
//
// Parameters:
//
//	ctx: Context for the request.
//	namespace: Path parameter.
//	slug: Path parameter.
//	body: SchemaAccessGroupNewParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*map[string]interface{}: Default Response
//
// Example:
//
//	accessGroup, err := client.Schemas.AccessGroup.New(context.Background(), "namespace", "slug", sdk.SchemaAccessGroupNewParams{
//		AccessGroup: sdk.AccessGroupParam{
//			AccessGroupSlug: sdk.F[string]("xxx"),
//		},
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(accessGroup)
func (r *SchemaAccessGroupService) New(ctx context.Context, namespace string, slug string, body SchemaAccessGroupNewParams, opts ...option.RequestOption) (res *map[string]interface{}, err error) {
	opts = slices.Concat(r.Options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/schemas/%s/%s/access-group", url.PathEscape(namespace), url.PathEscape(slug))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Remove an access group from a schema.
//
// Parameters:
//
//	ctx: Context for the request.
//	namespace: Path parameter.
//	slug: Path parameter.
//	body: SchemaAccessGroupDeleteParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*map[string]interface{}: Default Response
//
// Example:
//
//	accessGroup, err := client.Schemas.AccessGroup.Delete(context.Background(), "namespace", "slug", sdk.SchemaAccessGroupDeleteParams{
//		AccessGroup: sdk.AccessGroupParam{
//			AccessGroupSlug: sdk.F[string]("xxx"),
//		},
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(accessGroup)
func (r *SchemaAccessGroupService) Delete(ctx context.Context, namespace string, slug string, body SchemaAccessGroupDeleteParams, opts ...option.RequestOption) (res *map[string]interface{}, err error) {
	opts = slices.Concat(r.Options, opts)
	if namespace == "" {
		err = errors.New("missing required namespace parameter")
		return nil, err
	}
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/schemas/%s/%s/access-group", url.PathEscape(namespace), url.PathEscape(slug))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, body, &res, opts...)
	return res, err
}

type SchemaAccessGroupNewParams struct {
	AccessGroup AccessGroupParam `json:"access_group" api:"required"`
}

func (r SchemaAccessGroupNewParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r.AccessGroup)
}

type SchemaAccessGroupDeleteParams struct {
	AccessGroup AccessGroupParam `json:"access_group" api:"required"`
}

func (r SchemaAccessGroupDeleteParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r.AccessGroup)
}
