// Code generated by Scalar SDK Generator. DO NOT EDIT.

package sdk

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"github.com/scalar/scalar-go/internal/apijson"
	"github.com/scalar/scalar-go/internal/param"
	"github.com/scalar/scalar-go/internal/requestconfig"
	"github.com/scalar/scalar-go/option"
)

// SdkRepositoryService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewSdkRepositoryService] method instead.
type SdkRepositoryService struct {
	Options []option.RequestOption
}

// NewSdkRepositoryService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewSdkRepositoryService(opts ...option.RequestOption) (r *SdkRepositoryService) {
	r = &SdkRepositoryService{}
	r.Options = opts
	return
}

// Link one language target to a GitHub repository, so builds sync there.
//
// Parameters:
//
//	ctx: Context for the request.
//	uid: Path parameter.
//	body: SdkRepositoryLinkParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*SdkRepositoryLinkResponse: Default Response
//
// Example:
//
//	repository, err := client.Sdks.Repositories.Link(context.Background(), "UakgbKJ5m9gl0JDMbcJqL", sdk.SdkRepositoryLinkParams{
//		BaseBranch:   sdk.F[string]("main"),
//		Language:     sdk.F[sdk.SdkRepositoryLinkParamsLanguage](sdk.SdkRepositoryLinkParamsLanguage("typescript")),
//		RepositoryID: sdk.F[int64](123456789),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(repository)
func (r *SdkRepositoryService) Link(ctx context.Context, uid string, body SdkRepositoryLinkParams, opts ...option.RequestOption) (res *SdkRepositoryLinkResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	if uid == "" {
		err = errors.New("missing required uid parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/sdks/%s/repositories", url.PathEscape(uid))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Unlink one language target from its repository.
//
// Parameters:
//
//	ctx: Context for the request.
//	uid: Path parameter.
//	language: Path parameter.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*map[string]interface{}: Default Response
//
// Example:
//
//	repository, err := client.Sdks.Repositories.Unlink(context.Background(), "UakgbKJ5m9gl0JDMbcJqL", "typescript")
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(repository)
func (r *SdkRepositoryService) Unlink(ctx context.Context, uid string, language SdkRepositoryUnlinkParamsLanguage, opts ...option.RequestOption) (res *map[string]interface{}, err error) {
	opts = slices.Concat(r.Options, opts)
	if uid == "" {
		err = errors.New("missing required uid parameter")
		return nil, err
	}
	if language == "" {
		err = errors.New("missing required language parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/sdks/%s/repositories/%s", url.PathEscape(uid), url.PathEscape(string(language)))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, nil, &res, opts...)
	return res, err
}

// Toggle publish-on-merge and the release settings for a linked target.
//
// Parameters:
//
//	ctx: Context for the request.
//	uid: Path parameter.
//	language: Path parameter.
//	body: SdkRepositoryUpdatePublishingParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*map[string]interface{}: Default Response
//
// Example:
//
//	repository, err := client.Sdks.Repositories.UpdatePublishing(context.Background(), "UakgbKJ5m9gl0JDMbcJqL", "typescript", sdk.SdkRepositoryUpdatePublishingParams{
//		PublishOnMerge: sdk.F[bool](true),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(repository)
func (r *SdkRepositoryService) UpdatePublishing(ctx context.Context, uid string, language SdkRepositoryUpdatePublishingParamsLanguage, body SdkRepositoryUpdatePublishingParams, opts ...option.RequestOption) (res *map[string]interface{}, err error) {
	opts = slices.Concat(r.Options, opts)
	if uid == "" {
		err = errors.New("missing required uid parameter")
		return nil, err
	}
	if language == "" {
		err = errors.New("missing required language parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/sdks/%s/repositories/%s/publishing", url.PathEscape(uid), url.PathEscape(string(language)))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

type SdkRepositoryLinkParams struct {
	BaseBranch     param.Field[string]                          `json:"baseBranch" api:"required"`
	Language       param.Field[SdkRepositoryLinkParamsLanguage] `json:"language" api:"required"`
	RepositoryID   param.Field[int64]                           `json:"repositoryId" api:"required"`
	PrereleaseType param.Field[string]                          `json:"prereleaseType"`
}

func (r SdkRepositoryLinkParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type SdkRepositoryLinkParamsLanguage string

const (
	SdkRepositoryLinkParamsLanguageTypescript SdkRepositoryLinkParamsLanguage = "typescript"
	SdkRepositoryLinkParamsLanguagePython     SdkRepositoryLinkParamsLanguage = "python"
	SdkRepositoryLinkParamsLanguageCli        SdkRepositoryLinkParamsLanguage = "cli"
	SdkRepositoryLinkParamsLanguageCsharp     SdkRepositoryLinkParamsLanguage = "csharp"
	SdkRepositoryLinkParamsLanguageJava       SdkRepositoryLinkParamsLanguage = "java"
	SdkRepositoryLinkParamsLanguageRuby       SdkRepositoryLinkParamsLanguage = "ruby"
	SdkRepositoryLinkParamsLanguagePhp        SdkRepositoryLinkParamsLanguage = "php"
	SdkRepositoryLinkParamsLanguageGo         SdkRepositoryLinkParamsLanguage = "go"
	SdkRepositoryLinkParamsLanguageRust       SdkRepositoryLinkParamsLanguage = "rust"
	SdkRepositoryLinkParamsLanguageKotlin     SdkRepositoryLinkParamsLanguage = "kotlin"
	SdkRepositoryLinkParamsLanguageSwift      SdkRepositoryLinkParamsLanguage = "swift"
	SdkRepositoryLinkParamsLanguageCpp        SdkRepositoryLinkParamsLanguage = "cpp"
	SdkRepositoryLinkParamsLanguageDart       SdkRepositoryLinkParamsLanguage = "dart"
)

func (r SdkRepositoryLinkParamsLanguage) IsKnown() bool {
	switch r {
	case SdkRepositoryLinkParamsLanguageTypescript, SdkRepositoryLinkParamsLanguagePython, SdkRepositoryLinkParamsLanguageCli, SdkRepositoryLinkParamsLanguageCsharp, SdkRepositoryLinkParamsLanguageJava, SdkRepositoryLinkParamsLanguageRuby, SdkRepositoryLinkParamsLanguagePhp, SdkRepositoryLinkParamsLanguageGo, SdkRepositoryLinkParamsLanguageRust, SdkRepositoryLinkParamsLanguageKotlin, SdkRepositoryLinkParamsLanguageSwift, SdkRepositoryLinkParamsLanguageCpp, SdkRepositoryLinkParamsLanguageDart:
		return true
	}
	return false
}

type SdkRepositoryUpdatePublishingParams struct {
	PublishOnMerge param.Field[bool]                                          `json:"publishOnMerge" api:"required"`
	Access         param.Field[SdkRepositoryUpdatePublishingParamsAccess]     `json:"access"`
	AuthMethod     param.Field[SdkRepositoryUpdatePublishingParamsAuthMethod] `json:"authMethod"`
	Tag            param.Field[string]                                        `json:"tag"`
}

func (r SdkRepositoryUpdatePublishingParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type SdkRepositoryUpdatePublishingParamsAuthMethod string

const (
	SdkRepositoryUpdatePublishingParamsAuthMethodOidc        SdkRepositoryUpdatePublishingParamsAuthMethod = "oidc"
	SdkRepositoryUpdatePublishingParamsAuthMethodAccessToken SdkRepositoryUpdatePublishingParamsAuthMethod = "access-token"
)

func (r SdkRepositoryUpdatePublishingParamsAuthMethod) IsKnown() bool {
	switch r {
	case SdkRepositoryUpdatePublishingParamsAuthMethodOidc, SdkRepositoryUpdatePublishingParamsAuthMethodAccessToken:
		return true
	}
	return false
}

type SdkRepositoryUpdatePublishingParamsAccess string

const (
	SdkRepositoryUpdatePublishingParamsAccessPublic     SdkRepositoryUpdatePublishingParamsAccess = "public"
	SdkRepositoryUpdatePublishingParamsAccessRestricted SdkRepositoryUpdatePublishingParamsAccess = "restricted"
)

func (r SdkRepositoryUpdatePublishingParamsAccess) IsKnown() bool {
	switch r {
	case SdkRepositoryUpdatePublishingParamsAccessPublic, SdkRepositoryUpdatePublishingParamsAccessRestricted:
		return true
	}
	return false
}

type SdkRepositoryUpdatePublishingParamsLanguage string

const (
	SdkRepositoryUpdatePublishingParamsLanguageTypescript SdkRepositoryUpdatePublishingParamsLanguage = "typescript"
	SdkRepositoryUpdatePublishingParamsLanguagePython     SdkRepositoryUpdatePublishingParamsLanguage = "python"
	SdkRepositoryUpdatePublishingParamsLanguageCli        SdkRepositoryUpdatePublishingParamsLanguage = "cli"
	SdkRepositoryUpdatePublishingParamsLanguageCsharp     SdkRepositoryUpdatePublishingParamsLanguage = "csharp"
	SdkRepositoryUpdatePublishingParamsLanguageJava       SdkRepositoryUpdatePublishingParamsLanguage = "java"
	SdkRepositoryUpdatePublishingParamsLanguageRuby       SdkRepositoryUpdatePublishingParamsLanguage = "ruby"
	SdkRepositoryUpdatePublishingParamsLanguagePhp        SdkRepositoryUpdatePublishingParamsLanguage = "php"
	SdkRepositoryUpdatePublishingParamsLanguageGo         SdkRepositoryUpdatePublishingParamsLanguage = "go"
	SdkRepositoryUpdatePublishingParamsLanguageRust       SdkRepositoryUpdatePublishingParamsLanguage = "rust"
	SdkRepositoryUpdatePublishingParamsLanguageKotlin     SdkRepositoryUpdatePublishingParamsLanguage = "kotlin"
	SdkRepositoryUpdatePublishingParamsLanguageSwift      SdkRepositoryUpdatePublishingParamsLanguage = "swift"
	SdkRepositoryUpdatePublishingParamsLanguageCpp        SdkRepositoryUpdatePublishingParamsLanguage = "cpp"
	SdkRepositoryUpdatePublishingParamsLanguageDart       SdkRepositoryUpdatePublishingParamsLanguage = "dart"
)

func (r SdkRepositoryUpdatePublishingParamsLanguage) IsKnown() bool {
	switch r {
	case SdkRepositoryUpdatePublishingParamsLanguageTypescript, SdkRepositoryUpdatePublishingParamsLanguagePython, SdkRepositoryUpdatePublishingParamsLanguageCli, SdkRepositoryUpdatePublishingParamsLanguageCsharp, SdkRepositoryUpdatePublishingParamsLanguageJava, SdkRepositoryUpdatePublishingParamsLanguageRuby, SdkRepositoryUpdatePublishingParamsLanguagePhp, SdkRepositoryUpdatePublishingParamsLanguageGo, SdkRepositoryUpdatePublishingParamsLanguageRust, SdkRepositoryUpdatePublishingParamsLanguageKotlin, SdkRepositoryUpdatePublishingParamsLanguageSwift, SdkRepositoryUpdatePublishingParamsLanguageCpp, SdkRepositoryUpdatePublishingParamsLanguageDart:
		return true
	}
	return false
}

type SdkRepositoryLinkResponse struct {
	Branch string                        `json:"branch" api:"required"`
	Repo   string                        `json:"repo" api:"required"`
	JSON   sdkRepositoryLinkResponseJSON `json:"-"`
}

// sdkRepositoryLinkResponseJSON contains the JSON metadata for the struct [SdkRepositoryLinkResponse]
type sdkRepositoryLinkResponseJSON struct {
	Branch      apijson.Field
	Repo        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *SdkRepositoryLinkResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r sdkRepositoryLinkResponseJSON) RawJSON() string {
	return r.raw
}

type SdkRepositoryUnlinkParamsLanguage string

const (
	SdkRepositoryUnlinkParamsLanguageTypescript SdkRepositoryUnlinkParamsLanguage = "typescript"
	SdkRepositoryUnlinkParamsLanguagePython     SdkRepositoryUnlinkParamsLanguage = "python"
	SdkRepositoryUnlinkParamsLanguageCli        SdkRepositoryUnlinkParamsLanguage = "cli"
	SdkRepositoryUnlinkParamsLanguageCsharp     SdkRepositoryUnlinkParamsLanguage = "csharp"
	SdkRepositoryUnlinkParamsLanguageJava       SdkRepositoryUnlinkParamsLanguage = "java"
	SdkRepositoryUnlinkParamsLanguageRuby       SdkRepositoryUnlinkParamsLanguage = "ruby"
	SdkRepositoryUnlinkParamsLanguagePhp        SdkRepositoryUnlinkParamsLanguage = "php"
	SdkRepositoryUnlinkParamsLanguageGo         SdkRepositoryUnlinkParamsLanguage = "go"
	SdkRepositoryUnlinkParamsLanguageRust       SdkRepositoryUnlinkParamsLanguage = "rust"
	SdkRepositoryUnlinkParamsLanguageKotlin     SdkRepositoryUnlinkParamsLanguage = "kotlin"
	SdkRepositoryUnlinkParamsLanguageSwift      SdkRepositoryUnlinkParamsLanguage = "swift"
	SdkRepositoryUnlinkParamsLanguageCpp        SdkRepositoryUnlinkParamsLanguage = "cpp"
	SdkRepositoryUnlinkParamsLanguageDart       SdkRepositoryUnlinkParamsLanguage = "dart"
)

func (r SdkRepositoryUnlinkParamsLanguage) IsKnown() bool {
	switch r {
	case SdkRepositoryUnlinkParamsLanguageTypescript, SdkRepositoryUnlinkParamsLanguagePython, SdkRepositoryUnlinkParamsLanguageCli, SdkRepositoryUnlinkParamsLanguageCsharp, SdkRepositoryUnlinkParamsLanguageJava, SdkRepositoryUnlinkParamsLanguageRuby, SdkRepositoryUnlinkParamsLanguagePhp, SdkRepositoryUnlinkParamsLanguageGo, SdkRepositoryUnlinkParamsLanguageRust, SdkRepositoryUnlinkParamsLanguageKotlin, SdkRepositoryUnlinkParamsLanguageSwift, SdkRepositoryUnlinkParamsLanguageCpp, SdkRepositoryUnlinkParamsLanguageDart:
		return true
	}
	return false
}
