// Code generated by Scalar SDK Generator. DO NOT EDIT.

package scalarapi

import (
	"scalar-api/internal/apijson"
	"scalar-api/packages/respjson"
)

type APIDocument struct {
	Description string `json:"description" api:"required"`
	IsPrivate bool `json:"isPrivate" api:"required"`
	Namespace string `json:"namespace" api:"required"`
	Slug string `json:"slug" api:"required"`
	Tags string `json:"tags" api:"required"`
	Title string `json:"title" api:"required"`
	UID string `json:"uid" api:"required"`
	Version string `json:"version" api:"required"`
	Versions []ManagedDocVersion `json:"versions" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Description respjson.Field
		IsPrivate respjson.Field
		Namespace respjson.Field
		Slug respjson.Field
		Tags respjson.Field
		Title respjson.Field
		UID respjson.Field
		Version respjson.Field
		Versions respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// RawJSON returns the unmodified JSON received from the API.
func (r APIDocument) RawJSON() string { return r.JSON.raw }
func (r *APIDocument) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type ManagedDocVersion struct {
	CreatedAt float64 `json:"createdAt" api:"required"`
	// Any of "complete", "failed".
	EmbedStatus ManagedDocVersionEmbedStatus `json:"embedStatus" api:"required"`
	Tags []string `json:"tags" api:"required"`
	UID string `json:"uid" api:"required"`
	Upgraded bool `json:"upgraded" api:"required"`
	Version string `json:"version" api:"required"`
	JSONSha string `json:"jsonSha"`
	Tools []ManagedDocVersionTool `json:"tools"`
	VersionSha string `json:"versionSha"`
	YamlSha string `json:"yamlSha"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		CreatedAt respjson.Field
		EmbedStatus respjson.Field
		Tags respjson.Field
		UID respjson.Field
		Upgraded respjson.Field
		Version respjson.Field
		JSONSha respjson.Field
		Tools respjson.Field
		VersionSha respjson.Field
		YamlSha respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// RawJSON returns the unmodified JSON received from the API.
func (r ManagedDocVersion) RawJSON() string { return r.JSON.raw }
func (r *ManagedDocVersion) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type Schema struct {
	Description string `json:"description" api:"required"`
	IsPrivate bool `json:"isPrivate" api:"required"`
	Namespace string `json:"namespace" api:"required"`
	Slug string `json:"slug" api:"required"`
	Title string `json:"title" api:"required"`
	UID string `json:"uid" api:"required"`
	Versions []ManagedSchemaVersion `json:"versions" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Description respjson.Field
		IsPrivate respjson.Field
		Namespace respjson.Field
		Slug respjson.Field
		Title respjson.Field
		UID respjson.Field
		Versions respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// RawJSON returns the unmodified JSON received from the API.
func (r Schema) RawJSON() string { return r.JSON.raw }
func (r *Schema) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type ManagedSchemaVersion struct {
	CreatedAt int64 `json:"createdAt" api:"required"`
	UID string `json:"uid" api:"required"`
	UpdatedAt int64 `json:"updatedAt" api:"required"`
	Version string `json:"version" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		CreatedAt respjson.Field
		UID respjson.Field
		UpdatedAt respjson.Field
		Version respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// RawJSON returns the unmodified JSON received from the API.
func (r ManagedSchemaVersion) RawJSON() string { return r.JSON.raw }
func (r *ManagedSchemaVersion) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type UID struct {
	UID string `json:"uid" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		UID respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// RawJSON returns the unmodified JSON received from the API.
func (r UID) RawJSON() string { return r.JSON.raw }
func (r *UID) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type LoginPortal struct {
	Slug string `json:"slug" api:"required"`
	Title string `json:"title" api:"required"`
	UID string `json:"uid" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Slug respjson.Field
		Title respjson.Field
		UID respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// RawJSON returns the unmodified JSON received from the API.
func (r LoginPortal) RawJSON() string { return r.JSON.raw }
func (r *LoginPortal) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type Rule struct {
	Description string `json:"description" api:"required"`
	IsPrivate bool `json:"isPrivate" api:"required"`
	Namespace string `json:"namespace" api:"required"`
	Slug string `json:"slug" api:"required"`
	Title string `json:"title" api:"required"`
	UID string `json:"uid" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Description respjson.Field
		IsPrivate respjson.Field
		Namespace respjson.Field
		Slug respjson.Field
		Title respjson.Field
		UID respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// RawJSON returns the unmodified JSON received from the API.
func (r Rule) RawJSON() string { return r.JSON.raw }
func (r *Rule) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type Theme struct {
	Description string `json:"description" api:"required"`
	Name string `json:"name" api:"required"`
	Slug string `json:"slug" api:"required"`
	UID string `json:"uid" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Description respjson.Field
		Name respjson.Field
		Slug respjson.Field
		UID respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// RawJSON returns the unmodified JSON received from the API.
func (r Theme) RawJSON() string { return r.JSON.raw }
func (r *Theme) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type Team struct {
	Name string `json:"name" api:"required"`
	Slug string `json:"slug" api:"required"`
	Theme string `json:"theme" api:"required"`
	UID string `json:"uid" api:"required"`
	ImageURI string `json:"imageUri"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Name respjson.Field
		Slug respjson.Field
		Theme respjson.Field
		UID respjson.Field
		ImageURI respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// RawJSON returns the unmodified JSON received from the API.
func (r Team) RawJSON() string { return r.JSON.raw }
func (r *Team) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type GithubProject struct {
	AccessGroups string `json:"accessGroups" api:"required"`
	ActiveDeployment ActiveDeployment `json:"activeDeployment" api:"required"`
	ActiveThemeID string `json:"activeThemeId" api:"required"`
	AgentEnabled bool `json:"agentEnabled" api:"required"`
	CreatedAt int64 `json:"createdAt" api:"required"`
	IsPrivate bool `json:"isPrivate" api:"required"`
	LastPublished int64 `json:"lastPublished" api:"required"`
	LastPublishedUID string `json:"lastPublishedUid" api:"required"`
	LoginPortalUID string `json:"loginPortalUid" api:"required"`
	Name string `json:"name" api:"required"`
	PublishMessage string `json:"publishMessage" api:"required"`
	PublishStatus string `json:"publishStatus" api:"required"`
	Slug string `json:"slug" api:"required"`
	UID string `json:"uid" api:"required"`
	UpdatedAt int64 `json:"updatedAt" api:"required"`
	Repository GithubProjectRepository `json:"repository"`
	TypesenseID float64 `json:"typesenseId"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		AccessGroups respjson.Field
		ActiveDeployment respjson.Field
		ActiveThemeID respjson.Field
		AgentEnabled respjson.Field
		CreatedAt respjson.Field
		IsPrivate respjson.Field
		LastPublished respjson.Field
		LastPublishedUID respjson.Field
		LoginPortalUID respjson.Field
		Name respjson.Field
		PublishMessage respjson.Field
		PublishStatus respjson.Field
		Slug respjson.Field
		UID respjson.Field
		UpdatedAt respjson.Field
		Repository respjson.Field
		TypesenseID respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// RawJSON returns the unmodified JSON received from the API.
func (r GithubProject) RawJSON() string { return r.JSON.raw }
func (r *GithubProject) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type ActiveDeployment struct {
	Domain string `json:"domain" api:"required"`
	PublishedAt int64 `json:"publishedAt" api:"required"`
	UID string `json:"uid" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Domain respjson.Field
		PublishedAt respjson.Field
		UID respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// RawJSON returns the unmodified JSON received from the API.
func (r ActiveDeployment) RawJSON() string { return r.JSON.raw }
func (r *ActiveDeployment) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type GithubProjectRepository struct {
	Branch string `json:"branch" api:"required"`
	ConfigPath string `json:"configPath" api:"required"`
	Expired bool `json:"expired" api:"required"`
	ID float64 `json:"id" api:"required"`
	LinkedBy string `json:"linkedBy" api:"required"`
	Name string `json:"name" api:"required"`
	PrComments bool `json:"prComments" api:"required"`
	PublishOnMerge bool `json:"publishOnMerge" api:"required"`
	PublishPreviews bool `json:"publishPreviews" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Branch respjson.Field
		ConfigPath respjson.Field
		Expired respjson.Field
		ID respjson.Field
		LinkedBy respjson.Field
		Name respjson.Field
		PrComments respjson.Field
		PublishOnMerge respjson.Field
		PublishPreviews respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// RawJSON returns the unmodified JSON received from the API.
func (r GithubProjectRepository) RawJSON() string { return r.JSON.raw }
func (r *GithubProjectRepository) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type TeamSummary struct {
	Name string `json:"name" api:"required"`
	UID string `json:"uid" api:"required"`
	ImageURI string `json:"imageUri"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		Name respjson.Field
		UID respjson.Field
		ImageURI respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// RawJSON returns the unmodified JSON received from the API.
func (r TeamSummary) RawJSON() string { return r.JSON.raw }
func (r *TeamSummary) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type User struct {
	ActiveTeamID string `json:"activeTeamId" api:"required"`
	CreatedAt int64 `json:"createdAt" api:"required"`
	Email string `json:"email" api:"required" format:"email"`
	HasGithub bool `json:"hasGithub" api:"required"`
	Teams []TeamSummary `json:"teams" api:"required"`
	UID string `json:"uid" api:"required"`
	UpdatedAt int64 `json:"updatedAt" api:"required"`
	Theme string `json:"theme"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		ActiveTeamID respjson.Field
		CreatedAt respjson.Field
		Email respjson.Field
		HasGithub respjson.Field
		Teams respjson.Field
		UID respjson.Field
		UpdatedAt respjson.Field
		Theme respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// RawJSON returns the unmodified JSON received from the API.
func (r User) RawJSON() string { return r.JSON.raw }
func (r *User) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

type ManagedDocVersionEmbedStatus string

const (
	ManagedDocVersionEmbedStatusComplete ManagedDocVersionEmbedStatus = "complete"
	ManagedDocVersionEmbedStatusFailed ManagedDocVersionEmbedStatus = "failed"
)

type ManagedDocVersionTool struct {
	// Any of "execute-request", "get-mini-openapi-spec".
	EnabledTools []string `json:"enabledTools" api:"required"`
	// Any of "delete", "get", "head", "options", "patch", "post", "put", "trace".
	Method string `json:"method" api:"required"`
	Path string `json:"path" api:"required"`
	// JSON contains metadata for fields, check presence with [respjson.Field.Valid].
	JSON struct {
		EnabledTools respjson.Field
		Method respjson.Field
		Path respjson.Field
		ExtraFields map[string]respjson.Field
		raw         string
	} `json:"-"`
}

// RawJSON returns the unmodified JSON received from the API.
func (r ManagedDocVersionTool) RawJSON() string { return r.JSON.raw }
func (r *ManagedDocVersionTool) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}
