// Code generated by Scalar SDK Generator. DO NOT EDIT.

package scalarapi

import (
	"context"
	"net/http"
	"slices"

	"scalar-api/internal/apijson"
	"scalar-api/internal/requestconfig"
	"scalar-api/option"
)

// TeamService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewTeamService] method instead.
type TeamService struct {
	Options []option.RequestOption
}

// NewTeamService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewTeamService(opts ...option.RequestOption) (r *TeamService) {
	r = &TeamService{}
	r.Options = opts
	return
}

// List all available teams
//
// Parameters:
//     ctx: Context for the request.
//     opts: Options to apply to this request.
//
// Returns:
//     *[]Team: Default Response
//
// Example:
//
//     team, err := client.Teams.List(context.Background())
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(team)
func (r *TeamService) List(ctx context.Context, opts ...option.RequestOption) (res *[]Team, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/teams"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

type Team struct {
	UID string `json:"uid" api:"required"`
	Name string `json:"name" api:"required"`
	Slug string `json:"slug" api:"required"`
	Theme string `json:"theme" api:"required"`
	ImageURI string `json:"imageUri"`
	JSON teamJSON `json:"-"`
}

// teamJSON contains the JSON metadata for the struct [Team]
type teamJSON struct {
	UID apijson.Field
	Name apijson.Field
	Slug apijson.Field
	Theme apijson.Field
	ImageURI apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *Team) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r teamJSON) RawJSON() string {
	return r.raw
}

type TeamListResponse struct {
	Message string `json:"message" api:"required"`
	Code string `json:"code" api:"required"`
	JSON teamListResponseJSON `json:"-"`
}

// teamListResponseJSON contains the JSON metadata for the struct [TeamListResponse]
type teamListResponseJSON struct {
	Message apijson.Field
	Code apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *TeamListResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r teamListResponseJSON) RawJSON() string {
	return r.raw
}
