// Code generated by Scalar SDK Generator. DO NOT EDIT.

package sdk

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"github.com/scalar/scalar-go/internal/apijson"
	"github.com/scalar/scalar-go/internal/param"
	"github.com/scalar/scalar-go/internal/requestconfig"
	"github.com/scalar/scalar-go/option"
)

// TeamMemberService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewTeamMemberService] method instead.
type TeamMemberService struct {
	Options []option.RequestOption
}

// NewTeamMemberService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewTeamMemberService(opts ...option.RequestOption) (r *TeamMemberService) {
	r = &TeamMemberService{}
	r.Options = opts
	return
}

// List the members of the current team, along with the invites still outstanding.
//
// Parameters:
//
//	ctx: Context for the request.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*TeamMemberListResponse: Default Response
//
// Example:
//
//	member, err := client.Teams.Members.List(context.Background())
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(member)
func (r *TeamMemberService) List(ctx context.Context, opts ...option.RequestOption) (res *TeamMemberListResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/teams/members"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Change what a member of the current team is allowed to do.
//
// Parameters:
//
//	ctx: Context for the request.
//	uid: Path parameter.
//	body: TeamMemberUpdateParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*map[string]interface{}: Default Response
//
// Example:
//
//	member, err := client.Teams.Members.Update(context.Background(), "UakgbKJ5m9gl0JDMbcJqL", sdk.TeamMemberUpdateParams{
//		Role: sdk.F[sdk.Role](sdk.Role("owner")),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(member)
func (r *TeamMemberService) Update(ctx context.Context, uid string, body TeamMemberUpdateParams, opts ...option.RequestOption) (res *map[string]interface{}, err error) {
	opts = slices.Concat(r.Options, opts)
	if uid == "" {
		err = errors.New("missing required uid parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/teams/members/%s", url.PathEscape(uid))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPatch, path, body, &res, opts...)
	return res, err
}

// Remove someone from the current team.
//
// Parameters:
//
//	ctx: Context for the request.
//	uid: Path parameter.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*map[string]interface{}: Default Response
//
// Example:
//
//	member, err := client.Teams.Members.Delete(context.Background(), "UakgbKJ5m9gl0JDMbcJqL")
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(member)
func (r *TeamMemberService) Delete(ctx context.Context, uid string, opts ...option.RequestOption) (res *map[string]interface{}, err error) {
	opts = slices.Concat(r.Options, opts)
	if uid == "" {
		err = errors.New("missing required uid parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/teams/members/%s", url.PathEscape(uid))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, nil, &res, opts...)
	return res, err
}

type TeamMember struct {
	DisplayName string         `json:"displayName" api:"required"`
	Role        Role           `json:"role" api:"required"`
	UID         string         `json:"uid" api:"required"`
	ImageURI    string         `json:"imageUri"`
	JSON        teamMemberJSON `json:"-"`
}

// teamMemberJSON contains the JSON metadata for the struct [TeamMember]
type teamMemberJSON struct {
	DisplayName apijson.Field
	Role        apijson.Field
	UID         apijson.Field
	ImageURI    apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *TeamMember) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r teamMemberJSON) RawJSON() string {
	return r.raw
}

type TeamInvite struct {
	Email   string         `json:"email" api:"required" format:"email"`
	Role    Role           `json:"role" api:"required"`
	UID     string         `json:"uid" api:"required"`
	Expires float64        `json:"expires"`
	JSON    teamInviteJSON `json:"-"`
}

// teamInviteJSON contains the JSON metadata for the struct [TeamInvite]
type teamInviteJSON struct {
	Email       apijson.Field
	Role        apijson.Field
	UID         apijson.Field
	Expires     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *TeamInvite) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r teamInviteJSON) RawJSON() string {
	return r.raw
}

type TeamMemberUpdateParams struct {
	Role param.Field[Role] `json:"role" api:"required"`
}

func (r TeamMemberUpdateParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type TeamMemberListResponse struct {
	Members        []TeamMember               `json:"members" api:"required"`
	PendingInvites []TeamInvite               `json:"pendingInvites" api:"required"`
	JSON           teamMemberListResponseJSON `json:"-"`
}

// teamMemberListResponseJSON contains the JSON metadata for the struct [TeamMemberListResponse]
type teamMemberListResponseJSON struct {
	Members        apijson.Field
	PendingInvites apijson.Field
	raw            string
	ExtraFields    map[string]apijson.Field
}

func (r *TeamMemberListResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r teamMemberListResponseJSON) RawJSON() string {
	return r.raw
}
