// Code generated by Scalar SDK Generator. DO NOT EDIT.

package scalarapi

import (
	"context"
	"net/http"
	"slices"

	"github.com/scalar/scalar-go/internal/requestconfig"
	"github.com/scalar/scalar-go/option"
)

// TeamService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewTeamService] method instead.
type TeamService struct {
	options []option.RequestOption
}

// NewTeamService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewTeamService(opts ...option.RequestOption) TeamService {
	s := TeamService{}
	s.options = opts
	return s
}

// List all available teams
func (r *TeamService) List(ctx context.Context, opts ...option.RequestOption) (res *[]Team, err error) {
	opts = slices.Concat(r.options, opts)
	requestPath := "v1/teams"
	res = new([]Team)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, requestPath, nil, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}
