// Code generated by Scalar SDK Generator. DO NOT EDIT.

package sdk

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"github.com/scalar/scalar-go/internal/apijson"
	"github.com/scalar/scalar-go/internal/param"
	"github.com/scalar/scalar-go/internal/requestconfig"
	"github.com/scalar/scalar-go/option"
)

// TeamInviteService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewTeamInviteService] method instead.
type TeamInviteService struct {
	Options []option.RequestOption
}

// NewTeamInviteService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewTeamInviteService(opts ...option.RequestOption) (r *TeamInviteService) {
	r = &TeamInviteService{}
	r.Options = opts
	return
}

// Invite someone to the current team by email.
//
// Parameters:
//
//	ctx: Context for the request.
//	body: TeamInviteMemberParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*map[string]interface{}: Default Response
//
// Example:
//
//	invite, err := client.Teams.Invites.Member(context.Background(), sdk.TeamInviteMemberParams{
//		Email: sdk.F[string]("alex@example.com"),
//		Role:  sdk.F[sdk.Role](sdk.Role("owner")),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(invite)
func (r *TeamInviteService) Member(ctx context.Context, body TeamInviteMemberParams, opts ...option.RequestOption) (res *map[string]interface{}, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/teams/invites"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Send the invite email again.
//
// Parameters:
//
//	ctx: Context for the request.
//	uid: Path parameter.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*map[string]interface{}: Default Response
//
// Example:
//
//	invite, err := client.Teams.Invites.Resend(context.Background(), "UakgbKJ5m9gl0JDMbcJqL")
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(invite)
func (r *TeamInviteService) Resend(ctx context.Context, uid string, opts ...option.RequestOption) (res *map[string]interface{}, err error) {
	opts = slices.Concat(r.Options, opts)
	if uid == "" {
		err = errors.New("missing required uid parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/teams/invites/%s", url.PathEscape(uid))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPatch, path, nil, &res, opts...)
	return res, err
}

// Withdraw an invite that has not been accepted.
//
// Parameters:
//
//	ctx: Context for the request.
//	uid: Path parameter.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*map[string]interface{}: Default Response
//
// Example:
//
//	invite, err := client.Teams.Invites.Cancel(context.Background(), "UakgbKJ5m9gl0JDMbcJqL")
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(invite)
func (r *TeamInviteService) Cancel(ctx context.Context, uid string, opts ...option.RequestOption) (res *map[string]interface{}, err error) {
	opts = slices.Concat(r.Options, opts)
	if uid == "" {
		err = errors.New("missing required uid parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/teams/invites/%s", url.PathEscape(uid))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, nil, &res, opts...)
	return res, err
}

type Role string

const (
	RoleOwner  Role = "owner"
	RoleAdmin  Role = "admin"
	RoleEditor Role = "editor"
	RoleViewer Role = "viewer"
)

func (r Role) IsKnown() bool {
	switch r {
	case RoleOwner, RoleAdmin, RoleEditor, RoleViewer:
		return true
	}
	return false
}

type TeamInviteMemberParams struct {
	Email param.Field[string] `json:"email" api:"required" format:"email"`
	Role  param.Field[Role]   `json:"role" api:"required"`
}

func (r TeamInviteMemberParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}
