// Code generated by Scalar SDK Generator. DO NOT EDIT.

package scalargo

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"slices"

	"scalar-go/internal/apijson"
	"scalar-go/internal/param"
	"scalar-go/internal/requestconfig"
	"scalar-go/option"
)

// ThemeService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewThemeService] method instead.
type ThemeService struct {
	Options []option.RequestOption
}

// NewThemeService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewThemeService(opts ...option.RequestOption) (r *ThemeService) {
	r = &ThemeService{}
	r.Options = opts
	return
}

// List all team themes.
//
// Parameters:
//     ctx: Context for the request.
//     opts: Options to apply to this request.
//
// Returns:
//     *[]Theme: Default Response
//
// Example:
//
//     theme, err := client.Themes.List(context.Background())
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(theme)
func (r *ThemeService) List(ctx context.Context, opts ...option.RequestOption) (res *[]Theme, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/themes"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Create a team theme.
//
// Parameters:
//     ctx: Context for the request.
//     body: ThemeNewParams request parameters.
//     opts: Options to apply to this request.
//
// Returns:
//     *ThemeNewResponse: Default Response
//
// Example:
//
//     theme, err := client.Themes.New(context.Background(), sdk.ThemeNewParams{
//     	Document: sdk.F[string](""),
//     	Name: sdk.F[string](""),
//     	Slug: sdk.F[string](""),
//     })
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(theme)
func (r *ThemeService) New(ctx context.Context, body ThemeNewParams, opts ...option.RequestOption) (res *ThemeNewResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "v1/themes"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Update theme metadata.
//
// Parameters:
//     ctx: Context for the request.
//     slug: Path parameter.
//     body: ThemeUpdateParams request parameters.
//     opts: Options to apply to this request.
//
// Returns:
//     *map[string]interface{}: Default Response
//
// Example:
//
//     theme, err := client.Themes.Update(context.Background(), "slug", sdk.ThemeUpdateParams{})
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(theme)
func (r *ThemeService) Update(ctx context.Context, slug string, body ThemeUpdateParams, opts ...option.RequestOption) (res *map[string]interface{}, err error) {
	opts = slices.Concat(r.Options, opts)
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/themes/%s", slug)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPatch, path, body, &res, opts...)
	return res, err
}

// Replace the theme document.
//
// Parameters:
//     ctx: Context for the request.
//     slug: Path parameter.
//     body: ThemeReplaceDocumentParams request parameters.
//     opts: Options to apply to this request.
//
// Returns:
//     *map[string]interface{}: Default Response
//
// Example:
//
//     theme, err := client.Themes.ReplaceDocument(context.Background(), "slug", sdk.ThemeReplaceDocumentParams{
//     	Document: sdk.F[string](""),
//     })
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(theme)
func (r *ThemeService) ReplaceDocument(ctx context.Context, slug string, body ThemeReplaceDocumentParams, opts ...option.RequestOption) (res *map[string]interface{}, err error) {
	opts = slices.Concat(r.Options, opts)
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/themes/%s", slug)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPut, path, body, &res, opts...)
	return res, err
}

// Delete a theme by slug.
//
// Parameters:
//     ctx: Context for the request.
//     slug: Path parameter.
//     opts: Options to apply to this request.
//
// Returns:
//     *map[string]interface{}: Default Response
//
// Example:
//
//     theme, err := client.Themes.Delete(context.Background(), "slug")
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(theme)
func (r *ThemeService) Delete(ctx context.Context, slug string, opts ...option.RequestOption) (res *map[string]interface{}, err error) {
	opts = slices.Concat(r.Options, opts)
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/themes/%s", slug)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, path, nil, &res, opts...)
	return res, err
}

// Get the theme document by slug.
//
// Parameters:
//     ctx: Context for the request.
//     slug: Path parameter.
//     opts: Options to apply to this request.
//
// Returns:
//     *string: Default Response
//
// Example:
//
//     theme, err := client.Themes.Get(context.Background(), "slug")
//     if err != nil {
//     	panic(err)
//     }
//     fmt.Println(theme)
func (r *ThemeService) Get(ctx context.Context, slug string, opts ...option.RequestOption) (res *string, err error) {
	opts = slices.Concat(r.Options, opts)
	opts = append([]option.RequestOption{option.WithHeader("Accept", "text/plain")}, opts...)
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/themes/%s", slug)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

type Theme struct {
	UID string `json:"uid" api:"required"`
	Name string `json:"name" api:"required"`
	Description string `json:"description" api:"required"`
	Slug string `json:"slug" api:"required"`
	JSON themeJSON `json:"-"`
}

// themeJSON contains the JSON metadata for the struct [Theme]
type themeJSON struct {
	UID apijson.Field
	Name apijson.Field
	Description apijson.Field
	Slug apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *Theme) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r themeJSON) RawJSON() string {
	return r.raw
}

type ThemeNewResponse struct {
	UID string `json:"uid" api:"required"`
	JSON themeNewResponseJSON `json:"-"`
}

// themeNewResponseJSON contains the JSON metadata for the struct [ThemeNewResponse]
type themeNewResponseJSON struct {
	UID apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *ThemeNewResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r themeNewResponseJSON) RawJSON() string {
	return r.raw
}

type ThemeNewParams struct {
	Document param.Field[string] `json:"document" api:"required"`
	Name param.Field[string] `json:"name" api:"required"`
	Slug param.Field[string] `json:"slug" api:"required"`
	Description param.Field[string] `json:"description"`
}

func (r ThemeNewParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type ThemeUpdateParams struct {
	Description param.Field[string] `json:"description"`
	Name param.Field[string] `json:"name"`
}

func (r ThemeUpdateParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type ThemeReplaceDocumentParams struct {
	Document param.Field[string] `json:"document" api:"required"`
}

func (r ThemeReplaceDocumentParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}
