// Code generated by Scalar SDK Generator. DO NOT EDIT.

package scalarapi

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"scalar-api/internal/apijson"
	"scalar-api/internal/requestconfig"
	"scalar-api/option"
	"scalar-api/packages/param"
)

// ThemeService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewThemeService] method instead.
type ThemeService struct {
	options []option.RequestOption
}

// NewThemeService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewThemeService(opts ...option.RequestOption) ThemeService {
	s := ThemeService{}
	s.options = opts
	return s
}

// List all team themes.
func (r *ThemeService) List(ctx context.Context, opts ...option.RequestOption) (res *[]Theme, err error) {
	opts = slices.Concat(r.options, opts)
	requestPath := "v1/themes"
	res = new([]Theme)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, requestPath, nil, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

// Create a team theme.
func (r *ThemeService) New(ctx context.Context, body ThemeNewParams, opts ...option.RequestOption) (res *UID, err error) {
	opts = slices.Concat(r.options, opts)
	requestPath := "v1/themes"
	res = new(UID)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, requestPath, body, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type ThemeNewParams struct {
	Document string `json:"document" api:"required"`
	Name string `json:"name" api:"required"`
	Slug string `json:"slug" api:"required"`
	Description param.Opt[string] `json:"description,omitzero"`
	paramObj
}

func (r ThemeNewParams) MarshalJSON() (data []byte, err error) {
	type shadow ThemeNewParams
	return param.MarshalObject(r, (*shadow)(&r))
}
func (r *ThemeNewParams) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Update theme metadata.
func (r *ThemeService) Update(ctx context.Context, slug string, body ThemeUpdateParams, opts ...option.RequestOption) (res *map[string]any, err error) {
	opts = slices.Concat(r.options, opts)
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	requestPath := fmt.Sprintf("v1/themes/%s", url.PathEscape(slug))
	res = new(map[string]any)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPatch, requestPath, body, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type ThemeUpdateParams struct {
	Description param.Opt[string] `json:"description,omitzero"`
	Name param.Opt[string] `json:"name,omitzero"`
	paramObj
}

func (r ThemeUpdateParams) MarshalJSON() (data []byte, err error) {
	type shadow ThemeUpdateParams
	return param.MarshalObject(r, (*shadow)(&r))
}
func (r *ThemeUpdateParams) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Replace the theme document.
func (r *ThemeService) ReplaceDocument(ctx context.Context, slug string, body ThemeReplaceDocumentParams, opts ...option.RequestOption) (res *map[string]any, err error) {
	opts = slices.Concat(r.options, opts)
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	requestPath := fmt.Sprintf("v1/themes/%s", url.PathEscape(slug))
	res = new(map[string]any)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPut, requestPath, body, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

type ThemeReplaceDocumentParams struct {
	Document string `json:"document" api:"required"`
	paramObj
}

func (r ThemeReplaceDocumentParams) MarshalJSON() (data []byte, err error) {
	type shadow ThemeReplaceDocumentParams
	return param.MarshalObject(r, (*shadow)(&r))
}
func (r *ThemeReplaceDocumentParams) UnmarshalJSON(data []byte) error {
	return apijson.UnmarshalRoot(data, r)
}

// Delete a theme by slug.
func (r *ThemeService) Delete(ctx context.Context, slug string, opts ...option.RequestOption) (res *map[string]any, err error) {
	opts = slices.Concat(r.options, opts)
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	requestPath := fmt.Sprintf("v1/themes/%s", url.PathEscape(slug))
	res = new(map[string]any)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodDelete, requestPath, nil, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}

// Get the theme document by slug.
func (r *ThemeService) Get(ctx context.Context, slug string, opts ...option.RequestOption) (res *string, err error) {
	opts = slices.Concat(r.options, opts)
	if slug == "" {
		err = errors.New("missing required slug parameter")
		return nil, err
	}
	requestPath := fmt.Sprintf("v1/themes/%s", url.PathEscape(slug))
	res = new(string)
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, requestPath, nil, &res, opts...)
	if err != nil {
		return nil, err
	}
	return res, nil
}
