// Code generated by Scalar SDK Generator. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"strconv"
	"strings"
	"sync"
	"time"

	sdk "github.com/scalar/scalar-go"
	"github.com/scalar/scalar-go/option"
)

// Smoke test: calls every generated operation once to confirm the SDK can reach each endpoint.
// Run it from this repo with `go run tests/smoke-test.go`. The generator also runs this file
// against a mock server and reads the JSON report produced via SCALAR_SMOKE_REPORT.
var client = sdk.NewClient(option.WithBearerAuth("test"), option.WithOAuth2("test"), option.WithHeader("Authorization", "Bearer test"), option.WithHeader("Authorization", "Bearer test"), option.WithMaxRetries(2), option.WithRequestTimeout(10*time.Second))

type smokeResult struct {
	Operation  string `json:"operation"`
	Method     string `json:"method"`
	Path       string `json:"path"`
	Label      string `json:"label,omitempty"`
	Status     string `json:"status"`
	DurationMs int64  `json:"durationMs"`
	Error      string `json:"error,omitempty"`
}

// Label says which of an operation's two calls this is — "required params" or "all params".
// It is empty when the operation contributed a single case.
type smokeCase struct {
	Operation string
	Method    string
	Path      string
	Label     string
	Run       func()
}

func _smokeCase0() {
	registry, err := client.Registry.ListAllAPIDocuments(context.Background())
	if err != nil {
		panic(err)
	}

	fmt.Println(registry)
}

func _smokeCase1() {
	registry, err := client.Registry.ListAPIDocuments(context.Background(), "acme")
	if err != nil {
		panic(err)
	}

	fmt.Println(registry)
}

func _smokeCase2() {
	registry, err := client.Registry.NewAPIDocument(context.Background(), "acme", sdk.RegistryNewAPIDocumentParams{
		Document: sdk.F[string]("{\"openapi\":\"3.1.0\",\"info\":{\"title\":\"Acme API\",\"version\":\"1.2.0\"},\"paths\":{}}"),
		Slug:     sdk.F[string]("acme-api"),
		Title:    sdk.F[string]("Acme API"),
		Version:  sdk.F[string]("1.2.0"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(registry)
}

func _smokeCase3() {
	registry, err := client.Registry.NewAPIDocument(context.Background(), "acme", sdk.RegistryNewAPIDocumentParams{
		Document:    sdk.F[string]("{\"openapi\":\"3.1.0\",\"info\":{\"title\":\"Acme API\",\"version\":\"1.2.0\"},\"paths\":{}}"),
		Slug:        sdk.F[string]("acme-api"),
		Title:       sdk.F[string]("Acme API"),
		Version:     sdk.F[string]("1.2.0"),
		Description: sdk.F[string]("API for managing Acme products and orders."),
		IsPrivate:   sdk.F[bool](false),
		Ruleset:     sdk.F[string]("extends: [\"spectral:oas\"]"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(registry)
}

func _smokeCase4() {
	registry, err := client.Registry.UpdateAPIDocument(context.Background(), "acme", "acme-api", sdk.RegistryUpdateAPIDocumentParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(registry)
}

func _smokeCase5() {
	registry, err := client.Registry.UpdateAPIDocument(context.Background(), "acme", "acme-api", sdk.RegistryUpdateAPIDocumentParams{
		Description: sdk.F[string]("API for managing Acme products and orders."),
		IsPrivate:   sdk.F[bool](false),
		Ruleset:     sdk.F[string]("extends: [\"spectral:oas\"]"),
		Title:       sdk.F[string]("Acme API"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(registry)
}

func _smokeCase6() {
	registry, err := client.Registry.DeleteAPIDocument(context.Background(), "acme", "acme-api")
	if err != nil {
		panic(err)
	}

	fmt.Println(registry)
}

func _smokeCase7() {
	registry, err := client.Registry.GetAPIDocumentVersion(context.Background(), "acme", "acme-api", "1.2.0")
	if err != nil {
		panic(err)
	}

	fmt.Println(registry)
}

func _smokeCase8() {
	registry, err := client.Registry.UpdateAPIDocumentVersion(context.Background(), "acme", "acme-api", "1.2.0", sdk.RegistryUpdateAPIDocumentVersionParams{
		Document: sdk.F[string]("{\"openapi\":\"3.1.0\",\"info\":{\"title\":\"Acme API\",\"version\":\"1.2.0\"},\"paths\":{}}"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(registry)
}

func _smokeCase9() {
	registry, err := client.Registry.DeleteAPIDocumentVersion(context.Background(), "acme", "acme-api", "1.2.0")
	if err != nil {
		panic(err)
	}

	fmt.Println(registry)
}

func _smokeCase10() {
	registry, err := client.Registry.ListAPIDocumentVersionMetadata(context.Background(), "acme", "acme-api", "1.2.0")
	if err != nil {
		panic(err)
	}

	fmt.Println(registry)
}

func _smokeCase11() {
	registry, err := client.Registry.NewAPIDocumentVersion(context.Background(), "acme", "acme-api", sdk.RegistryNewAPIDocumentVersionParams{
		Document: sdk.F[string]("{\"openapi\":\"3.1.0\",\"info\":{\"title\":\"Acme API\",\"version\":\"1.2.0\"},\"paths\":{}}"),
		Version:  sdk.F[string]("1.2.0"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(registry)
}

func _smokeCase12() {
	registry, err := client.Registry.NewAPIDocumentVersion(context.Background(), "acme", "acme-api", sdk.RegistryNewAPIDocumentVersionParams{
		Document: sdk.F[string]("{\"openapi\":\"3.1.0\",\"info\":{\"title\":\"Acme API\",\"version\":\"1.2.0\"},\"paths\":{}}"),
		Version:  sdk.F[string]("1.2.0"),
		Force:    sdk.F[bool](false),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(registry)
}

func _smokeCase13() {
	registry, err := client.Registry.NewAPIDocumentAccessGroup(context.Background(), "acme", "acme-api", sdk.RegistryNewAPIDocumentAccessGroupParams{
		AccessGroup: sdk.AccessGroupParam{
			AccessGroupSlug: sdk.F[string]("acme-api"),
		},
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(registry)
}

func _smokeCase14() {
	registry, err := client.Registry.DeleteAPIDocumentAccessGroup(context.Background(), "acme", "acme-api", sdk.RegistryDeleteAPIDocumentAccessGroupParams{
		AccessGroup: sdk.AccessGroupParam{
			AccessGroupSlug: sdk.F[string]("acme-api"),
		},
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(registry)
}

func _smokeCase15() {
	schema, err := client.Schemas.List(context.Background(), "acme")
	if err != nil {
		panic(err)
	}

	fmt.Println(schema)
}

func _smokeCase16() {
	schema, err := client.Schemas.New(context.Background(), "acme", sdk.SchemaNewParams{
		Document: sdk.F[string]("{\"type\":\"object\",\"properties\":{\"name\":{\"type\":\"string\",\"examples\":[\"Acme\"]}}}"),
		Slug:     sdk.F[string]("customer"),
		Title:    sdk.F[string]("Customer"),
		Version:  sdk.F[string]("1.2.0"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(schema)
}

func _smokeCase17() {
	schema, err := client.Schemas.New(context.Background(), "acme", sdk.SchemaNewParams{
		Document:    sdk.F[string]("{\"type\":\"object\",\"properties\":{\"name\":{\"type\":\"string\",\"examples\":[\"Acme\"]}}}"),
		Slug:        sdk.F[string]("customer"),
		Title:       sdk.F[string]("Customer"),
		Version:     sdk.F[string]("1.2.0"),
		Description: sdk.F[string]("API for managing Acme products and orders."),
		IsPrivate:   sdk.F[bool](false),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(schema)
}

func _smokeCase18() {
	schema, err := client.Schemas.Update(context.Background(), "acme", "customer", sdk.SchemaUpdateParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(schema)
}

func _smokeCase19() {
	schema, err := client.Schemas.Update(context.Background(), "acme", "customer", sdk.SchemaUpdateParams{
		Description: sdk.F[string]("API for managing Acme products and orders."),
		IsPrivate:   sdk.F[bool](false),
		Title:       sdk.F[string]("Customer"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(schema)
}

func _smokeCase20() {
	schema, err := client.Schemas.Delete(context.Background(), "acme", "customer")
	if err != nil {
		panic(err)
	}

	fmt.Println(schema)
}

func _smokeCase21() {
	version, err := client.Schemas.Version.Get(context.Background(), "acme", "customer", "1.2.0")
	if err != nil {
		panic(err)
	}

	fmt.Println(version)
}

func _smokeCase22() {
	version, err := client.Schemas.Version.Delete(context.Background(), "acme", "customer", "1.2.0")
	if err != nil {
		panic(err)
	}

	fmt.Println(version)
}

func _smokeCase23() {
	version, err := client.Schemas.Version.New(context.Background(), "acme", "customer", sdk.SchemaVersionNewParams{
		Document: sdk.F[string]("{\"type\":\"object\",\"properties\":{\"name\":{\"type\":\"string\",\"examples\":[\"Acme\"]}}}"),
		Version:  sdk.F[string]("1.2.0"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(version)
}

func _smokeCase24() {
	version, err := client.Schemas.Version.New(context.Background(), "acme", "customer", sdk.SchemaVersionNewParams{
		Document: sdk.F[string]("{\"type\":\"object\",\"properties\":{\"name\":{\"type\":\"string\",\"examples\":[\"Acme\"]}}}"),
		Version:  sdk.F[string]("1.2.0"),
		Force:    sdk.F[bool](false),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(version)
}

func _smokeCase25() {
	accessGroup, err := client.Schemas.AccessGroup.New(context.Background(), "acme", "customer", sdk.SchemaAccessGroupNewParams{
		AccessGroup: sdk.AccessGroupParam{
			AccessGroupSlug: sdk.F[string]("acme-api"),
		},
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(accessGroup)
}

func _smokeCase26() {
	accessGroup, err := client.Schemas.AccessGroup.Delete(context.Background(), "acme", "customer", sdk.SchemaAccessGroupDeleteParams{
		AccessGroup: sdk.AccessGroupParam{
			AccessGroupSlug: sdk.F[string]("acme-api"),
		},
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(accessGroup)
}

func _smokeCase27() {
	loginPortal, err := client.LoginPortals.Get(context.Background(), "acme-login")
	if err != nil {
		panic(err)
	}

	fmt.Println(loginPortal)
}

func _smokeCase28() {
	loginPortal, err := client.LoginPortals.Update(context.Background(), "acme-login", sdk.LoginPortalUpdateParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(loginPortal)
}

func _smokeCase29() {
	loginPortal, err := client.LoginPortals.Update(context.Background(), "acme-login", sdk.LoginPortalUpdateParams{
		Title: sdk.F[string]("Acme Private Documentation"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(loginPortal)
}

func _smokeCase30() {
	loginPortal, err := client.LoginPortals.Delete(context.Background(), "acme-login")
	if err != nil {
		panic(err)
	}

	fmt.Println(loginPortal)
}

func _smokeCase31() {
	loginPortal, err := client.LoginPortals.New(context.Background(), sdk.LoginPortalNewParams{
		Email: sdk.F[sdk.LoginPortalEmailParam](sdk.LoginPortalEmailParam{
			Logo:             sdk.F[string](""),
			LogoSize:         sdk.F[string]("100"),
			ButtonText:       sdk.F[string]("Login"),
			Message:          sdk.F[string]("Click to access private documentation hosted by scalar.com"),
			Title:            sdk.F[string]("Private Docs"),
			MainColor:        sdk.F[string]("#2a2f45"),
			MainBackground:   sdk.F[string]("#f6f6f6"),
			CardColor:        sdk.F[string]("#2a2f45"),
			CardBackground:   sdk.F[string]("#fff"),
			ButtonColor:      sdk.F[string]("#fff"),
			ButtonBackground: sdk.F[string]("#0f0f0f"),
		}),
		Page: sdk.F[sdk.LoginPortalPageParam](sdk.LoginPortalPageParam{
			Title:           sdk.F[string]("Scalar Private Docs"),
			Description:     sdk.F[string]("Login to access your documentation"),
			Head:            sdk.F[string](""),
			Script:          sdk.F[string](""),
			Theme:           sdk.F[string](""),
			CompanyName:     sdk.F[string](""),
			Logo:            sdk.F[string](""),
			LogoURL:         sdk.F[string](""),
			Favicon:         sdk.F[string](""),
			TermsLink:       sdk.F[string](""),
			PrivacyLink:     sdk.F[string](""),
			FormTitle:       sdk.F[string]("Scalar Private Docs"),
			FormDescription: sdk.F[string]("Login to access your documentation"),
			FormImage:       sdk.F[string](""),
		}),
		Slug:  sdk.F[string]("acme-login"),
		Title: sdk.F[string]("Acme Private Documentation"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(loginPortal)
}

func _smokeCase32() {
	loginPortal, err := client.LoginPortals.List(context.Background())
	if err != nil {
		panic(err)
	}

	fmt.Println(loginPortal)
}

func _smokeCase33() {
	accessGroup, err := client.AccessGroups.New(context.Background(), sdk.AccessGroupNewParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(accessGroup)
}

func _smokeCase34() {
	accessGroup, err := client.AccessGroups.New(context.Background(), sdk.AccessGroupNewParams{
		AllowedDomains: sdk.F[string]("example.com"),
		Name:           sdk.F[string]("Engineering"),
		Slug:           sdk.F[string]("engineering"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(accessGroup)
}

func _smokeCase35() {
	accessGroup, err := client.AccessGroups.Get(context.Background(), "acme-api")
	if err != nil {
		panic(err)
	}

	fmt.Println(accessGroup)
}

func _smokeCase36() {
	accessGroup, err := client.AccessGroups.Update(context.Background(), "acme-api", sdk.AccessGroupUpdateParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(accessGroup)
}

func _smokeCase37() {
	accessGroup, err := client.AccessGroups.Update(context.Background(), "acme-api", sdk.AccessGroupUpdateParams{
		Name: sdk.F[string]("Engineering"),
		Slug: sdk.F[string]("engineering"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(accessGroup)
}

func _smokeCase38() {
	accessGroup, err := client.AccessGroups.Delete(context.Background(), "acme-api")
	if err != nil {
		panic(err)
	}

	fmt.Println(accessGroup)
}

func _smokeCase39() {
	domain, err := client.AccessGroups.Domains.New(context.Background(), "acme-api", sdk.AccessGroupDomainNewParams{
		Domain: sdk.F[string]("example.com"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(domain)
}

func _smokeCase40() {
	domain, err := client.AccessGroups.Domains.Delete(context.Background(), "acme-api", sdk.AccessGroupDomainDeleteParams{
		Domain: sdk.F[string]("example.com"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(domain)
}

func _smokeCase41() {
	rule, err := client.Rules.ListRulesets(context.Background(), "acme")
	if err != nil {
		panic(err)
	}

	fmt.Println(rule)
}

func _smokeCase42() {
	rule, err := client.Rules.NewRuleset(context.Background(), "acme", sdk.RuleNewRulesetParams{
		Document: sdk.F[string]("extends: [\"spectral:oas\"]\nrules:\n  info-contact: warn\n"),
		Slug:     sdk.F[string]("acme-rules"),
		Title:    sdk.F[string]("Acme API Rules"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(rule)
}

func _smokeCase43() {
	rule, err := client.Rules.NewRuleset(context.Background(), "acme", sdk.RuleNewRulesetParams{
		Document:    sdk.F[string]("extends: [\"spectral:oas\"]\nrules:\n  info-contact: warn\n"),
		Slug:        sdk.F[string]("acme-rules"),
		Title:       sdk.F[string]("Acme API Rules"),
		Description: sdk.F[string]("API for managing Acme products and orders."),
		IsPrivate:   sdk.F[bool](false),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(rule)
}

func _smokeCase44() {
	rule, err := client.Rules.UpdateRuleset(context.Background(), "acme", "acme-rules", sdk.RuleUpdateRulesetParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(rule)
}

func _smokeCase45() {
	rule, err := client.Rules.UpdateRuleset(context.Background(), "acme", "acme-rules", sdk.RuleUpdateRulesetParams{
		Description: sdk.F[string]("API for managing Acme products and orders."),
		IsPrivate:   sdk.F[bool](false),
		Namespace:   sdk.F[string]("acme"),
		Slug:        sdk.F[string]("acme-rules"),
		Title:       sdk.F[string]("Acme API Rules"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(rule)
}

func _smokeCase46() {
	rule, err := client.Rules.DeleteRuleset(context.Background(), "acme", "acme-rules")
	if err != nil {
		panic(err)
	}

	fmt.Println(rule)
}

func _smokeCase47() {
	rule, err := client.Rules.GetRulesetDocument(context.Background(), "acme", "acme-rules")
	if err != nil {
		panic(err)
	}

	fmt.Println(rule)
}

func _smokeCase48() {
	rule, err := client.Rules.NewRulesetAccessGroup(context.Background(), "acme", "acme-rules", sdk.RuleNewRulesetAccessGroupParams{
		AccessGroup: sdk.AccessGroupParam{
			AccessGroupSlug: sdk.F[string]("acme-api"),
		},
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(rule)
}

func _smokeCase49() {
	rule, err := client.Rules.DeleteRulesetAccessGroup(context.Background(), "acme", "acme-rules", sdk.RuleDeleteRulesetAccessGroupParams{
		AccessGroup: sdk.AccessGroupParam{
			AccessGroupSlug: sdk.F[string]("acme-api"),
		},
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(rule)
}

func _smokeCase50() {
	theme, err := client.Themes.List(context.Background())
	if err != nil {
		panic(err)
	}

	fmt.Println(theme)
}

func _smokeCase51() {
	theme, err := client.Themes.New(context.Background(), sdk.ThemeNewParams{
		Document: sdk.F[string](":root { --scalar-color-1: #1f2937; }"),
		Name:     sdk.F[string]("Acme Theme"),
		Slug:     sdk.F[string]("acme-theme"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(theme)
}

func _smokeCase52() {
	theme, err := client.Themes.New(context.Background(), sdk.ThemeNewParams{
		Document:    sdk.F[string](":root { --scalar-color-1: #1f2937; }"),
		Name:        sdk.F[string]("Acme Theme"),
		Slug:        sdk.F[string]("acme-theme"),
		Description: sdk.F[string]("API for managing Acme products and orders."),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(theme)
}

func _smokeCase53() {
	theme, err := client.Themes.Update(context.Background(), "acme-theme", sdk.ThemeUpdateParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(theme)
}

func _smokeCase54() {
	theme, err := client.Themes.Update(context.Background(), "acme-theme", sdk.ThemeUpdateParams{
		Description: sdk.F[string]("API for managing Acme products and orders."),
		Name:        sdk.F[string]("Acme Theme"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(theme)
}

func _smokeCase55() {
	theme, err := client.Themes.ReplaceDocument(context.Background(), "acme-theme", sdk.ThemeReplaceDocumentParams{
		Document: sdk.F[string](":root { --scalar-color-1: #1f2937; }"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(theme)
}

func _smokeCase56() {
	theme, err := client.Themes.Delete(context.Background(), "acme-theme")
	if err != nil {
		panic(err)
	}

	fmt.Println(theme)
}

func _smokeCase57() {
	theme, err := client.Themes.Get(context.Background(), "acme-theme")
	if err != nil {
		panic(err)
	}

	fmt.Println(theme)
}

func _smokeCase58() {
	team, err := client.Teams.List(context.Background())
	if err != nil {
		panic(err)
	}

	fmt.Println(team)
}

func _smokeCase59() {
	member, err := client.Teams.Members.List(context.Background())
	if err != nil {
		panic(err)
	}

	fmt.Println(member)
}

func _smokeCase60() {
	member, err := client.Teams.Members.Update(context.Background(), "UakgbKJ5m9gl0JDMbcJqL", sdk.TeamMemberUpdateParams{
		Role: sdk.F[sdk.Role](sdk.Role("owner")),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(member)
}

func _smokeCase61() {
	member, err := client.Teams.Members.Delete(context.Background(), "UakgbKJ5m9gl0JDMbcJqL")
	if err != nil {
		panic(err)
	}

	fmt.Println(member)
}

func _smokeCase62() {
	invite, err := client.Teams.Invites.Member(context.Background(), sdk.TeamInviteMemberParams{
		Email: sdk.F[string]("alex@example.com"),
		Role:  sdk.F[sdk.Role](sdk.Role("owner")),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(invite)
}

func _smokeCase63() {
	invite, err := client.Teams.Invites.Resend(context.Background(), "UakgbKJ5m9gl0JDMbcJqL")
	if err != nil {
		panic(err)
	}

	fmt.Println(invite)
}

func _smokeCase64() {
	invite, err := client.Teams.Invites.Cancel(context.Background(), "UakgbKJ5m9gl0JDMbcJqL")
	if err != nil {
		panic(err)
	}

	fmt.Println(invite)
}

func _smokeCase65() {
	scalarDoc, err := client.ScalarDocs.ListGuides(context.Background())
	if err != nil {
		panic(err)
	}

	fmt.Println(scalarDoc)
}

func _smokeCase66() {
	scalarDoc, err := client.ScalarDocs.NewGuide(context.Background(), sdk.ScalarDocNewGuideParams{
		AllowedDomains: sdk.F[[]string]([]string{}),
		AllowedUsers:   sdk.F[[]string]([]string{}),
		IsPrivate:      sdk.F[bool](false),
		Name:           sdk.F[string]("Acme Documentation"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(scalarDoc)
}

func _smokeCase67() {
	scalarDoc, err := client.ScalarDocs.NewGuide(context.Background(), sdk.ScalarDocNewGuideParams{
		AllowedDomains: sdk.F[[]string]([]string{}),
		AllowedUsers:   sdk.F[[]string]([]string{}),
		IsPrivate:      sdk.F[bool](false),
		Name:           sdk.F[string]("Acme Documentation"),
		Slug:           sdk.F[string]("acme-docs"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(scalarDoc)
}

func _smokeCase68() {
	scalarDoc, err := client.ScalarDocs.PublishGuide(context.Background(), "acme-docs")
	if err != nil {
		panic(err)
	}

	fmt.Println(scalarDoc)
}

func _smokeCase69() {
	scalarDoc, err := client.ScalarDocs.ListProjects(context.Background(), sdk.ScalarDocListProjectsParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(scalarDoc)
}

func _smokeCase70() {
	scalarDoc, err := client.ScalarDocs.ListProjects(context.Background(), sdk.ScalarDocListProjectsParams{
		Limit: sdk.F[int64](20),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(scalarDoc)
}

func _smokeCase71() {
	scalarDoc, err := client.ScalarDocs.NewProject(context.Background(), sdk.ScalarDocNewProjectParams{
		Name:     sdk.F[string]("Acme Documentation"),
		Provider: sdk.F[sdk.ScalarDocNewProjectParamsProvider](sdk.ScalarDocNewProjectParamsProvider("forgejo")),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(scalarDoc)
}

func _smokeCase72() {
	scalarDoc, err := client.ScalarDocs.NewProject(context.Background(), sdk.ScalarDocNewProjectParams{
		Name:     sdk.F[string]("Acme Documentation"),
		Provider: sdk.F[sdk.ScalarDocNewProjectParamsProvider](sdk.ScalarDocNewProjectParamsProvider("forgejo")),
		BitbucketRepository: sdk.F[sdk.ScalarDocNewProjectParamsBitbucketRepository](sdk.ScalarDocNewProjectParamsBitbucketRepository{
			WorkspaceUUID: sdk.F[string]("{12345678-1234-4234-8234-123456789abc}"),
			RepoUUID:      sdk.F[string]("{abcdef01-1234-4234-8234-123456789abc}"),
		}),
		Blank: sdk.F[bool](true),
		GithubRepository: sdk.F[sdk.ScalarDocNewProjectParamsGithubRepository](sdk.ScalarDocNewProjectParamsGithubRepository{
			InstallationID: sdk.F[int64](84),
			RepoID:         sdk.F[int64](123456789),
		}),
		IsPrivate: sdk.F[bool](false),
		Slug:      sdk.F[string]("acme-docs"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(scalarDoc)
}

func _smokeCase73() {
	scalarDoc, err := client.ScalarDocs.GetProject(context.Background(), "acme-docs")
	if err != nil {
		panic(err)
	}

	fmt.Println(scalarDoc)
}

func _smokeCase74() {
	scalarDoc, err := client.ScalarDocs.UpdateProject(context.Background(), "acme-docs", sdk.ScalarDocUpdateProjectParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(scalarDoc)
}

func _smokeCase75() {
	scalarDoc, err := client.ScalarDocs.UpdateProject(context.Background(), "acme-docs", sdk.ScalarDocUpdateProjectParams{
		AccessGroups:     sdk.F[[]string]([]string{"UakgbKJ5m9gl0JDMbcJqL"}),
		ActiveThemeID:    sdk.F[string]("TakgbKJ5m9gl0JDMbcJqL"),
		AgentEnabled:     sdk.F[bool](true),
		AnalyticsEnabled: sdk.F[bool](true),
		IsPrivate:        sdk.F[bool](false),
		LoginPortalUID:   sdk.F[interface{}]("LakgbKJ5m9gl0JDMbcJqL"),
		Name:             sdk.F[string]("Acme Documentation"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(scalarDoc)
}

func _smokeCase76() {
	scalarDoc, err := client.ScalarDocs.DeleteProject(context.Background(), "acme-docs")
	if err != nil {
		panic(err)
	}

	fmt.Println(scalarDoc)
}

func _smokeCase77() {
	scalarDoc, err := client.ScalarDocs.PublishProject(context.Background(), "acme-docs", sdk.ScalarDocPublishProjectParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(scalarDoc)
}

func _smokeCase78() {
	scalarDoc, err := client.ScalarDocs.PublishProject(context.Background(), "acme-docs", sdk.ScalarDocPublishProjectParams{
		CommitSha:  sdk.F[string]("0123456789abcdef0123456789abcdef01234567"),
		ConfigPath: sdk.F[string]("scalar.config.json"),
		Preview:    sdk.F[bool](false),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(scalarDoc)
}

func _smokeCase79() {
	scalarDoc, err := client.ScalarDocs.ListProjectConfig(context.Background(), "acme-docs", sdk.ScalarDocListProjectConfigParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(scalarDoc)
}

func _smokeCase80() {
	scalarDoc, err := client.ScalarDocs.ListProjectConfig(context.Background(), "acme-docs", sdk.ScalarDocListProjectConfigParams{
		Ref: sdk.F[string]("main"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(scalarDoc)
}

func _smokeCase81() {
	scalarDoc, err := client.ScalarDocs.UpdateProjectConfig(context.Background(), "acme-docs", sdk.ScalarDocUpdateProjectConfigParams{
		Content: sdk.F[string]("{\"name\":\"Acme Documentation\"}"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(scalarDoc)
}

func _smokeCase82() {
	scalarDoc, err := client.ScalarDocs.UpdateProjectConfig(context.Background(), "acme-docs", sdk.ScalarDocUpdateProjectConfigParams{
		Content:   sdk.F[string]("{\"name\":\"Acme Documentation\"}"),
		BaseToken: sdk.F[string]("example-edit-token"),
		Message:   sdk.F[string]("Update documentation configuration"),
		Path:      sdk.F[string]("scalar.config.json"),
		Ref:       sdk.F[string]("main"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(scalarDoc)
}

func _smokeCase83() {
	scalarDoc, err := client.ScalarDocs.ListProjectDomain(context.Background(), "acme-docs")
	if err != nil {
		panic(err)
	}

	fmt.Println(scalarDoc)
}

func _smokeCase84() {
	scalarDoc, err := client.ScalarDocs.ListProjectDomainStatus(context.Background(), "acme-docs")
	if err != nil {
		panic(err)
	}

	fmt.Println(scalarDoc)
}

func _smokeCase85() {
	namespace, err := client.Namespaces.List(context.Background())
	if err != nil {
		panic(err)
	}

	fmt.Println(namespace)
}

func _smokeCase86() {
	authentication, err := client.Authentication.ExchangePersonalToken(context.Background(), sdk.AuthenticationExchangePersonalTokenParams{
		PersonalToken: sdk.F[string]("scalar_example_personal_token"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(authentication)
}

func _smokeCase87() {
	authentication, err := client.Authentication.ListCurrentUser(context.Background())
	if err != nil {
		panic(err)
	}

	fmt.Println(authentication)
}

func _smokeCase88() {
	sdk, err := client.Sdks.List(context.Background(), sdk.SdkListParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(sdk)
}

func _smokeCase89() {
	sdk, err := client.Sdks.List(context.Background(), sdk.SdkListParams{
		Limit: sdk.F[int64](20),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(sdk)
}

func _smokeCase90() {
	sdk, err := client.Sdks.New(context.Background(), sdk.SdkNewParams{
		APIUID:    sdk.F[string]("UakgbKJ5m9gl0JDMbcJqL"),
		Languages: sdk.F[[]sdk.SdkNewParamsLanguage]([]sdk.SdkNewParamsLanguage{"typescript"}),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(sdk)
}

func _smokeCase91() {
	sdk, err := client.Sdks.New(context.Background(), sdk.SdkNewParams{
		APIUID:    sdk.F[string]("UakgbKJ5m9gl0JDMbcJqL"),
		Languages: sdk.F[[]sdk.SdkNewParamsLanguage]([]sdk.SdkNewParamsLanguage{"typescript"}),
		ClassName: sdk.F[string]("Acme"),
		Config:    sdk.F[string]("{\"targets\":{\"typescript\":{\"packageName\":\"@acme/sdk\"}}}"),
		Slug:      sdk.F[string]("acme-sdk"),
		Title:     sdk.F[string]("Acme SDK"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(sdk)
}

func _smokeCase92() {
	sdk, err := client.Sdks.Get(context.Background(), "UakgbKJ5m9gl0JDMbcJqL")
	if err != nil {
		panic(err)
	}

	fmt.Println(sdk)
}

func _smokeCase93() {
	sdk, err := client.Sdks.Update(context.Background(), "UakgbKJ5m9gl0JDMbcJqL", sdk.SdkUpdateParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(sdk)
}

func _smokeCase94() {
	sdk, err := client.Sdks.Update(context.Background(), "UakgbKJ5m9gl0JDMbcJqL", sdk.SdkUpdateParams{
		APIUID:     sdk.F[string]("UakgbKJ5m9gl0JDMbcJqL"),
		APIVersion: sdk.F[string]("1.2.0"),
		Config:     sdk.F[string]("{\"targets\":{\"typescript\":{\"packageName\":\"@acme/sdk\"}}}"),
		IsPrivate:  sdk.F[bool](false),
		Slug:       sdk.F[string]("acme-sdk"),
		Title:      sdk.F[string]("Acme SDK"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(sdk)
}

func _smokeCase95() {
	sdk, err := client.Sdks.Delete(context.Background(), "UakgbKJ5m9gl0JDMbcJqL")
	if err != nil {
		panic(err)
	}

	fmt.Println(sdk)
}

func _smokeCase96() {
	sdk, err := client.Sdks.Build(context.Background(), "UakgbKJ5m9gl0JDMbcJqL", sdk.SdkBuildParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(sdk)
}

func _smokeCase97() {
	sdk, err := client.Sdks.Build(context.Background(), "UakgbKJ5m9gl0JDMbcJqL", sdk.SdkBuildParams{
		Languages: sdk.F[[]sdk.SdkBuildParamsLanguage]([]sdk.SdkBuildParamsLanguage{"typescript"}),
		Version:   sdk.F[string]("1.2.0"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(sdk)
}

func _smokeCase98() {
	version, err := client.Sdks.Versions.New(context.Background(), "UakgbKJ5m9gl0JDMbcJqL", sdk.SdkVersionNewParams{
		APIVersion: sdk.F[string]("1.2.0"),
		Version:    sdk.F[string]("1.2.0"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(version)
}

func _smokeCase99() {
	version, err := client.Sdks.Versions.Delete(context.Background(), "UakgbKJ5m9gl0JDMbcJqL", "1.2.0")
	if err != nil {
		panic(err)
	}

	fmt.Println(version)
}

func _smokeCase100() {
	repository, err := client.Sdks.Repositories.Link(context.Background(), "UakgbKJ5m9gl0JDMbcJqL", sdk.SdkRepositoryLinkParams{
		BaseBranch:   sdk.F[string]("main"),
		Language:     sdk.F[sdk.SdkRepositoryLinkParamsLanguage](sdk.SdkRepositoryLinkParamsLanguage("typescript")),
		RepositoryID: sdk.F[int64](123456789),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(repository)
}

func _smokeCase101() {
	repository, err := client.Sdks.Repositories.Link(context.Background(), "UakgbKJ5m9gl0JDMbcJqL", sdk.SdkRepositoryLinkParams{
		BaseBranch:     sdk.F[string]("main"),
		Language:       sdk.F[sdk.SdkRepositoryLinkParamsLanguage](sdk.SdkRepositoryLinkParamsLanguage("typescript")),
		RepositoryID:   sdk.F[int64](123456789),
		PrereleaseType: sdk.F[string]("beta"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(repository)
}

func _smokeCase102() {
	repository, err := client.Sdks.Repositories.Unlink(context.Background(), "UakgbKJ5m9gl0JDMbcJqL", "typescript")
	if err != nil {
		panic(err)
	}

	fmt.Println(repository)
}

func _smokeCase103() {
	repository, err := client.Sdks.Repositories.UpdatePublishing(context.Background(), "UakgbKJ5m9gl0JDMbcJqL", "typescript", sdk.SdkRepositoryUpdatePublishingParams{
		PublishOnMerge: sdk.F[bool](true),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(repository)
}

func _smokeCase104() {
	repository, err := client.Sdks.Repositories.UpdatePublishing(context.Background(), "UakgbKJ5m9gl0JDMbcJqL", "typescript", sdk.SdkRepositoryUpdatePublishingParams{
		PublishOnMerge: sdk.F[bool](true),
		Access:         sdk.F[sdk.SdkRepositoryUpdatePublishingParamsAccess](sdk.SdkRepositoryUpdatePublishingParamsAccess("public")),
		AuthMethod:     sdk.F[sdk.SdkRepositoryUpdatePublishingParamsAuthMethod](sdk.SdkRepositoryUpdatePublishingParamsAuthMethod("oidc")),
		Tag:            sdk.F[string]("latest"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(repository)
}

func _smokeCase105() {
	server, err := client.Mcp.Servers.List(context.Background())
	if err != nil {
		panic(err)
	}

	fmt.Println(server)
}

func _smokeCase106() {
	server, err := client.Mcp.Servers.New(context.Background(), sdk.McpServerNewParams{
		Name: sdk.F[string]("Acme MCP"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(server)
}

func _smokeCase107() {
	server, err := client.Mcp.Servers.New(context.Background(), sdk.McpServerNewParams{
		Name:        sdk.F[string]("Acme MCP"),
		ProjectUIDs: sdk.F[[]string]([]string{"PakgbKJ5m9gl0JDMbcJqL"}),
		Slug:        sdk.F[string]("acme-mcp"),
		VersionUIDs: sdk.F[[]string]([]string{"VakgbKJ5m9gl0JDMbcJqL"}),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(server)
}

func _smokeCase108() {
	server, err := client.Mcp.Servers.Get(context.Background(), "42")
	if err != nil {
		panic(err)
	}

	fmt.Println(server)
}

func _smokeCase109() {
	server, err := client.Mcp.Servers.Update(context.Background(), "42", sdk.McpServerUpdateParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(server)
}

func _smokeCase110() {
	server, err := client.Mcp.Servers.Update(context.Background(), "42", sdk.McpServerUpdateParams{
		AutoAddOperations: sdk.F[bool](true),
		DocsPages:         sdk.F[[]string]([]string{"getting-started"}),
		Name:              sdk.F[string]("Acme MCP"),
		Operations:        sdk.F[[]string]([]string{"42"}),
		Slug:              sdk.F[string]("acme-mcp"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(server)
}

func _smokeCase111() {
	server, err := client.Mcp.Servers.Delete(context.Background(), "42")
	if err != nil {
		panic(err)
	}

	fmt.Println(server)
}

func _smokeCase112() {
	installation, err := client.Mcp.Servers.Installations.List(context.Background(), "42")
	if err != nil {
		panic(err)
	}

	fmt.Println(installation)
}

func _smokeCase113() {
	installation, err := client.Mcp.Servers.Installations.New(context.Background(), "42", sdk.McpServerInstallationNewParams{
		DocumentAuth: sdk.F[map[string]interface{}](map[string]interface{}{}),
		Name:         sdk.F[string]("Acme MCP"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(installation)
}

func _smokeCase114() {
	installation, err := client.Mcp.Servers.Installations.New(context.Background(), "42", sdk.McpServerInstallationNewParams{
		DocumentAuth: sdk.F[map[string]interface{}](map[string]interface{}{}),
		Name:         sdk.F[string]("Acme MCP"),
		Slug:         sdk.F[string]("acme-mcp"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(installation)
}

func _smokeCase115() {
	installation, err := client.Mcp.Servers.Installations.Get(context.Background(), "42", "84")
	if err != nil {
		panic(err)
	}

	fmt.Println(installation)
}

func _smokeCase116() {
	installation, err := client.Mcp.Servers.Installations.Update(context.Background(), "42", "84", sdk.McpServerInstallationUpdateParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(installation)
}

func _smokeCase117() {
	installation, err := client.Mcp.Servers.Installations.Update(context.Background(), "42", "84", sdk.McpServerInstallationUpdateParams{
		DocumentAuth:   sdk.F[map[string]interface{}](map[string]interface{}{}),
		IsPrivate:      sdk.F[bool](false),
		LoginPortalUID: sdk.F[string]("LakgbKJ5m9gl0JDMbcJqL"),
		McpVersion:     sdk.F[string]("1.2.0"),
		Name:           sdk.F[string]("Acme MCP"),
		Slug:           sdk.F[string]("acme-mcp"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(installation)
}

func _smokeCase118() {
	installation, err := client.Mcp.Servers.Installations.Delete(context.Background(), "42", "84")
	if err != nil {
		panic(err)
	}

	fmt.Println(installation)
}

func _smokeCase119() {
	installation, err := client.Mcp.Servers.Installations.NewAccessGroup(context.Background(), "42", "84", sdk.McpServerInstallationNewAccessGroupParams{
		AccessGroupUID: sdk.F[string]("UakgbKJ5m9gl0JDMbcJqL"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(installation)
}

func _smokeCase120() {
	installation, err := client.Mcp.Servers.Installations.DeleteAccessGroup(context.Background(), "42", "84", sdk.McpServerInstallationDeleteAccessGroupParams{
		AccessGroupUID: sdk.F[string]("UakgbKJ5m9gl0JDMbcJqL"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(installation)
}

var cases = []smokeCase{
	{
		Operation: "listAllApiDocuments",
		Method:    "GET",
		Path:      "/v1/apis",
		Run:       _smokeCase0,
	},

	{
		Operation: "listApiDocuments",
		Method:    "GET",
		Path:      "/v1/apis/{namespace}",
		Run:       _smokeCase1,
	},

	{
		Operation: "createApiDocument",
		Method:    "POST",
		Path:      "/v1/apis/{namespace}",
		Label:     "required params",
		Run:       _smokeCase2,
	},

	{
		Operation: "createApiDocument",
		Method:    "POST",
		Path:      "/v1/apis/{namespace}",
		Label:     "all params",
		Run:       _smokeCase3,
	},

	{
		Operation: "updateApiDocument",
		Method:    "PATCH",
		Path:      "/v1/apis/{namespace}/{slug}",
		Label:     "required params",
		Run:       _smokeCase4,
	},

	{
		Operation: "updateApiDocument",
		Method:    "PATCH",
		Path:      "/v1/apis/{namespace}/{slug}",
		Label:     "all params",
		Run:       _smokeCase5,
	},

	{
		Operation: "deleteApiDocument",
		Method:    "DELETE",
		Path:      "/v1/apis/{namespace}/{slug}",
		Run:       _smokeCase6,
	},

	{
		Operation: "retrieveApiDocumentVersion",
		Method:    "GET",
		Path:      "/v1/apis/{namespace}/{slug}/version/{semver}",
		Run:       _smokeCase7,
	},

	{
		Operation: "updateApiDocumentVersion",
		Method:    "PATCH",
		Path:      "/v1/apis/{namespace}/{slug}/version/{semver}",
		Run:       _smokeCase8,
	},

	{
		Operation: "deleteApiDocumentVersion",
		Method:    "DELETE",
		Path:      "/v1/apis/{namespace}/{slug}/version/{semver}",
		Run:       _smokeCase9,
	},

	{
		Operation: "listApiDocumentVersionMetadata",
		Method:    "GET",
		Path:      "/v1/apis/{namespace}/{slug}/version/{semver}/metadata",
		Run:       _smokeCase10,
	},

	{
		Operation: "createApiDocumentVersion",
		Method:    "POST",
		Path:      "/v1/apis/{namespace}/{slug}/version",
		Label:     "required params",
		Run:       _smokeCase11,
	},

	{
		Operation: "createApiDocumentVersion",
		Method:    "POST",
		Path:      "/v1/apis/{namespace}/{slug}/version",
		Label:     "all params",
		Run:       _smokeCase12,
	},

	{
		Operation: "createApiDocumentAccessGroup",
		Method:    "POST",
		Path:      "/v1/apis/{namespace}/{slug}/access-group",
		Run:       _smokeCase13,
	},

	{
		Operation: "deleteApiDocumentAccessGroup",
		Method:    "DELETE",
		Path:      "/v1/apis/{namespace}/{slug}/access-group",
		Run:       _smokeCase14,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/schemas/{namespace}",
		Run:       _smokeCase15,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/schemas/{namespace}",
		Label:     "required params",
		Run:       _smokeCase16,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/schemas/{namespace}",
		Label:     "all params",
		Run:       _smokeCase17,
	},

	{
		Operation: "update",
		Method:    "PATCH",
		Path:      "/v1/schemas/{namespace}/{slug}",
		Label:     "required params",
		Run:       _smokeCase18,
	},

	{
		Operation: "update",
		Method:    "PATCH",
		Path:      "/v1/schemas/{namespace}/{slug}",
		Label:     "all params",
		Run:       _smokeCase19,
	},

	{
		Operation: "delete",
		Method:    "DELETE",
		Path:      "/v1/schemas/{namespace}/{slug}",
		Run:       _smokeCase20,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/v1/schemas/{namespace}/{slug}/version/{semver}",
		Run:       _smokeCase21,
	},

	{
		Operation: "delete",
		Method:    "DELETE",
		Path:      "/v1/schemas/{namespace}/{slug}/version/{semver}",
		Run:       _smokeCase22,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/schemas/{namespace}/{slug}/version",
		Label:     "required params",
		Run:       _smokeCase23,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/schemas/{namespace}/{slug}/version",
		Label:     "all params",
		Run:       _smokeCase24,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/schemas/{namespace}/{slug}/access-group",
		Run:       _smokeCase25,
	},

	{
		Operation: "delete",
		Method:    "DELETE",
		Path:      "/v1/schemas/{namespace}/{slug}/access-group",
		Run:       _smokeCase26,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/v1/login-portals/{slug}",
		Run:       _smokeCase27,
	},

	{
		Operation: "update",
		Method:    "PATCH",
		Path:      "/v1/login-portals/{slug}",
		Label:     "required params",
		Run:       _smokeCase28,
	},

	{
		Operation: "update",
		Method:    "PATCH",
		Path:      "/v1/login-portals/{slug}",
		Label:     "all params",
		Run:       _smokeCase29,
	},

	{
		Operation: "delete",
		Method:    "DELETE",
		Path:      "/v1/login-portals/{slug}",
		Run:       _smokeCase30,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/login-portals",
		Run:       _smokeCase31,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/login-portals",
		Run:       _smokeCase32,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/access-groups",
		Label:     "required params",
		Run:       _smokeCase33,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/access-groups",
		Label:     "all params",
		Run:       _smokeCase34,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/v1/access-groups/{slug}",
		Run:       _smokeCase35,
	},

	{
		Operation: "update",
		Method:    "PATCH",
		Path:      "/v1/access-groups/{slug}",
		Label:     "required params",
		Run:       _smokeCase36,
	},

	{
		Operation: "update",
		Method:    "PATCH",
		Path:      "/v1/access-groups/{slug}",
		Label:     "all params",
		Run:       _smokeCase37,
	},

	{
		Operation: "delete",
		Method:    "DELETE",
		Path:      "/v1/access-groups/{slug}",
		Run:       _smokeCase38,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/access-groups/{slug}/domains",
		Run:       _smokeCase39,
	},

	{
		Operation: "delete",
		Method:    "DELETE",
		Path:      "/v1/access-groups/{slug}/domains",
		Run:       _smokeCase40,
	},

	{
		Operation: "listRulesets",
		Method:    "GET",
		Path:      "/v1/rulesets/{namespace}",
		Run:       _smokeCase41,
	},

	{
		Operation: "createRuleset",
		Method:    "POST",
		Path:      "/v1/rulesets/{namespace}",
		Label:     "required params",
		Run:       _smokeCase42,
	},

	{
		Operation: "createRuleset",
		Method:    "POST",
		Path:      "/v1/rulesets/{namespace}",
		Label:     "all params",
		Run:       _smokeCase43,
	},

	{
		Operation: "updateRuleset",
		Method:    "PATCH",
		Path:      "/v1/rulesets/{namespace}/{slug}",
		Label:     "required params",
		Run:       _smokeCase44,
	},

	{
		Operation: "updateRuleset",
		Method:    "PATCH",
		Path:      "/v1/rulesets/{namespace}/{slug}",
		Label:     "all params",
		Run:       _smokeCase45,
	},

	{
		Operation: "deleteRuleset",
		Method:    "DELETE",
		Path:      "/v1/rulesets/{namespace}/{slug}",
		Run:       _smokeCase46,
	},

	{
		Operation: "retrieveRulesetDocument",
		Method:    "GET",
		Path:      "/v1/rulesets/{namespace}/{slug}",
		Run:       _smokeCase47,
	},

	{
		Operation: "createRulesetAccessGroup",
		Method:    "POST",
		Path:      "/v1/rulesets/{namespace}/{slug}/access-group",
		Run:       _smokeCase48,
	},

	{
		Operation: "deleteRulesetAccessGroup",
		Method:    "DELETE",
		Path:      "/v1/rulesets/{namespace}/{slug}/access-group",
		Run:       _smokeCase49,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/themes",
		Run:       _smokeCase50,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/themes",
		Label:     "required params",
		Run:       _smokeCase51,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/themes",
		Label:     "all params",
		Run:       _smokeCase52,
	},

	{
		Operation: "update",
		Method:    "PATCH",
		Path:      "/v1/themes/{slug}",
		Label:     "required params",
		Run:       _smokeCase53,
	},

	{
		Operation: "update",
		Method:    "PATCH",
		Path:      "/v1/themes/{slug}",
		Label:     "all params",
		Run:       _smokeCase54,
	},

	{
		Operation: "replaceDocument",
		Method:    "PUT",
		Path:      "/v1/themes/{slug}",
		Run:       _smokeCase55,
	},

	{
		Operation: "delete",
		Method:    "DELETE",
		Path:      "/v1/themes/{slug}",
		Run:       _smokeCase56,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/v1/themes/{slug}",
		Run:       _smokeCase57,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/teams",
		Run:       _smokeCase58,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/teams/members",
		Run:       _smokeCase59,
	},

	{
		Operation: "update",
		Method:    "PATCH",
		Path:      "/v1/teams/members/{uid}",
		Run:       _smokeCase60,
	},

	{
		Operation: "delete",
		Method:    "DELETE",
		Path:      "/v1/teams/members/{uid}",
		Run:       _smokeCase61,
	},

	{
		Operation: "member",
		Method:    "POST",
		Path:      "/v1/teams/invites",
		Run:       _smokeCase62,
	},

	{
		Operation: "resend",
		Method:    "PATCH",
		Path:      "/v1/teams/invites/{uid}",
		Run:       _smokeCase63,
	},

	{
		Operation: "cancel",
		Method:    "DELETE",
		Path:      "/v1/teams/invites/{uid}",
		Run:       _smokeCase64,
	},

	{
		Operation: "listGuides",
		Method:    "GET",
		Path:      "/v1/guides",
		Run:       _smokeCase65,
	},

	{
		Operation: "createGuide",
		Method:    "POST",
		Path:      "/v1/guides",
		Label:     "required params",
		Run:       _smokeCase66,
	},

	{
		Operation: "createGuide",
		Method:    "POST",
		Path:      "/v1/guides",
		Label:     "all params",
		Run:       _smokeCase67,
	},

	{
		Operation: "publishGuide",
		Method:    "POST",
		Path:      "/v1/guides/{slug}/publish",
		Run:       _smokeCase68,
	},

	{
		Operation: "listProjects",
		Method:    "GET",
		Path:      "/v1/docs",
		Label:     "required params",
		Run:       _smokeCase69,
	},

	{
		Operation: "listProjects",
		Method:    "GET",
		Path:      "/v1/docs",
		Label:     "all params",
		Run:       _smokeCase70,
	},

	{
		Operation: "createProject",
		Method:    "POST",
		Path:      "/v1/docs",
		Label:     "required params",
		Run:       _smokeCase71,
	},

	{
		Operation: "createProject",
		Method:    "POST",
		Path:      "/v1/docs",
		Label:     "all params",
		Run:       _smokeCase72,
	},

	{
		Operation: "retrieveProject",
		Method:    "GET",
		Path:      "/v1/docs/{slug}",
		Run:       _smokeCase73,
	},

	{
		Operation: "updateProject",
		Method:    "PATCH",
		Path:      "/v1/docs/{slug}",
		Label:     "required params",
		Run:       _smokeCase74,
	},

	{
		Operation: "updateProject",
		Method:    "PATCH",
		Path:      "/v1/docs/{slug}",
		Label:     "all params",
		Run:       _smokeCase75,
	},

	{
		Operation: "deleteProject",
		Method:    "DELETE",
		Path:      "/v1/docs/{slug}",
		Run:       _smokeCase76,
	},

	{
		Operation: "publishProject",
		Method:    "POST",
		Path:      "/v1/docs/{slug}/publish",
		Label:     "required params",
		Run:       _smokeCase77,
	},

	{
		Operation: "publishProject",
		Method:    "POST",
		Path:      "/v1/docs/{slug}/publish",
		Label:     "all params",
		Run:       _smokeCase78,
	},

	{
		Operation: "listProjectConfig",
		Method:    "GET",
		Path:      "/v1/docs/{slug}/config",
		Label:     "required params",
		Run:       _smokeCase79,
	},

	{
		Operation: "listProjectConfig",
		Method:    "GET",
		Path:      "/v1/docs/{slug}/config",
		Label:     "all params",
		Run:       _smokeCase80,
	},

	{
		Operation: "updateProjectConfig",
		Method:    "PUT",
		Path:      "/v1/docs/{slug}/config",
		Label:     "required params",
		Run:       _smokeCase81,
	},

	{
		Operation: "updateProjectConfig",
		Method:    "PUT",
		Path:      "/v1/docs/{slug}/config",
		Label:     "all params",
		Run:       _smokeCase82,
	},

	{
		Operation: "listProjectDomain",
		Method:    "GET",
		Path:      "/v1/docs/{slug}/domain",
		Run:       _smokeCase83,
	},

	{
		Operation: "listProjectDomainStatus",
		Method:    "GET",
		Path:      "/v1/docs/{slug}/domain/status",
		Run:       _smokeCase84,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/namespaces",
		Run:       _smokeCase85,
	},

	{
		Operation: "exchangePersonalToken",
		Method:    "POST",
		Path:      "/v1/auth/exchange",
		Run:       _smokeCase86,
	},

	{
		Operation: "listCurrentUser",
		Method:    "GET",
		Path:      "/v1/auth/me",
		Run:       _smokeCase87,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/sdks",
		Label:     "required params",
		Run:       _smokeCase88,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/sdks",
		Label:     "all params",
		Run:       _smokeCase89,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/sdks",
		Label:     "required params",
		Run:       _smokeCase90,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/sdks",
		Label:     "all params",
		Run:       _smokeCase91,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/v1/sdks/{uid}",
		Run:       _smokeCase92,
	},

	{
		Operation: "update",
		Method:    "PATCH",
		Path:      "/v1/sdks/{uid}",
		Label:     "required params",
		Run:       _smokeCase93,
	},

	{
		Operation: "update",
		Method:    "PATCH",
		Path:      "/v1/sdks/{uid}",
		Label:     "all params",
		Run:       _smokeCase94,
	},

	{
		Operation: "delete",
		Method:    "DELETE",
		Path:      "/v1/sdks/{uid}",
		Run:       _smokeCase95,
	},

	{
		Operation: "build",
		Method:    "POST",
		Path:      "/v1/sdks/{uid}/build",
		Label:     "required params",
		Run:       _smokeCase96,
	},

	{
		Operation: "build",
		Method:    "POST",
		Path:      "/v1/sdks/{uid}/build",
		Label:     "all params",
		Run:       _smokeCase97,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/sdks/{uid}/versions",
		Run:       _smokeCase98,
	},

	{
		Operation: "delete",
		Method:    "DELETE",
		Path:      "/v1/sdks/{uid}/versions/{version}",
		Run:       _smokeCase99,
	},

	{
		Operation: "link",
		Method:    "POST",
		Path:      "/v1/sdks/{uid}/repositories",
		Label:     "required params",
		Run:       _smokeCase100,
	},

	{
		Operation: "link",
		Method:    "POST",
		Path:      "/v1/sdks/{uid}/repositories",
		Label:     "all params",
		Run:       _smokeCase101,
	},

	{
		Operation: "unlink",
		Method:    "DELETE",
		Path:      "/v1/sdks/{uid}/repositories/{language}",
		Run:       _smokeCase102,
	},

	{
		Operation: "updatePublishing",
		Method:    "POST",
		Path:      "/v1/sdks/{uid}/repositories/{language}/publishing",
		Label:     "required params",
		Run:       _smokeCase103,
	},

	{
		Operation: "updatePublishing",
		Method:    "POST",
		Path:      "/v1/sdks/{uid}/repositories/{language}/publishing",
		Label:     "all params",
		Run:       _smokeCase104,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/mcp/servers",
		Run:       _smokeCase105,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/mcp/servers",
		Label:     "required params",
		Run:       _smokeCase106,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/mcp/servers",
		Label:     "all params",
		Run:       _smokeCase107,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/v1/mcp/servers/{id}",
		Run:       _smokeCase108,
	},

	{
		Operation: "update",
		Method:    "PATCH",
		Path:      "/v1/mcp/servers/{id}",
		Label:     "required params",
		Run:       _smokeCase109,
	},

	{
		Operation: "update",
		Method:    "PATCH",
		Path:      "/v1/mcp/servers/{id}",
		Label:     "all params",
		Run:       _smokeCase110,
	},

	{
		Operation: "delete",
		Method:    "DELETE",
		Path:      "/v1/mcp/servers/{id}",
		Run:       _smokeCase111,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/mcp/servers/{id}/installations",
		Run:       _smokeCase112,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/mcp/servers/{id}/installations",
		Label:     "required params",
		Run:       _smokeCase113,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/mcp/servers/{id}/installations",
		Label:     "all params",
		Run:       _smokeCase114,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/v1/mcp/servers/{id}/installations/{installationId}",
		Run:       _smokeCase115,
	},

	{
		Operation: "update",
		Method:    "PATCH",
		Path:      "/v1/mcp/servers/{id}/installations/{installationId}",
		Label:     "required params",
		Run:       _smokeCase116,
	},

	{
		Operation: "update",
		Method:    "PATCH",
		Path:      "/v1/mcp/servers/{id}/installations/{installationId}",
		Label:     "all params",
		Run:       _smokeCase117,
	},

	{
		Operation: "delete",
		Method:    "DELETE",
		Path:      "/v1/mcp/servers/{id}/installations/{installationId}",
		Run:       _smokeCase118,
	},

	{
		Operation: "createAccessGroup",
		Method:    "POST",
		Path:      "/v1/mcp/servers/{id}/installations/{installationId}/access-group",
		Run:       _smokeCase119,
	},

	{
		Operation: "deleteAccessGroup",
		Method:    "DELETE",
		Path:      "/v1/mcp/servers/{id}/installations/{installationId}/access-group",
		Run:       _smokeCase120,
	},
}

func selectedCases() []smokeCase {
	filter := os.Getenv("SCALAR_SMOKE_FILTER")
	if filter == "" {
		return cases
	}
	needles := strings.Split(filter, ",")
	selected := make([]smokeCase, 0, len(cases))
	for _, testCase := range cases {
		for _, needle := range needles {
			needle = strings.TrimSpace(needle)
			if needle == "" {
				continue
			}
			if strings.Contains(testCase.Operation, needle) || strings.Contains(testCase.Path, needle) {
				selected = append(selected, testCase)
				break
			}
		}
	}
	return selected
}

// How many cases run at once. A large SDK has hundreds of operations, and one goroutine per case
// puts more requests in flight than the client's transport pools connections for. SCALAR_SMOKE_CONCURRENCY
// overrides the cap; anything unparseable falls back to the default.
func smokeConcurrency(caseCount int) int {
	limit := 32
	if override, err := strconv.Atoi(os.Getenv("SCALAR_SMOKE_CONCURRENCY")); err == nil && override > 0 {
		limit = override
	}
	if caseCount < limit {
		return caseCount
	}
	return limit
}

func runCase(testCase smokeCase) (result smokeResult) {
	startedAt := time.Now()
	result = smokeResult{
		Operation: testCase.Operation,
		Method:    testCase.Method,
		Path:      testCase.Path,
		Label:     testCase.Label,
		Status:    "passed",
	}
	defer func() {
		result.DurationMs = time.Since(startedAt).Milliseconds()
		if recovered := recover(); recovered != nil {
			result.Status = "failed"
			result.Error = fmt.Sprint(recovered)
		}
	}()
	testCase.Run()
	return result
}

func main() {
	selected := selectedCases()
	results := make([]smokeResult, len(selected))
	var wg sync.WaitGroup
	// Buffered channel as a counting semaphore: every goroutine still starts, but only
	// smokeConcurrency of them hold a slot — and so have a request in flight — at a time.
	semaphore := make(chan struct{}, smokeConcurrency(len(selected)))
	for index, testCase := range selected {
		wg.Add(1)
		go func(index int, testCase smokeCase) {
			defer wg.Done()
			semaphore <- struct{}{}
			defer func() { <-semaphore }()
			results[index] = runCase(testCase)
		}(index, testCase)
	}
	wg.Wait()

	failed := 0
	for _, result := range results {
		if result.Status == "failed" {
			failed++
		}
	}

	report := map[string]interface{}{"total": len(results), "failed": failed, "results": results}
	if reportPath := os.Getenv("SCALAR_SMOKE_REPORT"); reportPath != "" {
		bytes, err := json.Marshal(report)
		if err != nil {
			panic(err)
		}
		if err := os.WriteFile(reportPath, bytes, 0o644); err != nil {
			panic(err)
		}
	} else {
		for _, result := range results {
			suffix := ""
			if result.Label != "" {
				suffix = " [" + result.Label + "]"
			}
			if result.Status == "passed" {
				fmt.Printf("PASS %s%s (%s %s) %dms\n", result.Operation, suffix, result.Method, result.Path, result.DurationMs)
			} else {
				fmt.Fprintf(os.Stderr, "FAIL %s%s (%s %s)\n%s\n", result.Operation, suffix, result.Method, result.Path, result.Error)
			}
		}
		if len(results) == 0 {
			fmt.Fprintln(os.Stderr, "No code samples ran (empty SDK or a SCALAR_SMOKE_FILTER that matched nothing).")
		} else {
			fmt.Printf("\n%d/%d samples passed\n", len(results)-failed, len(results))
		}
	}

	if failed > 0 || len(results) == 0 {
		os.Exit(1)
	}
}
