// Code generated by Scalar SDK Generator. DO NOT EDIT.

package shared

import (
	"github.com/scalar/scalar-go/internal/apijson"
)

type Value400 struct {
	Code    string       `json:"code" api:"required"`
	Message string       `json:"message" api:"required"`
	JSON    value400JSON `json:"-"`
}

// value400JSON contains the JSON metadata for the struct [Value400]
type value400JSON struct {
	Code        apijson.Field
	Message     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *Value400) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r value400JSON) RawJSON() string {
	return r.raw
}

type Value401 struct {
	Code    string       `json:"code" api:"required"`
	Message string       `json:"message" api:"required"`
	JSON    value401JSON `json:"-"`
}

// value401JSON contains the JSON metadata for the struct [Value401]
type value401JSON struct {
	Code        apijson.Field
	Message     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *Value401) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r value401JSON) RawJSON() string {
	return r.raw
}

type Value403 struct {
	Code    string       `json:"code" api:"required"`
	Message string       `json:"message" api:"required"`
	JSON    value403JSON `json:"-"`
}

// value403JSON contains the JSON metadata for the struct [Value403]
type value403JSON struct {
	Code        apijson.Field
	Message     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *Value403) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r value403JSON) RawJSON() string {
	return r.raw
}

type Value404 struct {
	Code    string       `json:"code" api:"required"`
	Message string       `json:"message" api:"required"`
	JSON    value404JSON `json:"-"`
}

// value404JSON contains the JSON metadata for the struct [Value404]
type value404JSON struct {
	Code        apijson.Field
	Message     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *Value404) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r value404JSON) RawJSON() string {
	return r.raw
}

type Value422 struct {
	Code    string       `json:"code" api:"required"`
	Message string       `json:"message" api:"required"`
	JSON    value422JSON `json:"-"`
}

// value422JSON contains the JSON metadata for the struct [Value422]
type value422JSON struct {
	Code        apijson.Field
	Message     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *Value422) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r value422JSON) RawJSON() string {
	return r.raw
}

type Value500 struct {
	Code    string       `json:"code" api:"required"`
	Message string       `json:"message" api:"required"`
	JSON    value500JSON `json:"-"`
}

// value500JSON contains the JSON metadata for the struct [Value500]
type value500JSON struct {
	Code        apijson.Field
	Message     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *Value500) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r value500JSON) RawJSON() string {
	return r.raw
}

type Nanoid = string

type Namespace = string

type ManagedDocVersion struct {
	CreatedAt     float64                      `json:"createdAt" api:"required"`
	EmbedStatus   ManagedDocVersionEmbedStatus `json:"embedStatus" api:"required,nullable"`
	EndpointCount int64                        `json:"endpointCount" api:"required,nullable"`
	Tags          []string                     `json:"tags" api:"required"`
	UID           string                       `json:"uid" api:"required"`
	Upgraded      bool                         `json:"upgraded" api:"required"`
	Version       string                       `json:"version" api:"required"`
	JsonSha       string                       `json:"jsonSha"`
	Tools         []ManagedDocVersionTool      `json:"tools"`
	YamlSha       string                       `json:"yamlSha"`
	JSON          managedDocVersionJSON        `json:"-"`
}

// managedDocVersionJSON contains the JSON metadata for the struct [ManagedDocVersion]
type managedDocVersionJSON struct {
	CreatedAt     apijson.Field
	EmbedStatus   apijson.Field
	EndpointCount apijson.Field
	Tags          apijson.Field
	UID           apijson.Field
	Upgraded      apijson.Field
	Version       apijson.Field
	JsonSha       apijson.Field
	Tools         apijson.Field
	YamlSha       apijson.Field
	raw           string
	ExtraFields   map[string]apijson.Field
}

func (r *ManagedDocVersion) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r managedDocVersionJSON) RawJSON() string {
	return r.raw
}

type ManagedDocVersionTool struct {
	EnabledTools []ManagedDocVersionToolsEnabledTool `json:"enabledTools" api:"required"`
	Method       string                              `json:"method" api:"required"`
	Path         string                              `json:"path" api:"required"`
	JSON         managedDocVersionToolJSON           `json:"-"`
}

// managedDocVersionToolJSON contains the JSON metadata for the struct [ManagedDocVersionTool]
type managedDocVersionToolJSON struct {
	EnabledTools apijson.Field
	Method       apijson.Field
	Path         apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *ManagedDocVersionTool) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r managedDocVersionToolJSON) RawJSON() string {
	return r.raw
}

type ManagedDocVersionToolsEnabledTool string

const (
	ManagedDocVersionToolsEnabledToolExecuteRequest     ManagedDocVersionToolsEnabledTool = "execute-request"
	ManagedDocVersionToolsEnabledToolGetMiniOpenapiSpec ManagedDocVersionToolsEnabledTool = "get-mini-openapi-spec"
)

func (r ManagedDocVersionToolsEnabledTool) IsKnown() bool {
	switch r {
	case ManagedDocVersionToolsEnabledToolExecuteRequest, ManagedDocVersionToolsEnabledToolGetMiniOpenapiSpec:
		return true
	}
	return false
}

type ManagedDocVersionEmbedStatus string

const (
	ManagedDocVersionEmbedStatusComplete ManagedDocVersionEmbedStatus = "complete"
	ManagedDocVersionEmbedStatusFailed   ManagedDocVersionEmbedStatus = "failed"
)

func (r ManagedDocVersionEmbedStatus) IsKnown() bool {
	switch r {
	case ManagedDocVersionEmbedStatusComplete, ManagedDocVersionEmbedStatusFailed:
		return true
	}
	return false
}

type Timestamp = int64

type UID struct {
	UID  string  `json:"uid" api:"required"`
	JSON uidJSON `json:"-"`
}

// uidJSON contains the JSON metadata for the struct [UID]
type uidJSON struct {
	UID         apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *UID) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r uidJSON) RawJSON() string {
	return r.raw
}
