// Code generated by Scalar SDK Generator. DO NOT EDIT.

package shared

import (
	"github.com/scalar/scalar-go/internal/apijson"
)

type Value400 struct {
	Message string       `json:"message" api:"required"`
	Code    string       `json:"code" api:"required"`
	JSON    value400JSON `json:"-"`
}

// value400JSON contains the JSON metadata for the struct [Value400]
type value400JSON struct {
	Message     apijson.Field
	Code        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *Value400) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r value400JSON) RawJSON() string {
	return r.raw
}

type Value401 struct {
	Message string       `json:"message" api:"required"`
	Code    string       `json:"code" api:"required"`
	JSON    value401JSON `json:"-"`
}

// value401JSON contains the JSON metadata for the struct [Value401]
type value401JSON struct {
	Message     apijson.Field
	Code        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *Value401) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r value401JSON) RawJSON() string {
	return r.raw
}

type Value403 struct {
	Message string       `json:"message" api:"required"`
	Code    string       `json:"code" api:"required"`
	JSON    value403JSON `json:"-"`
}

// value403JSON contains the JSON metadata for the struct [Value403]
type value403JSON struct {
	Message     apijson.Field
	Code        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *Value403) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r value403JSON) RawJSON() string {
	return r.raw
}

type Value404 struct {
	Message string       `json:"message" api:"required"`
	Code    string       `json:"code" api:"required"`
	JSON    value404JSON `json:"-"`
}

// value404JSON contains the JSON metadata for the struct [Value404]
type value404JSON struct {
	Message     apijson.Field
	Code        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *Value404) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r value404JSON) RawJSON() string {
	return r.raw
}

type Value422 struct {
	Message string       `json:"message" api:"required"`
	Code    string       `json:"code" api:"required"`
	JSON    value422JSON `json:"-"`
}

// value422JSON contains the JSON metadata for the struct [Value422]
type value422JSON struct {
	Message     apijson.Field
	Code        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *Value422) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r value422JSON) RawJSON() string {
	return r.raw
}

type Value500 struct {
	Message string       `json:"message" api:"required"`
	Code    string       `json:"code" api:"required"`
	JSON    value500JSON `json:"-"`
}

// value500JSON contains the JSON metadata for the struct [Value500]
type value500JSON struct {
	Message     apijson.Field
	Code        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *Value500) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r value500JSON) RawJSON() string {
	return r.raw
}

type Nanoid = string

type Namespace = string

type ManagedDocVersion struct {
	UID         string                       `json:"uid" api:"required"`
	CreatedAt   float64                      `json:"createdAt" api:"required"`
	Version     string                       `json:"version" api:"required"`
	Upgraded    bool                         `json:"upgraded" api:"required"`
	EmbedStatus ManagedDocVersionEmbedStatus `json:"embedStatus" api:"required,nullable"`
	Tags        []string                     `json:"tags" api:"required"`
	Tools       []ManagedDocVersionTool      `json:"tools"`
	YamlSha     string                       `json:"yamlSha"`
	JsonSha     string                       `json:"jsonSha"`
	VersionSha  string                       `json:"versionSha"`
	JSON        managedDocVersionJSON        `json:"-"`
}

// managedDocVersionJSON contains the JSON metadata for the struct [ManagedDocVersion]
type managedDocVersionJSON struct {
	UID         apijson.Field
	CreatedAt   apijson.Field
	Version     apijson.Field
	Upgraded    apijson.Field
	EmbedStatus apijson.Field
	Tags        apijson.Field
	Tools       apijson.Field
	YamlSha     apijson.Field
	JsonSha     apijson.Field
	VersionSha  apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *ManagedDocVersion) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r managedDocVersionJSON) RawJSON() string {
	return r.raw
}

type ManagedDocVersionTool struct {
	Path         string                              `json:"path" api:"required"`
	Method       ManagedDocVersionToolsMethod        `json:"method" api:"required"`
	EnabledTools []ManagedDocVersionToolsEnabledTool `json:"enabledTools" api:"required"`
	JSON         managedDocVersionToolJSON           `json:"-"`
}

// managedDocVersionToolJSON contains the JSON metadata for the struct [ManagedDocVersionTool]
type managedDocVersionToolJSON struct {
	Path         apijson.Field
	Method       apijson.Field
	EnabledTools apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *ManagedDocVersionTool) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r managedDocVersionToolJSON) RawJSON() string {
	return r.raw
}

type ManagedDocVersionToolsMethod string

const (
	ManagedDocVersionToolsMethodDelete  ManagedDocVersionToolsMethod = "delete"
	ManagedDocVersionToolsMethodGet     ManagedDocVersionToolsMethod = "get"
	ManagedDocVersionToolsMethodHead    ManagedDocVersionToolsMethod = "head"
	ManagedDocVersionToolsMethodOptions ManagedDocVersionToolsMethod = "options"
	ManagedDocVersionToolsMethodPatch   ManagedDocVersionToolsMethod = "patch"
	ManagedDocVersionToolsMethodPost    ManagedDocVersionToolsMethod = "post"
	ManagedDocVersionToolsMethodPut     ManagedDocVersionToolsMethod = "put"
	ManagedDocVersionToolsMethodTrace   ManagedDocVersionToolsMethod = "trace"
)

func (r ManagedDocVersionToolsMethod) IsKnown() bool {
	switch r {
	case ManagedDocVersionToolsMethodDelete, ManagedDocVersionToolsMethodGet, ManagedDocVersionToolsMethodHead, ManagedDocVersionToolsMethodOptions, ManagedDocVersionToolsMethodPatch, ManagedDocVersionToolsMethodPost, ManagedDocVersionToolsMethodPut, ManagedDocVersionToolsMethodTrace:
		return true
	}
	return false
}

type ManagedDocVersionToolsEnabledTool string

const (
	ManagedDocVersionToolsEnabledToolExecuteRequest     ManagedDocVersionToolsEnabledTool = "execute-request"
	ManagedDocVersionToolsEnabledToolGetMiniOpenapiSpec ManagedDocVersionToolsEnabledTool = "get-mini-openapi-spec"
)

func (r ManagedDocVersionToolsEnabledTool) IsKnown() bool {
	switch r {
	case ManagedDocVersionToolsEnabledToolExecuteRequest, ManagedDocVersionToolsEnabledToolGetMiniOpenapiSpec:
		return true
	}
	return false
}

type ManagedDocVersionEmbedStatus string

const (
	ManagedDocVersionEmbedStatusComplete ManagedDocVersionEmbedStatus = "complete"
	ManagedDocVersionEmbedStatusFailed   ManagedDocVersionEmbedStatus = "failed"
)

func (r ManagedDocVersionEmbedStatus) IsKnown() bool {
	switch r {
	case ManagedDocVersionEmbedStatusComplete, ManagedDocVersionEmbedStatusFailed:
		return true
	}
	return false
}

type Timestamp = int64

type UID struct {
	UID  string  `json:"uid" api:"required"`
	JSON uidJSON `json:"-"`
}

// uidJSON contains the JSON metadata for the struct [UID]
type uidJSON struct {
	UID         apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *UID) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r uidJSON) RawJSON() string {
	return r.raw
}
